import { ArrowRight, ChevronDown, RefreshCw, Sparkles } from 'lucide-react'
import { useMemo, useState } from 'react'

import { Button } from '@/components/ui/button'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible'
import { Skeleton } from '@/components/ui/skeleton'
import { cn } from '@/lib/utils'
import { renderCompactSummaryHtml } from '@/pages/search/aiSummary'
import { useSearchSummary } from '@/pages/search/useSearchSummary'
import type { SearchSummaryResponse } from '@/services/searchService'

interface SearchModalAiSummaryProps {
  teamId: string
  /** The trimmed, non-empty query typed into the dialog. */
  query: string
  /** Open `/search` for this query with the AI Summary pre-expanded. */
  onSeeFullResults: () => void
}

/**
 * Compact, collapsed-by-default AI Summary row in the header search dialog
 * (#1079).
 *
 * Nothing is requested until the user expands the row; typing never does.
 * The summary lives in the shared search-summary store under the same key
 * `/search?q=…` uses without filters, so "See full results" reuses it rather
 * than regenerating, and closing the dialog mid-request still caches the
 * answer. Editing the query changes the key, which collapses the row.
 */
export function SearchModalAiSummary({
  teamId,
  query,
  onSeeFullResults,
}: Readonly<SearchModalAiSummaryProps>) {
  const summary = useSearchSummary(teamId, query, undefined, undefined)
  // Expansion belongs to one search: a new query is a new key, so the row
  // collapses by itself instead of generating for every edit.
  const [expandedKey, setExpandedKey] = useState<string | null>(null)
  const open = expandedKey !== null && expandedKey === summary.key

  const handleOpenChange = (next: boolean) => {
    if (!next || !summary.key) {
      setExpandedKey(null)
      return
    }
    setExpandedKey(summary.key)
    summary.generate()
  }

  return (
    <Collapsible
      open={open}
      onOpenChange={handleOpenChange}
      className="rounded-md border"
    >
      <CollapsibleTrigger className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm font-medium">
        <Sparkles className="size-4 shrink-0" />
        <span className="flex-1">AI Summary</span>
        <ChevronDown
          className={cn(
            'size-4 shrink-0 transition-transform',
            open && 'rotate-180'
          )}
        />
      </CollapsibleTrigger>
      <CollapsibleContent className="px-3 pb-3">
        {summary.state === undefined || summary.state.status === 'loading' ? (
          <div
            data-testid="ai-summary-skeleton"
            aria-busy="true"
            aria-label="Generating summary"
            className="space-y-2"
          >
            <Skeleton className="h-3 w-full" />
            <Skeleton className="h-3 w-full" />
            <Skeleton className="h-3 w-2/3" />
          </div>
        ) : summary.state.status === 'error' ? (
          <div role="alert" className="flex flex-col items-start gap-2 text-sm">
            <p className="text-destructive">{summary.state.message}</p>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={summary.retry}
            >
              <RefreshCw className="size-3.5" />
              Retry
            </Button>
          </div>
        ) : (
          <CompactSummary
            data={summary.state.data}
            onSeeFullResults={onSeeFullResults}
          />
        )}
      </CollapsibleContent>
    </Collapsible>
  )
}

function CompactSummary({
  data,
  onSeeFullResults,
}: Readonly<{ data: SearchSummaryResponse; onSeeFullResults: () => void }>) {
  const html = useMemo(
    () => renderCompactSummaryHtml(data.summary, data.sources),
    [data.summary, data.sources]
  )

  return (
    <div className="space-y-2">
      <div className="relative max-h-40 overflow-hidden">
        <div
          data-testid="ai-summary-compact"
          className="prose prose-sm dark:prose-invert max-w-none"
          // Sanitized by renderCompactSummaryHtml (DOMPurify) — the summary is
          // untrusted LLM output.
          dangerouslySetInnerHTML={{ __html: html }}
        />
        <div
          aria-hidden="true"
          className="from-background pointer-events-none absolute inset-x-0 bottom-0 h-8 bg-gradient-to-t"
        />
      </div>
      <div className="flex items-center justify-between gap-2">
        <p className="text-muted-foreground text-xs">
          Generated by {data.model}
        </p>
        <Button
          type="button"
          variant="link"
          size="sm"
          className="h-auto p-0"
          onClick={onSeeFullResults}
        >
          See full results
          <ArrowRight className="size-3.5" />
        </Button>
      </div>
    </div>
  )
}
