// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MocktaskSubmitter is an autogenerated mock type for the taskSubmitter type
type MocktaskSubmitter struct {
	mock.Mock
}

type MocktaskSubmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MocktaskSubmitter) EXPECT() *MocktaskSubmitter_Expecter {
	return &MocktaskSubmitter_Expecter{mock: &_m.Mock}
}

// Submit provides a mock function with given fields: task
func (_m *MocktaskSubmitter) Submit(task func()) {
	_m.Called(task)
}

// MocktaskSubmitter_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type MocktaskSubmitter_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - task func()
func (_e *MocktaskSubmitter_Expecter) Submit(task interface{}) *MocktaskSubmitter_Submit_Call {
	return &MocktaskSubmitter_Submit_Call{Call: _e.mock.On("Submit", task)}
}

func (_c *MocktaskSubmitter_Submit_Call) Run(run func(task func())) *MocktaskSubmitter_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *MocktaskSubmitter_Submit_Call) Return() *MocktaskSubmitter_Submit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MocktaskSubmitter_Submit_Call) RunAndReturn(run func(func())) *MocktaskSubmitter_Submit_Call {
	_c.Run(run)
	return _c
}

// NewMocktaskSubmitter creates a new instance of MocktaskSubmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktaskSubmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocktaskSubmitter {
	mock := &MocktaskSubmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
