-- Revert the consolidated baseline: drop every object it created and return the
-- public schema to empty. golang-migrate's own schema_migrations table is left
-- intact so the migrator can still record the version change.
DROP TABLE IF EXISTS public.activities CASCADE;
DROP TABLE IF EXISTS public.agent_execution_events CASCADE;
DROP TABLE IF EXISTS public.agent_executions CASCADE;
DROP TABLE IF EXISTS public.agents CASCADE;
DROP TABLE IF EXISTS public.api_key_integration_permissions CASCADE;
DROP TABLE IF EXISTS public.api_key_integrations_catalog CASCADE;
DROP TABLE IF EXISTS public.api_keys CASCADE;
DROP TABLE IF EXISTS public.artifacts CASCADE;
DROP TABLE IF EXISTS public.attachments CASCADE;
DROP TABLE IF EXISTS public.blueprints CASCADE;
DROP TABLE IF EXISTS public.claude_code_hooks_payload CASCADE;
DROP TABLE IF EXISTS public.content_versions CASCADE;
DROP TABLE IF EXISTS public.cursor_ide_hooks_payload CASCADE;
DROP TABLE IF EXISTS public.device_tokens CASCADE;
DROP TABLE IF EXISTS public.embedding_providers CASCADE;
DROP TABLE IF EXISTS public.embeddings CASCADE;
DROP TABLE IF EXISTS public.feed_item_replies CASCADE;
DROP TABLE IF EXISTS public.feed_items CASCADE;
DROP TABLE IF EXISTS public.feeds CASCADE;
DROP TABLE IF EXISTS public.financial_kpi_snapshots CASCADE;
DROP TABLE IF EXISTS public.github_installation_repositories CASCADE;
DROP TABLE IF EXISTS public.github_installations CASCADE;
DROP TABLE IF EXISTS public.memories CASCADE;
DROP TABLE IF EXISTS public.notification_deliveries CASCADE;
DROP TABLE IF EXISTS public.notification_digest_queue CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.prompt_gallery_templates CASCADE;
DROP TABLE IF EXISTS public.prompt_references CASCADE;
DROP TABLE IF EXISTS public.prompt_share_access CASCADE;
DROP TABLE IF EXISTS public.prompt_shares CASCADE;
DROP TABLE IF EXISTS public.prompts CASCADE;
DROP TABLE IF EXISTS public.resource_access_events CASCADE;
DROP TABLE IF EXISTS public.team_invitations CASCADE;
DROP TABLE IF EXISTS public.team_members CASCADE;
DROP TABLE IF EXISTS public.team_subscriptions CASCADE;
DROP TABLE IF EXISTS public.teams CASCADE;
DROP TABLE IF EXISTS public.test_table CASCADE;
DROP TABLE IF EXISTS public.types CASCADE;
DROP TABLE IF EXISTS public.user_preferences CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.webhook_events CASCADE;
DROP FUNCTION IF EXISTS public.update_agents_updated_at() CASCADE;
DROP FUNCTION IF EXISTS public.update_updated_at_column() CASCADE;
DROP EXTENSION IF EXISTS vector;
DROP EXTENSION IF EXISTS "uuid-ossp";
