-- Revert 107. The embeddings table is a derived cache, so TRUNCATE is safe; the
-- vectors must be regenerated by the active embedding provider afterwards anyway.
-- This restores the column to the 768-dim width set by migration 101.
TRUNCATE embeddings;

DROP INDEX IF EXISTS idx_embeddings_vector_cosine;

ALTER TABLE embeddings ALTER COLUMN vector_embeddings TYPE vector(768);

CREATE INDEX idx_embeddings_vector_cosine ON embeddings USING hnsw (vector_embeddings vector_cosine_ops);
