import type { BodyEditorView } from '@/components/patterns/resource'
import type { Project } from '@/services/projectService'

export interface PromptFormData {
  name: string
  slug: string
  description: string
  body: string
  status: 'draft' | 'published'
  mcp_expose: boolean
  labels: string[]
  project_id: string
}

/** The prompt editor's tabs are the shared body editor's — one vocabulary, not two. */
export type EditorView = BodyEditorView

export interface EditorSettingsProps {
  formData: PromptFormData
  errors: Partial<PromptFormData>
  projects: Project[]
  loadingProjects: boolean
  isCheckingSlug: boolean
  slugAutoGenerated: boolean
  onSlugChange: (slug: string) => void
  onFormDataChange: (updater: (prev: PromptFormData) => PromptFormData) => void
}
