import { ArrowLeft, Save } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { useLocation, useNavigate, useParams } from 'react-router-dom'

import { PageHeader } from '@/components/PageHeader'
import { PromptTemplateLoader } from '@/components/PromptTemplateLoader'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { useTeam } from '@/contexts/TeamContext'
import { useAnalytics } from '@/hooks'
import { toast } from '@/lib/toast'
import type { Project } from '@/services/projectService'
import { projectService } from '@/services/projectService'
import type { Prompt } from '@/services/promptService'
import { promptService } from '@/services/promptService'
import { ANALYTICS_EVENTS } from '@/types/analytics'
import { getErrorMessage } from '@/utils/errorHandling'

import { EditorPane } from './editor/EditorPane'
import { EditorSettings } from './editor/EditorSettings'
import type { EditorView, PromptFormData } from './editor/types'
import { usePromptSave } from './editor/usePromptSave'
import { useRenderPreview } from './editor/useRenderPreview'
import { slugify, useSlugGeneration } from './editor/useSlugGeneration'

function initialFormData(
  prefilled: {
    title?: string
    body?: string
    description?: string
  } | null
): PromptFormData {
  return {
    name: prefilled?.title ? `Based on: ${prefilled.title}` : '',
    slug: '',
    description: prefilled?.description ?? '',
    body: prefilled?.body ?? '',
    status: 'draft',
    mcp_expose: false,
    labels: [],
    project_id: '',
  }
}

function validate(formData: PromptFormData): Partial<PromptFormData> {
  const errors: Partial<PromptFormData> = {}
  if (!formData.project_id.trim()) errors.project_id = 'Project is required'
  if (!formData.name.trim()) errors.name = 'Name is required'
  if (!formData.slug.trim()) {
    errors.slug = 'Slug is required'
  } else if (/[^a-z0-9-]/.test(formData.slug)) {
    errors.slug =
      'Slug must contain only lowercase letters, numbers, and hyphens'
  }
  if (formData.description.length > 200) {
    errors.description = 'Description cannot be longer than 200 characters'
  }
  if (!formData.body.trim()) errors.body = 'Prompt content is required'
  return errors
}

export function PromptEditor() {
  const navigate = useNavigate()
  const location = useLocation()
  const { slug } = useParams<{ slug: string }>()
  const { currentTeam, isLoading: isLoadingTeam } = useTeam()
  const { trackEvent } = useAnalytics()

  const prefilledData = location.state as {
    title?: string
    body?: string
    description?: string
  } | null

  const [loading, setLoading] = useState(!!slug)
  const [view, setView] = useState<EditorView>('write')
  const [showTemplateLoader, setShowTemplateLoader] = useState(false)
  const [prompt, setPrompt] = useState<Prompt | null>(null)
  const [formData, setFormData] = useState<PromptFormData>(
    initialFormData(prefilledData)
  )
  const [projects, setProjects] = useState<Project[]>([])
  const [loadingProjects, setLoadingProjects] = useState(true)
  const [errors, setErrors] = useState<Partial<PromptFormData>>({})
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true)

  const isEditing = !!slug
  const pageTitle = isEditing ? 'Edit prompt' : 'Create new prompt'

  const { isCheckingSlug, generateUniqueSlug } = useSlugGeneration(
    currentTeam,
    prompt?.slug
  )
  const { saving, save } = usePromptSave({
    teamId: currentTeam?.id,
    prompt,
    trackEvent,
  })
  const {
    allPlaceholders,
    placeholderValues,
    setPlaceholderValue,
    renderedBody,
    renderError,
    isRendering,
    isLoadingPlaceholders,
    fetchAllPlaceholders,
  } = useRenderPreview({
    teamId: currentTeam?.id,
    prompt,
    view,
    isEditing,
  })

  const loadPrompt = useCallback(
    async (promptSlug: string) => {
      if (!currentTeam) {
        toast.error('No team selected')
        return
      }
      try {
        setLoading(true)
        const p = await promptService.getPrompt(currentTeam.id, promptSlug)
        setPrompt(p)
        setFormData({
          name: p.name,
          slug: p.slug,
          description: p.description,
          body: p.body,
          status: p.status,
          mcp_expose: p.mcp_expose,
          labels: p.labels ?? [],
          project_id: p.project_id,
        })
      } catch (error) {
        toast.error(getErrorMessage(error, 'Failed to load prompt'))
        void navigate('/prompts')
      } finally {
        setLoading(false)
      }
    },
    [navigate, currentTeam]
  )

  useEffect(() => {
    const fetchProjects = async () => {
      if (!currentTeam) return
      try {
        setLoadingProjects(true)
        const response = await projectService.getProjects(currentTeam.id, {})
        setProjects(response.projects)
        if (!isEditing && response.projects.length === 1) {
          setFormData(prev => ({
            ...prev,
            project_id: response.projects[0].id,
          }))
        }
      } catch {
        setProjects([])
      } finally {
        setLoadingProjects(false)
      }
    }
    void fetchProjects()
  }, [currentTeam, isEditing])

  useEffect(() => {
    if (slug && !isLoadingTeam) {
      void loadPrompt(slug)
    }
  }, [slug, loadPrompt, isLoadingTeam])

  const handleNameChange = async (name: string) => {
    const newSlug = slugAutoGenerated ? slugify(name) : formData.slug
    setFormData(prev => ({ ...prev, name, slug: newSlug }))

    if (!isEditing && slugAutoGenerated && newSlug) {
      const uniqueSlug = await generateUniqueSlug(newSlug)
      if (uniqueSlug !== newSlug) {
        setFormData(prev => ({ ...prev, slug: uniqueSlug }))
      }
    }
  }

  const handleSlugChange = (s: string) => {
    setSlugAutoGenerated(false)
    setFormData(prev => ({ ...prev, slug: s }))
  }

  useEffect(() => {
    if (!formData.slug || isEditing || slugAutoGenerated) return
    const timeoutId = setTimeout(() => {
      void generateUniqueSlug(formData.slug).then(uniqueSlug => {
        if (uniqueSlug !== formData.slug) {
          setFormData(prev => ({ ...prev, slug: uniqueSlug }))
        }
      })
    }, 1000)
    return () => {
      clearTimeout(timeoutId)
    }
  }, [formData.slug, generateUniqueSlug, isEditing, slugAutoGenerated])

  const handleSave = async () => {
    const validation = validate(formData)
    setErrors(validation)
    if (Object.keys(validation).length > 0) {
      toast.error('Please fix the validation errors')
      return
    }

    const savedSlug = await save(formData)
    if (savedSlug) {
      void navigate(`/prompts/${savedSlug}`)
    }
  }

  const handleLoadTemplate = (templatePrompt: Prompt) => {
    if (
      formData.body.trim() &&
      !confirm(
        'Loading a template will replace your current content. Continue?'
      )
    ) {
      return
    }
    setFormData(prev => ({
      ...prev,
      name: prev.name || `${templatePrompt.name} (Copy)`,
      slug: prev.slug || slugify(`${templatePrompt.name}-copy`),
      description: templatePrompt.description,
      body: templatePrompt.body,
    }))
    toast.success(`Template "${templatePrompt.name}" loaded`)
  }

  const handleViewChange = async (next: EditorView) => {
    setView(next)
    const basePayload = {
      prompt_id: slug ?? 'new',
      prompt_title: formData.name || 'Untitled',
      action_context: 'preview' as const,
    }
    if (next === 'preview') {
      trackEvent({
        event: ANALYTICS_EVENTS.PROMPT_PREVIEW_VIEWED,
        properties: basePayload,
      })
    }
    if (next === 'render' && slug) {
      await fetchAllPlaceholders()
      trackEvent({
        event: ANALYTICS_EVENTS.PROMPT_PREVIEW_VIEWED,
        properties: { ...basePayload, preview_type: 'render' },
      })
    }
  }

  const saveLabel = saving
    ? 'Saving…'
    : formData.status === 'published'
      ? 'Publish'
      : 'Save as draft'

  if (loading) {
    return (
      <div className="space-y-6">
        <PageHeader title={pageTitle} description="Loading prompt…" />
        <Skeleton className="h-64 w-full" />
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title={pageTitle}
        description={
          isEditing
            ? `Editing: ${prompt?.name ?? ''}`
            : 'Create a new AI prompt with markdown support.'
        }
        actions={
          <div className="flex flex-wrap items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                void navigate('/prompts')
              }}
            >
              <ArrowLeft className="mr-2 size-4" />
              Back
            </Button>
            <Button
              size="sm"
              data-testid="prompt-save-button"
              onClick={() => {
                void handleSave()
              }}
              disabled={saving}
            >
              <Save className="mr-2 size-4" />
              {saveLabel}
            </Button>
          </div>
        }
      />

      <div className="flex flex-col gap-6 lg:flex-row">
        <EditorPane
          formData={formData}
          errors={errors}
          view={view}
          onViewChange={v => {
            void handleViewChange(v)
          }}
          onNameChange={name => {
            void handleNameChange(name)
          }}
          onBodyChange={body => {
            setFormData(prev => ({ ...prev, body }))
          }}
          isEditing={isEditing}
          isLoadingPlaceholders={isLoadingPlaceholders}
          excludeCurrentPrompt={prompt?.slug}
          onLoadTemplateClick={() => {
            setShowTemplateLoader(true)
          }}
          allPlaceholders={allPlaceholders}
          placeholderValues={placeholderValues}
          onPlaceholderChange={setPlaceholderValue}
          renderedBody={renderedBody}
          renderError={renderError}
          isRendering={isRendering}
        />

        <div className="lg:w-[30%]">
          <EditorSettings
            formData={formData}
            errors={errors}
            projects={projects}
            loadingProjects={loadingProjects}
            isCheckingSlug={isCheckingSlug}
            slugAutoGenerated={slugAutoGenerated}
            onSlugChange={handleSlugChange}
            onFormDataChange={setFormData}
          />
        </div>
      </div>

      <PromptTemplateLoader
        isOpen={showTemplateLoader}
        onClose={() => {
          setShowTemplateLoader(false)
        }}
        onSelectPrompt={handleLoadTemplate}
        excludeCurrentPrompt={prompt?.slug}
      />
    </div>
  )
}
