// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	events "github.com/vibexp/vibexp/pkg/events"
)

// MockConcurrencyManagedListener is an autogenerated mock type for the ConcurrencyManagedListener type
type MockConcurrencyManagedListener struct {
	mock.Mock
}

type MockConcurrencyManagedListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConcurrencyManagedListener) EXPECT() *MockConcurrencyManagedListener_Expecter {
	return &MockConcurrencyManagedListener_Expecter{mock: &_m.Mock}
}

// EventTypes provides a mock function with no fields
func (_m *MockConcurrencyManagedListener) EventTypes() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventTypes")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockConcurrencyManagedListener_EventTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventTypes'
type MockConcurrencyManagedListener_EventTypes_Call struct {
	*mock.Call
}

// EventTypes is a helper method to define mock.On call
func (_e *MockConcurrencyManagedListener_Expecter) EventTypes() *MockConcurrencyManagedListener_EventTypes_Call {
	return &MockConcurrencyManagedListener_EventTypes_Call{Call: _e.mock.On("EventTypes")}
}

func (_c *MockConcurrencyManagedListener_EventTypes_Call) Run(run func()) *MockConcurrencyManagedListener_EventTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConcurrencyManagedListener_EventTypes_Call) Return(_a0 []string) *MockConcurrencyManagedListener_EventTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConcurrencyManagedListener_EventTypes_Call) RunAndReturn(run func() []string) *MockConcurrencyManagedListener_EventTypes_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function with given fields: ctx, event
func (_m *MockConcurrencyManagedListener) Handle(ctx context.Context, event events.Event) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, events.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConcurrencyManagedListener_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockConcurrencyManagedListener_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - event events.Event
func (_e *MockConcurrencyManagedListener_Expecter) Handle(ctx interface{}, event interface{}) *MockConcurrencyManagedListener_Handle_Call {
	return &MockConcurrencyManagedListener_Handle_Call{Call: _e.mock.On("Handle", ctx, event)}
}

func (_c *MockConcurrencyManagedListener_Handle_Call) Run(run func(ctx context.Context, event events.Event)) *MockConcurrencyManagedListener_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(events.Event))
	})
	return _c
}

func (_c *MockConcurrencyManagedListener_Handle_Call) Return(_a0 error) *MockConcurrencyManagedListener_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConcurrencyManagedListener_Handle_Call) RunAndReturn(run func(context.Context, events.Event) error) *MockConcurrencyManagedListener_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// ManagesOwnConcurrency provides a mock function with no fields
func (_m *MockConcurrencyManagedListener) ManagesOwnConcurrency() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ManagesOwnConcurrency")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockConcurrencyManagedListener_ManagesOwnConcurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManagesOwnConcurrency'
type MockConcurrencyManagedListener_ManagesOwnConcurrency_Call struct {
	*mock.Call
}

// ManagesOwnConcurrency is a helper method to define mock.On call
func (_e *MockConcurrencyManagedListener_Expecter) ManagesOwnConcurrency() *MockConcurrencyManagedListener_ManagesOwnConcurrency_Call {
	return &MockConcurrencyManagedListener_ManagesOwnConcurrency_Call{Call: _e.mock.On("ManagesOwnConcurrency")}
}

func (_c *MockConcurrencyManagedListener_ManagesOwnConcurrency_Call) Run(run func()) *MockConcurrencyManagedListener_ManagesOwnConcurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConcurrencyManagedListener_ManagesOwnConcurrency_Call) Return(_a0 bool) *MockConcurrencyManagedListener_ManagesOwnConcurrency_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConcurrencyManagedListener_ManagesOwnConcurrency_Call) RunAndReturn(run func() bool) *MockConcurrencyManagedListener_ManagesOwnConcurrency_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConcurrencyManagedListener creates a new instance of MockConcurrencyManagedListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConcurrencyManagedListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConcurrencyManagedListener {
	mock := &MockConcurrencyManagedListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
