// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	events "github.com/vibexp/vibexp/pkg/events"
)

// MockEventBus is an autogenerated mock type for the EventBus type
type MockEventBus struct {
	mock.Mock
}

type MockEventBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventBus) EXPECT() *MockEventBus_Expecter {
	return &MockEventBus_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, event
func (_m *MockEventBus) Publish(ctx context.Context, event events.Event) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, events.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventBus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventBus_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - event events.Event
func (_e *MockEventBus_Expecter) Publish(ctx interface{}, event interface{}) *MockEventBus_Publish_Call {
	return &MockEventBus_Publish_Call{Call: _e.mock.On("Publish", ctx, event)}
}

func (_c *MockEventBus_Publish_Call) Run(run func(ctx context.Context, event events.Event)) *MockEventBus_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(events.Event))
	})
	return _c
}

func (_c *MockEventBus_Publish_Call) Return(_a0 error) *MockEventBus_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_Publish_Call) RunAndReturn(run func(context.Context, events.Event) error) *MockEventBus_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with no fields
func (_m *MockEventBus) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventBus_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockEventBus_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockEventBus_Expecter) Start() *MockEventBus_Start_Call {
	return &MockEventBus_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockEventBus_Start_Call) Run(run func()) *MockEventBus_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventBus_Start_Call) Return(_a0 error) *MockEventBus_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_Start_Call) RunAndReturn(run func() error) *MockEventBus_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockEventBus) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventBus_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockEventBus_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockEventBus_Expecter) Stop() *MockEventBus_Stop_Call {
	return &MockEventBus_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockEventBus_Stop_Call) Run(run func()) *MockEventBus_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventBus_Stop_Call) Return(_a0 error) *MockEventBus_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_Stop_Call) RunAndReturn(run func() error) *MockEventBus_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: listener
func (_m *MockEventBus) Subscribe(listener events.EventListener) error {
	ret := _m.Called(listener)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(events.EventListener) error); ok {
		r0 = rf(listener)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventBus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventBus_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - listener events.EventListener
func (_e *MockEventBus_Expecter) Subscribe(listener interface{}) *MockEventBus_Subscribe_Call {
	return &MockEventBus_Subscribe_Call{Call: _e.mock.On("Subscribe", listener)}
}

func (_c *MockEventBus_Subscribe_Call) Run(run func(listener events.EventListener)) *MockEventBus_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(events.EventListener))
	})
	return _c
}

func (_c *MockEventBus_Subscribe_Call) Return(_a0 error) *MockEventBus_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_Subscribe_Call) RunAndReturn(run func(events.EventListener) error) *MockEventBus_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with given fields: listener
func (_m *MockEventBus) Unsubscribe(listener events.EventListener) error {
	ret := _m.Called(listener)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(events.EventListener) error); ok {
		r0 = rf(listener)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventBus_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockEventBus_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - listener events.EventListener
func (_e *MockEventBus_Expecter) Unsubscribe(listener interface{}) *MockEventBus_Unsubscribe_Call {
	return &MockEventBus_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", listener)}
}

func (_c *MockEventBus_Unsubscribe_Call) Run(run func(listener events.EventListener)) *MockEventBus_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(events.EventListener))
	})
	return _c
}

func (_c *MockEventBus_Unsubscribe_Call) Return(_a0 error) *MockEventBus_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_Unsubscribe_Call) RunAndReturn(run func(events.EventListener) error) *MockEventBus_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventBus creates a new instance of MockEventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventBus {
	mock := &MockEventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
