// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	events "github.com/vibexp/vibexp/pkg/events"
)

// MockEmbeddingProcessor is an autogenerated mock type for the EmbeddingProcessor type
type MockEmbeddingProcessor struct {
	mock.Mock
}

type MockEmbeddingProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingProcessor) EXPECT() *MockEmbeddingProcessor_Expecter {
	return &MockEmbeddingProcessor_Expecter{mock: &_m.Mock}
}

// ProcessEvent provides a mock function with given fields: ctx, event
func (_m *MockEmbeddingProcessor) ProcessEvent(ctx context.Context, event events.Event) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProcessEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, events.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmbeddingProcessor_ProcessEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessEvent'
type MockEmbeddingProcessor_ProcessEvent_Call struct {
	*mock.Call
}

// ProcessEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event events.Event
func (_e *MockEmbeddingProcessor_Expecter) ProcessEvent(ctx interface{}, event interface{}) *MockEmbeddingProcessor_ProcessEvent_Call {
	return &MockEmbeddingProcessor_ProcessEvent_Call{Call: _e.mock.On("ProcessEvent", ctx, event)}
}

func (_c *MockEmbeddingProcessor_ProcessEvent_Call) Run(run func(ctx context.Context, event events.Event)) *MockEmbeddingProcessor_ProcessEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(events.Event))
	})
	return _c
}

func (_c *MockEmbeddingProcessor_ProcessEvent_Call) Return(_a0 error) *MockEmbeddingProcessor_ProcessEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingProcessor_ProcessEvent_Call) RunAndReturn(run func(context.Context, events.Event) error) *MockEmbeddingProcessor_ProcessEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingProcessor creates a new instance of MockEmbeddingProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingProcessor {
	mock := &MockEmbeddingProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
