// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockInstanceSearchSettingsRepository is an autogenerated mock type for the InstanceSearchSettingsRepository type
type MockInstanceSearchSettingsRepository struct {
	mock.Mock
}

type MockInstanceSearchSettingsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstanceSearchSettingsRepository) EXPECT() *MockInstanceSearchSettingsRepository_Expecter {
	return &MockInstanceSearchSettingsRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx
func (_m *MockInstanceSearchSettingsRepository) Delete(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceSearchSettingsRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInstanceSearchSettingsRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstanceSearchSettingsRepository_Expecter) Delete(ctx interface{}) *MockInstanceSearchSettingsRepository_Delete_Call {
	return &MockInstanceSearchSettingsRepository_Delete_Call{Call: _e.mock.On("Delete", ctx)}
}

func (_c *MockInstanceSearchSettingsRepository_Delete_Call) Run(run func(ctx context.Context)) *MockInstanceSearchSettingsRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInstanceSearchSettingsRepository_Delete_Call) Return(_a0 error) *MockInstanceSearchSettingsRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceSearchSettingsRepository_Delete_Call) RunAndReturn(run func(context.Context) error) *MockInstanceSearchSettingsRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx
func (_m *MockInstanceSearchSettingsRepository) Get(ctx context.Context) (*models.InstanceSearchSettings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.InstanceSearchSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.InstanceSearchSettings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.InstanceSearchSettings); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InstanceSearchSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceSearchSettingsRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInstanceSearchSettingsRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstanceSearchSettingsRepository_Expecter) Get(ctx interface{}) *MockInstanceSearchSettingsRepository_Get_Call {
	return &MockInstanceSearchSettingsRepository_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockInstanceSearchSettingsRepository_Get_Call) Run(run func(ctx context.Context)) *MockInstanceSearchSettingsRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInstanceSearchSettingsRepository_Get_Call) Return(_a0 *models.InstanceSearchSettings, _a1 error) *MockInstanceSearchSettingsRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInstanceSearchSettingsRepository_Get_Call) RunAndReturn(run func(context.Context) (*models.InstanceSearchSettings, error)) *MockInstanceSearchSettingsRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InsertIfAbsent provides a mock function with given fields: ctx, settings
func (_m *MockInstanceSearchSettingsRepository) InsertIfAbsent(ctx context.Context, settings *models.InstanceSearchSettings) (bool, error) {
	ret := _m.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for InsertIfAbsent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.InstanceSearchSettings) (bool, error)); ok {
		return rf(ctx, settings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.InstanceSearchSettings) bool); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.InstanceSearchSettings) error); ok {
		r1 = rf(ctx, settings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceSearchSettingsRepository_InsertIfAbsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertIfAbsent'
type MockInstanceSearchSettingsRepository_InsertIfAbsent_Call struct {
	*mock.Call
}

// InsertIfAbsent is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.InstanceSearchSettings
func (_e *MockInstanceSearchSettingsRepository_Expecter) InsertIfAbsent(ctx interface{}, settings interface{}) *MockInstanceSearchSettingsRepository_InsertIfAbsent_Call {
	return &MockInstanceSearchSettingsRepository_InsertIfAbsent_Call{Call: _e.mock.On("InsertIfAbsent", ctx, settings)}
}

func (_c *MockInstanceSearchSettingsRepository_InsertIfAbsent_Call) Run(run func(ctx context.Context, settings *models.InstanceSearchSettings)) *MockInstanceSearchSettingsRepository_InsertIfAbsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.InstanceSearchSettings))
	})
	return _c
}

func (_c *MockInstanceSearchSettingsRepository_InsertIfAbsent_Call) Return(inserted bool, err error) *MockInstanceSearchSettingsRepository_InsertIfAbsent_Call {
	_c.Call.Return(inserted, err)
	return _c
}

func (_c *MockInstanceSearchSettingsRepository_InsertIfAbsent_Call) RunAndReturn(run func(context.Context, *models.InstanceSearchSettings) (bool, error)) *MockInstanceSearchSettingsRepository_InsertIfAbsent_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, settings
func (_m *MockInstanceSearchSettingsRepository) Upsert(ctx context.Context, settings *models.InstanceSearchSettings) error {
	ret := _m.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.InstanceSearchSettings) error); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceSearchSettingsRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockInstanceSearchSettingsRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.InstanceSearchSettings
func (_e *MockInstanceSearchSettingsRepository_Expecter) Upsert(ctx interface{}, settings interface{}) *MockInstanceSearchSettingsRepository_Upsert_Call {
	return &MockInstanceSearchSettingsRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, settings)}
}

func (_c *MockInstanceSearchSettingsRepository_Upsert_Call) Run(run func(ctx context.Context, settings *models.InstanceSearchSettings)) *MockInstanceSearchSettingsRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.InstanceSearchSettings))
	})
	return _c
}

func (_c *MockInstanceSearchSettingsRepository_Upsert_Call) Return(_a0 error) *MockInstanceSearchSettingsRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceSearchSettingsRepository_Upsert_Call) RunAndReturn(run func(context.Context, *models.InstanceSearchSettings) error) *MockInstanceSearchSettingsRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstanceSearchSettingsRepository creates a new instance of MockInstanceSearchSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstanceSearchSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstanceSearchSettingsRepository {
	mock := &MockInstanceSearchSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
