// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"

	time "time"
)

// MockAPIKeyRepository is an autogenerated mock type for the APIKeyRepository type
type MockAPIKeyRepository struct {
	mock.Mock
}

type MockAPIKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepository_Expecter {
	return &MockAPIKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, apiKey
func (_m *MockAPIKeyRepository) Create(ctx context.Context, apiKey *models.APIKey) error {
	ret := _m.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.APIKey) error); ok {
		r0 = rf(ctx, apiKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPIKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAPIKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey *models.APIKey
func (_e *MockAPIKeyRepository_Expecter) Create(ctx interface{}, apiKey interface{}) *MockAPIKeyRepository_Create_Call {
	return &MockAPIKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, apiKey)}
}

func (_c *MockAPIKeyRepository_Create_Call) Run(run func(ctx context.Context, apiKey *models.APIKey)) *MockAPIKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.APIKey))
	})
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) Return(_a0 error) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) RunAndReturn(run func(context.Context, *models.APIKey) error) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, keyID
func (_m *MockAPIKeyRepository) Delete(ctx context.Context, userID string, keyID string) error {
	ret := _m.Called(ctx, userID, keyID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, keyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPIKeyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAPIKeyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - keyID string
func (_e *MockAPIKeyRepository_Expecter) Delete(ctx interface{}, userID interface{}, keyID interface{}) *MockAPIKeyRepository_Delete_Call {
	return &MockAPIKeyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, keyID)}
}

func (_c *MockAPIKeyRepository_Delete_Call) Run(run func(ctx context.Context, userID string, keyID string)) *MockAPIKeyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_Delete_Call) Return(_a0 error) *MockAPIKeyRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIKeyRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAPIKeyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKeyHash provides a mock function with given fields: ctx, keyHash
func (_m *MockAPIKeyRepository) GetByKeyHash(ctx context.Context, keyHash string) (*models.APIKey, error) {
	ret := _m.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByKeyHash")
	}

	var r0 *models.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.APIKey, error)); ok {
		return rf(ctx, keyHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.APIKey); ok {
		r0 = rf(ctx, keyHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_GetByKeyHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKeyHash'
type MockAPIKeyRepository_GetByKeyHash_Call struct {
	*mock.Call
}

// GetByKeyHash is a helper method to define mock.On call
//   - ctx context.Context
//   - keyHash string
func (_e *MockAPIKeyRepository_Expecter) GetByKeyHash(ctx interface{}, keyHash interface{}) *MockAPIKeyRepository_GetByKeyHash_Call {
	return &MockAPIKeyRepository_GetByKeyHash_Call{Call: _e.mock.On("GetByKeyHash", ctx, keyHash)}
}

func (_c *MockAPIKeyRepository_GetByKeyHash_Call) Run(run func(ctx context.Context, keyHash string)) *MockAPIKeyRepository_GetByKeyHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetByKeyHash_Call) Return(_a0 *models.APIKey, _a1 error) *MockAPIKeyRepository_GetByKeyHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_GetByKeyHash_Call) RunAndReturn(run func(context.Context, string) (*models.APIKey, error)) *MockAPIKeyRepository_GetByKeyHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAPIKeyRepository) GetByUserID(ctx context.Context, userID string) ([]models.APIKey, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []models.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.APIKey, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.APIKey); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockAPIKeyRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAPIKeyRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockAPIKeyRepository_GetByUserID_Call {
	return &MockAPIKeyRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockAPIKeyRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAPIKeyRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetByUserID_Call) Return(_a0 []models.APIKey, _a1 error) *MockAPIKeyRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) ([]models.APIKey, error)) *MockAPIKeyRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetIntegrationsByAPIKeyID provides a mock function with given fields: ctx, apiKeyID
func (_m *MockAPIKeyRepository) GetIntegrationsByAPIKeyID(ctx context.Context, apiKeyID string) ([]string, error) {
	ret := _m.Called(ctx, apiKeyID)

	if len(ret) == 0 {
		panic("no return value specified for GetIntegrationsByAPIKeyID")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, apiKeyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, apiKeyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, apiKeyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_GetIntegrationsByAPIKeyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntegrationsByAPIKeyID'
type MockAPIKeyRepository_GetIntegrationsByAPIKeyID_Call struct {
	*mock.Call
}

// GetIntegrationsByAPIKeyID is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKeyID string
func (_e *MockAPIKeyRepository_Expecter) GetIntegrationsByAPIKeyID(ctx interface{}, apiKeyID interface{}) *MockAPIKeyRepository_GetIntegrationsByAPIKeyID_Call {
	return &MockAPIKeyRepository_GetIntegrationsByAPIKeyID_Call{Call: _e.mock.On("GetIntegrationsByAPIKeyID", ctx, apiKeyID)}
}

func (_c *MockAPIKeyRepository_GetIntegrationsByAPIKeyID_Call) Run(run func(ctx context.Context, apiKeyID string)) *MockAPIKeyRepository_GetIntegrationsByAPIKeyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetIntegrationsByAPIKeyID_Call) Return(_a0 []string, _a1 error) *MockAPIKeyRepository_GetIntegrationsByAPIKeyID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_GetIntegrationsByAPIKeyID_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockAPIKeyRepository_GetIntegrationsByAPIKeyID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamesByIDs provides a mock function with given fields: ctx, userID, ids
func (_m *MockAPIKeyRepository) GetNamesByIDs(ctx context.Context, userID string, ids []string) (map[string]string, error) {
	ret := _m.Called(ctx, userID, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetNamesByIDs")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (map[string]string, error)); ok {
		return rf(ctx, userID, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) map[string]string); ok {
		r0 = rf(ctx, userID, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, userID, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_GetNamesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamesByIDs'
type MockAPIKeyRepository_GetNamesByIDs_Call struct {
	*mock.Call
}

// GetNamesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ids []string
func (_e *MockAPIKeyRepository_Expecter) GetNamesByIDs(ctx interface{}, userID interface{}, ids interface{}) *MockAPIKeyRepository_GetNamesByIDs_Call {
	return &MockAPIKeyRepository_GetNamesByIDs_Call{Call: _e.mock.On("GetNamesByIDs", ctx, userID, ids)}
}

func (_c *MockAPIKeyRepository_GetNamesByIDs_Call) Run(run func(ctx context.Context, userID string, ids []string)) *MockAPIKeyRepository_GetNamesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetNamesByIDs_Call) Return(_a0 map[string]string, _a1 error) *MockAPIKeyRepository_GetNamesByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_GetNamesByIDs_Call) RunAndReturn(run func(context.Context, string, []string) (map[string]string, error)) *MockAPIKeyRepository_GetNamesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetValidIntegrationCodes provides a mock function with given fields: ctx
func (_m *MockAPIKeyRepository) GetValidIntegrationCodes(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetValidIntegrationCodes")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_GetValidIntegrationCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValidIntegrationCodes'
type MockAPIKeyRepository_GetValidIntegrationCodes_Call struct {
	*mock.Call
}

// GetValidIntegrationCodes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAPIKeyRepository_Expecter) GetValidIntegrationCodes(ctx interface{}) *MockAPIKeyRepository_GetValidIntegrationCodes_Call {
	return &MockAPIKeyRepository_GetValidIntegrationCodes_Call{Call: _e.mock.On("GetValidIntegrationCodes", ctx)}
}

func (_c *MockAPIKeyRepository_GetValidIntegrationCodes_Call) Run(run func(ctx context.Context)) *MockAPIKeyRepository_GetValidIntegrationCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetValidIntegrationCodes_Call) Return(_a0 []string, _a1 error) *MockAPIKeyRepository_GetValidIntegrationCodes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_GetValidIntegrationCodes_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockAPIKeyRepository_GetValidIntegrationCodes_Call {
	_c.Call.Return(run)
	return _c
}

// HasIntegrationPermission provides a mock function with given fields: ctx, apiKeyID, integrationCode
func (_m *MockAPIKeyRepository) HasIntegrationPermission(ctx context.Context, apiKeyID string, integrationCode string) (bool, error) {
	ret := _m.Called(ctx, apiKeyID, integrationCode)

	if len(ret) == 0 {
		panic("no return value specified for HasIntegrationPermission")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, apiKeyID, integrationCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, apiKeyID, integrationCode)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, apiKeyID, integrationCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_HasIntegrationPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasIntegrationPermission'
type MockAPIKeyRepository_HasIntegrationPermission_Call struct {
	*mock.Call
}

// HasIntegrationPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKeyID string
//   - integrationCode string
func (_e *MockAPIKeyRepository_Expecter) HasIntegrationPermission(ctx interface{}, apiKeyID interface{}, integrationCode interface{}) *MockAPIKeyRepository_HasIntegrationPermission_Call {
	return &MockAPIKeyRepository_HasIntegrationPermission_Call{Call: _e.mock.On("HasIntegrationPermission", ctx, apiKeyID, integrationCode)}
}

func (_c *MockAPIKeyRepository_HasIntegrationPermission_Call) Run(run func(ctx context.Context, apiKeyID string, integrationCode string)) *MockAPIKeyRepository_HasIntegrationPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_HasIntegrationPermission_Call) Return(_a0 bool, _a1 error) *MockAPIKeyRepository_HasIntegrationPermission_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_HasIntegrationPermission_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockAPIKeyRepository_HasIntegrationPermission_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastUsed provides a mock function with given fields: ctx, keyID, lastUsedAt
func (_m *MockAPIKeyRepository) UpdateLastUsed(ctx context.Context, keyID string, lastUsedAt time.Time) error {
	ret := _m.Called(ctx, keyID, lastUsedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, keyID, lastUsedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPIKeyRepository_UpdateLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastUsed'
type MockAPIKeyRepository_UpdateLastUsed_Call struct {
	*mock.Call
}

// UpdateLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - lastUsedAt time.Time
func (_e *MockAPIKeyRepository_Expecter) UpdateLastUsed(ctx interface{}, keyID interface{}, lastUsedAt interface{}) *MockAPIKeyRepository_UpdateLastUsed_Call {
	return &MockAPIKeyRepository_UpdateLastUsed_Call{Call: _e.mock.On("UpdateLastUsed", ctx, keyID, lastUsedAt)}
}

func (_c *MockAPIKeyRepository_UpdateLastUsed_Call) Run(run func(ctx context.Context, keyID string, lastUsedAt time.Time)) *MockAPIKeyRepository_UpdateLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockAPIKeyRepository_UpdateLastUsed_Call) Return(_a0 error) *MockAPIKeyRepository_UpdateLastUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIKeyRepository_UpdateLastUsed_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockAPIKeyRepository_UpdateLastUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIKeyRepository creates a new instance of MockAPIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
