// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/vibexp/vibexp/internal/models"
	mock "github.com/stretchr/testify/mock"

	repositories "github.com/vibexp/vibexp/internal/repositories"
)

// MockFeedRepository is an autogenerated mock type for the FeedRepository type
type MockFeedRepository struct {
	mock.Mock
}

type MockFeedRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeedRepository) EXPECT() *MockFeedRepository_Expecter {
	return &MockFeedRepository_Expecter{mock: &_m.Mock}
}

// CountAll provides a mock function with given fields: ctx, userID
func (_m *MockFeedRepository) CountAll(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountAll")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFeedRepository_CountAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAll'
type MockFeedRepository_CountAll_Call struct {
	*mock.Call
}

// CountAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockFeedRepository_Expecter) CountAll(ctx interface{}, userID interface{}) *MockFeedRepository_CountAll_Call {
	return &MockFeedRepository_CountAll_Call{Call: _e.mock.On("CountAll", ctx, userID)}
}

func (_c *MockFeedRepository_CountAll_Call) Run(run func(ctx context.Context, userID string)) *MockFeedRepository_CountAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFeedRepository_CountAll_Call) Return(_a0 int, _a1 error) *MockFeedRepository_CountAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFeedRepository_CountAll_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockFeedRepository_CountAll_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, feed
func (_m *MockFeedRepository) Create(ctx context.Context, feed *models.Feed) error {
	ret := _m.Called(ctx, feed)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Feed) error); ok {
		r0 = rf(ctx, feed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeedRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFeedRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - feed *models.Feed
func (_e *MockFeedRepository_Expecter) Create(ctx interface{}, feed interface{}) *MockFeedRepository_Create_Call {
	return &MockFeedRepository_Create_Call{Call: _e.mock.On("Create", ctx, feed)}
}

func (_c *MockFeedRepository_Create_Call) Run(run func(ctx context.Context, feed *models.Feed)) *MockFeedRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Feed))
	})
	return _c
}

func (_c *MockFeedRepository_Create_Call) Return(_a0 error) *MockFeedRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeedRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Feed) error) *MockFeedRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, teamID, feedID
func (_m *MockFeedRepository) Delete(ctx context.Context, userID string, teamID string, feedID string) error {
	ret := _m.Called(ctx, userID, teamID, feedID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, teamID, feedID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeedRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFeedRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - feedID string
func (_e *MockFeedRepository_Expecter) Delete(ctx interface{}, userID interface{}, teamID interface{}, feedID interface{}) *MockFeedRepository_Delete_Call {
	return &MockFeedRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, teamID, feedID)}
}

func (_c *MockFeedRepository_Delete_Call) Run(run func(ctx context.Context, userID string, teamID string, feedID string)) *MockFeedRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockFeedRepository_Delete_Call) Return(_a0 error) *MockFeedRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeedRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockFeedRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, teamID, feedID
func (_m *MockFeedRepository) GetByID(ctx context.Context, userID string, teamID string, feedID string) (*models.Feed, error) {
	ret := _m.Called(ctx, userID, teamID, feedID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Feed
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.Feed, error)); ok {
		return rf(ctx, userID, teamID, feedID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.Feed); ok {
		r0 = rf(ctx, userID, teamID, feedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Feed)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, teamID, feedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFeedRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockFeedRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - feedID string
func (_e *MockFeedRepository_Expecter) GetByID(ctx interface{}, userID interface{}, teamID interface{}, feedID interface{}) *MockFeedRepository_GetByID_Call {
	return &MockFeedRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, teamID, feedID)}
}

func (_c *MockFeedRepository_GetByID_Call) Run(run func(ctx context.Context, userID string, teamID string, feedID string)) *MockFeedRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockFeedRepository_GetByID_Call) Return(_a0 *models.Feed, _a1 error) *MockFeedRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFeedRepository_GetByID_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.Feed, error)) *MockFeedRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, filters
func (_m *MockFeedRepository) List(ctx context.Context, userID string, filters repositories.FeedFilters) ([]models.Feed, int, error) {
	ret := _m.Called(ctx, userID, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Feed
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, repositories.FeedFilters) ([]models.Feed, int, error)); ok {
		return rf(ctx, userID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, repositories.FeedFilters) []models.Feed); ok {
		r0 = rf(ctx, userID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Feed)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, repositories.FeedFilters) int); ok {
		r1 = rf(ctx, userID, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, repositories.FeedFilters) error); ok {
		r2 = rf(ctx, userID, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFeedRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFeedRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filters repositories.FeedFilters
func (_e *MockFeedRepository_Expecter) List(ctx interface{}, userID interface{}, filters interface{}) *MockFeedRepository_List_Call {
	return &MockFeedRepository_List_Call{Call: _e.mock.On("List", ctx, userID, filters)}
}

func (_c *MockFeedRepository_List_Call) Run(run func(ctx context.Context, userID string, filters repositories.FeedFilters)) *MockFeedRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(repositories.FeedFilters))
	})
	return _c
}

func (_c *MockFeedRepository_List_Call) Return(_a0 []models.Feed, _a1 int, _a2 error) *MockFeedRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockFeedRepository_List_Call) RunAndReturn(run func(context.Context, string, repositories.FeedFilters) ([]models.Feed, int, error)) *MockFeedRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithLastPost provides a mock function with given fields: ctx, userID, filters
func (_m *MockFeedRepository) ListWithLastPost(ctx context.Context, userID string, filters repositories.FeedFilters) ([]models.FeedWithLastPost, error) {
	ret := _m.Called(ctx, userID, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListWithLastPost")
	}

	var r0 []models.FeedWithLastPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, repositories.FeedFilters) ([]models.FeedWithLastPost, error)); ok {
		return rf(ctx, userID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, repositories.FeedFilters) []models.FeedWithLastPost); ok {
		r0 = rf(ctx, userID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FeedWithLastPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, repositories.FeedFilters) error); ok {
		r1 = rf(ctx, userID, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFeedRepository_ListWithLastPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithLastPost'
type MockFeedRepository_ListWithLastPost_Call struct {
	*mock.Call
}

// ListWithLastPost is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filters repositories.FeedFilters
func (_e *MockFeedRepository_Expecter) ListWithLastPost(ctx interface{}, userID interface{}, filters interface{}) *MockFeedRepository_ListWithLastPost_Call {
	return &MockFeedRepository_ListWithLastPost_Call{Call: _e.mock.On("ListWithLastPost", ctx, userID, filters)}
}

func (_c *MockFeedRepository_ListWithLastPost_Call) Run(run func(ctx context.Context, userID string, filters repositories.FeedFilters)) *MockFeedRepository_ListWithLastPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(repositories.FeedFilters))
	})
	return _c
}

func (_c *MockFeedRepository_ListWithLastPost_Call) Return(_a0 []models.FeedWithLastPost, _a1 error) *MockFeedRepository_ListWithLastPost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFeedRepository_ListWithLastPost_Call) RunAndReturn(run func(context.Context, string, repositories.FeedFilters) ([]models.FeedWithLastPost, error)) *MockFeedRepository_ListWithLastPost_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, feed
func (_m *MockFeedRepository) Update(ctx context.Context, feed *models.Feed) error {
	ret := _m.Called(ctx, feed)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Feed) error); ok {
		r0 = rf(ctx, feed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeedRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFeedRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - feed *models.Feed
func (_e *MockFeedRepository_Expecter) Update(ctx interface{}, feed interface{}) *MockFeedRepository_Update_Call {
	return &MockFeedRepository_Update_Call{Call: _e.mock.On("Update", ctx, feed)}
}

func (_c *MockFeedRepository_Update_Call) Run(run func(ctx context.Context, feed *models.Feed)) *MockFeedRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Feed))
	})
	return _c
}

func (_c *MockFeedRepository_Update_Call) Return(_a0 error) *MockFeedRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeedRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Feed) error) *MockFeedRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFeedRepository creates a new instance of MockFeedRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedRepository {
	mock := &MockFeedRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
