// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"

	repositories "github.com/vibexp/vibexp/internal/repositories"

	time "time"
)

// MockAdminRepository is an autogenerated mock type for the AdminRepository type
type MockAdminRepository struct {
	mock.Mock
}

type MockAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminRepository) EXPECT() *MockAdminRepository_Expecter {
	return &MockAdminRepository_Expecter{mock: &_m.Mock}
}

// DeleteUserIfUnblocked provides a mock function with given fields: ctx, id
func (_m *MockAdminRepository) DeleteUserIfUnblocked(ctx context.Context, id string) ([]models.AdminDeleteBlocker, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserIfUnblocked")
	}

	var r0 []models.AdminDeleteBlocker
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.AdminDeleteBlocker, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.AdminDeleteBlocker); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminDeleteBlocker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAdminRepository_DeleteUserIfUnblocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserIfUnblocked'
type MockAdminRepository_DeleteUserIfUnblocked_Call struct {
	*mock.Call
}

// DeleteUserIfUnblocked is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAdminRepository_Expecter) DeleteUserIfUnblocked(ctx interface{}, id interface{}) *MockAdminRepository_DeleteUserIfUnblocked_Call {
	return &MockAdminRepository_DeleteUserIfUnblocked_Call{Call: _e.mock.On("DeleteUserIfUnblocked", ctx, id)}
}

func (_c *MockAdminRepository_DeleteUserIfUnblocked_Call) Run(run func(ctx context.Context, id string)) *MockAdminRepository_DeleteUserIfUnblocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdminRepository_DeleteUserIfUnblocked_Call) Return(_a0 []models.AdminDeleteBlocker, _a1 bool, _a2 error) *MockAdminRepository_DeleteUserIfUnblocked_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAdminRepository_DeleteUserIfUnblocked_Call) RunAndReturn(run func(context.Context, string) ([]models.AdminDeleteBlocker, bool, error)) *MockAdminRepository_DeleteUserIfUnblocked_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessBySourceSeries provides a mock function with given fields: ctx, from, to, granularity
func (_m *MockAdminRepository) GetAccessBySourceSeries(ctx context.Context, from time.Time, to time.Time, granularity string) ([]models.AdminSourcePoint, error) {
	ret := _m.Called(ctx, from, to, granularity)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessBySourceSeries")
	}

	var r0 []models.AdminSourcePoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string) ([]models.AdminSourcePoint, error)); ok {
		return rf(ctx, from, to, granularity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string) []models.AdminSourcePoint); ok {
		r0 = rf(ctx, from, to, granularity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminSourcePoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, string) error); ok {
		r1 = rf(ctx, from, to, granularity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetAccessBySourceSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessBySourceSeries'
type MockAdminRepository_GetAccessBySourceSeries_Call struct {
	*mock.Call
}

// GetAccessBySourceSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - granularity string
func (_e *MockAdminRepository_Expecter) GetAccessBySourceSeries(ctx interface{}, from interface{}, to interface{}, granularity interface{}) *MockAdminRepository_GetAccessBySourceSeries_Call {
	return &MockAdminRepository_GetAccessBySourceSeries_Call{Call: _e.mock.On("GetAccessBySourceSeries", ctx, from, to, granularity)}
}

func (_c *MockAdminRepository_GetAccessBySourceSeries_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, granularity string)) *MockAdminRepository_GetAccessBySourceSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(string))
	})
	return _c
}

func (_c *MockAdminRepository_GetAccessBySourceSeries_Call) Return(_a0 []models.AdminSourcePoint, _a1 error) *MockAdminRepository_GetAccessBySourceSeries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetAccessBySourceSeries_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, string) ([]models.AdminSourcePoint, error)) *MockAdminRepository_GetAccessBySourceSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityBreakdowns provides a mock function with given fields: ctx
func (_m *MockAdminRepository) GetEntityBreakdowns(ctx context.Context) ([]models.AdminEntityBreakdown, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityBreakdowns")
	}

	var r0 []models.AdminEntityBreakdown
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.AdminEntityBreakdown, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.AdminEntityBreakdown); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminEntityBreakdown)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetEntityBreakdowns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityBreakdowns'
type MockAdminRepository_GetEntityBreakdowns_Call struct {
	*mock.Call
}

// GetEntityBreakdowns is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminRepository_Expecter) GetEntityBreakdowns(ctx interface{}) *MockAdminRepository_GetEntityBreakdowns_Call {
	return &MockAdminRepository_GetEntityBreakdowns_Call{Call: _e.mock.On("GetEntityBreakdowns", ctx)}
}

func (_c *MockAdminRepository_GetEntityBreakdowns_Call) Run(run func(ctx context.Context)) *MockAdminRepository_GetEntityBreakdowns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminRepository_GetEntityBreakdowns_Call) Return(_a0 []models.AdminEntityBreakdown, _a1 error) *MockAdminRepository_GetEntityBreakdowns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetEntityBreakdowns_Call) RunAndReturn(run func(context.Context) ([]models.AdminEntityBreakdown, error)) *MockAdminRepository_GetEntityBreakdowns_Call {
	_c.Call.Return(run)
	return _c
}

// GetExtendedCounts provides a mock function with given fields: ctx
func (_m *MockAdminRepository) GetExtendedCounts(ctx context.Context) (models.AdminExtendedCounts, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExtendedCounts")
	}

	var r0 models.AdminExtendedCounts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (models.AdminExtendedCounts, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) models.AdminExtendedCounts); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.AdminExtendedCounts)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetExtendedCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExtendedCounts'
type MockAdminRepository_GetExtendedCounts_Call struct {
	*mock.Call
}

// GetExtendedCounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminRepository_Expecter) GetExtendedCounts(ctx interface{}) *MockAdminRepository_GetExtendedCounts_Call {
	return &MockAdminRepository_GetExtendedCounts_Call{Call: _e.mock.On("GetExtendedCounts", ctx)}
}

func (_c *MockAdminRepository_GetExtendedCounts_Call) Run(run func(ctx context.Context)) *MockAdminRepository_GetExtendedCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminRepository_GetExtendedCounts_Call) Return(_a0 models.AdminExtendedCounts, _a1 error) *MockAdminRepository_GetExtendedCounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetExtendedCounts_Call) RunAndReturn(run func(context.Context) (models.AdminExtendedCounts, error)) *MockAdminRepository_GetExtendedCounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetGrowthSeries provides a mock function with given fields: ctx, from, to, granularity
func (_m *MockAdminRepository) GetGrowthSeries(ctx context.Context, from time.Time, to time.Time, granularity string) ([]models.AdminGrowthCount, error) {
	ret := _m.Called(ctx, from, to, granularity)

	if len(ret) == 0 {
		panic("no return value specified for GetGrowthSeries")
	}

	var r0 []models.AdminGrowthCount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string) ([]models.AdminGrowthCount, error)); ok {
		return rf(ctx, from, to, granularity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string) []models.AdminGrowthCount); ok {
		r0 = rf(ctx, from, to, granularity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminGrowthCount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, string) error); ok {
		r1 = rf(ctx, from, to, granularity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetGrowthSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrowthSeries'
type MockAdminRepository_GetGrowthSeries_Call struct {
	*mock.Call
}

// GetGrowthSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - granularity string
func (_e *MockAdminRepository_Expecter) GetGrowthSeries(ctx interface{}, from interface{}, to interface{}, granularity interface{}) *MockAdminRepository_GetGrowthSeries_Call {
	return &MockAdminRepository_GetGrowthSeries_Call{Call: _e.mock.On("GetGrowthSeries", ctx, from, to, granularity)}
}

func (_c *MockAdminRepository_GetGrowthSeries_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, granularity string)) *MockAdminRepository_GetGrowthSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(string))
	})
	return _c
}

func (_c *MockAdminRepository_GetGrowthSeries_Call) Return(_a0 []models.AdminGrowthCount, _a1 error) *MockAdminRepository_GetGrowthSeries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetGrowthSeries_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, string) ([]models.AdminGrowthCount, error)) *MockAdminRepository_GetGrowthSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstanceCounts provides a mock function with given fields: ctx
func (_m *MockAdminRepository) GetInstanceCounts(ctx context.Context) (models.InstanceCounts, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetInstanceCounts")
	}

	var r0 models.InstanceCounts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (models.InstanceCounts, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) models.InstanceCounts); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.InstanceCounts)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetInstanceCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstanceCounts'
type MockAdminRepository_GetInstanceCounts_Call struct {
	*mock.Call
}

// GetInstanceCounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminRepository_Expecter) GetInstanceCounts(ctx interface{}) *MockAdminRepository_GetInstanceCounts_Call {
	return &MockAdminRepository_GetInstanceCounts_Call{Call: _e.mock.On("GetInstanceCounts", ctx)}
}

func (_c *MockAdminRepository_GetInstanceCounts_Call) Run(run func(ctx context.Context)) *MockAdminRepository_GetInstanceCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminRepository_GetInstanceCounts_Call) Return(_a0 models.InstanceCounts, _a1 error) *MockAdminRepository_GetInstanceCounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetInstanceCounts_Call) RunAndReturn(run func(context.Context) (models.InstanceCounts, error)) *MockAdminRepository_GetInstanceCounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetSignInSeries provides a mock function with given fields: ctx, from, to, granularity
func (_m *MockAdminRepository) GetSignInSeries(ctx context.Context, from time.Time, to time.Time, granularity string) ([]models.AdminCountPoint, error) {
	ret := _m.Called(ctx, from, to, granularity)

	if len(ret) == 0 {
		panic("no return value specified for GetSignInSeries")
	}

	var r0 []models.AdminCountPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string) ([]models.AdminCountPoint, error)); ok {
		return rf(ctx, from, to, granularity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string) []models.AdminCountPoint); ok {
		r0 = rf(ctx, from, to, granularity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminCountPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, string) error); ok {
		r1 = rf(ctx, from, to, granularity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetSignInSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSignInSeries'
type MockAdminRepository_GetSignInSeries_Call struct {
	*mock.Call
}

// GetSignInSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
//   - granularity string
func (_e *MockAdminRepository_Expecter) GetSignInSeries(ctx interface{}, from interface{}, to interface{}, granularity interface{}) *MockAdminRepository_GetSignInSeries_Call {
	return &MockAdminRepository_GetSignInSeries_Call{Call: _e.mock.On("GetSignInSeries", ctx, from, to, granularity)}
}

func (_c *MockAdminRepository_GetSignInSeries_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, granularity string)) *MockAdminRepository_GetSignInSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(string))
	})
	return _c
}

func (_c *MockAdminRepository_GetSignInSeries_Call) Return(_a0 []models.AdminCountPoint, _a1 error) *MockAdminRepository_GetSignInSeries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetSignInSeries_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, string) ([]models.AdminCountPoint, error)) *MockAdminRepository_GetSignInSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetSystemHealth provides a mock function with given fields: ctx
func (_m *MockAdminRepository) GetSystemHealth(ctx context.Context) (models.AdminSystemHealth, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemHealth")
	}

	var r0 models.AdminSystemHealth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (models.AdminSystemHealth, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) models.AdminSystemHealth); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.AdminSystemHealth)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetSystemHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemHealth'
type MockAdminRepository_GetSystemHealth_Call struct {
	*mock.Call
}

// GetSystemHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminRepository_Expecter) GetSystemHealth(ctx interface{}) *MockAdminRepository_GetSystemHealth_Call {
	return &MockAdminRepository_GetSystemHealth_Call{Call: _e.mock.On("GetSystemHealth", ctx)}
}

func (_c *MockAdminRepository_GetSystemHealth_Call) Run(run func(ctx context.Context)) *MockAdminRepository_GetSystemHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminRepository_GetSystemHealth_Call) Return(_a0 models.AdminSystemHealth, _a1 error) *MockAdminRepository_GetSystemHealth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetSystemHealth_Call) RunAndReturn(run func(context.Context) (models.AdminSystemHealth, error)) *MockAdminRepository_GetSystemHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamDetail provides a mock function with given fields: ctx, id
func (_m *MockAdminRepository) GetTeamDetail(ctx context.Context, id string) (*models.AdminTeamDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamDetail")
	}

	var r0 *models.AdminTeamDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.AdminTeamDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.AdminTeamDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AdminTeamDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetTeamDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamDetail'
type MockAdminRepository_GetTeamDetail_Call struct {
	*mock.Call
}

// GetTeamDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAdminRepository_Expecter) GetTeamDetail(ctx interface{}, id interface{}) *MockAdminRepository_GetTeamDetail_Call {
	return &MockAdminRepository_GetTeamDetail_Call{Call: _e.mock.On("GetTeamDetail", ctx, id)}
}

func (_c *MockAdminRepository_GetTeamDetail_Call) Run(run func(ctx context.Context, id string)) *MockAdminRepository_GetTeamDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdminRepository_GetTeamDetail_Call) Return(_a0 *models.AdminTeamDetail, _a1 error) *MockAdminRepository_GetTeamDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetTeamDetail_Call) RunAndReturn(run func(context.Context, string) (*models.AdminTeamDetail, error)) *MockAdminRepository_GetTeamDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserDetail provides a mock function with given fields: ctx, id
func (_m *MockAdminRepository) GetUserDetail(ctx context.Context, id string) (*models.AdminUserDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDetail")
	}

	var r0 *models.AdminUserDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.AdminUserDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.AdminUserDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AdminUserDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetUserDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserDetail'
type MockAdminRepository_GetUserDetail_Call struct {
	*mock.Call
}

// GetUserDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAdminRepository_Expecter) GetUserDetail(ctx interface{}, id interface{}) *MockAdminRepository_GetUserDetail_Call {
	return &MockAdminRepository_GetUserDetail_Call{Call: _e.mock.On("GetUserDetail", ctx, id)}
}

func (_c *MockAdminRepository_GetUserDetail_Call) Run(run func(ctx context.Context, id string)) *MockAdminRepository_GetUserDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdminRepository_GetUserDetail_Call) Return(_a0 *models.AdminUserDetail, _a1 error) *MockAdminRepository_GetUserDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetUserDetail_Call) RunAndReturn(run func(context.Context, string) (*models.AdminUserDetail, error)) *MockAdminRepository_GetUserDetail_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeams provides a mock function with given fields: ctx, filters
func (_m *MockAdminRepository) ListTeams(ctx context.Context, filters repositories.AdminTeamFilters) ([]models.AdminTeamListItem, int, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListTeams")
	}

	var r0 []models.AdminTeamListItem
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.AdminTeamFilters) ([]models.AdminTeamListItem, int, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repositories.AdminTeamFilters) []models.AdminTeamListItem); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminTeamListItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repositories.AdminTeamFilters) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repositories.AdminTeamFilters) error); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAdminRepository_ListTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeams'
type MockAdminRepository_ListTeams_Call struct {
	*mock.Call
}

// ListTeams is a helper method to define mock.On call
//   - ctx context.Context
//   - filters repositories.AdminTeamFilters
func (_e *MockAdminRepository_Expecter) ListTeams(ctx interface{}, filters interface{}) *MockAdminRepository_ListTeams_Call {
	return &MockAdminRepository_ListTeams_Call{Call: _e.mock.On("ListTeams", ctx, filters)}
}

func (_c *MockAdminRepository_ListTeams_Call) Run(run func(ctx context.Context, filters repositories.AdminTeamFilters)) *MockAdminRepository_ListTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.AdminTeamFilters))
	})
	return _c
}

func (_c *MockAdminRepository_ListTeams_Call) Return(_a0 []models.AdminTeamListItem, _a1 int, _a2 error) *MockAdminRepository_ListTeams_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAdminRepository_ListTeams_Call) RunAndReturn(run func(context.Context, repositories.AdminTeamFilters) ([]models.AdminTeamListItem, int, error)) *MockAdminRepository_ListTeams_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, filters
func (_m *MockAdminRepository) ListUsers(ctx context.Context, filters repositories.AdminUserFilters) ([]models.AdminUserListItem, int, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []models.AdminUserListItem
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.AdminUserFilters) ([]models.AdminUserListItem, int, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repositories.AdminUserFilters) []models.AdminUserListItem); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminUserListItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repositories.AdminUserFilters) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repositories.AdminUserFilters) error); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAdminRepository_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockAdminRepository_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - filters repositories.AdminUserFilters
func (_e *MockAdminRepository_Expecter) ListUsers(ctx interface{}, filters interface{}) *MockAdminRepository_ListUsers_Call {
	return &MockAdminRepository_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, filters)}
}

func (_c *MockAdminRepository_ListUsers_Call) Run(run func(ctx context.Context, filters repositories.AdminUserFilters)) *MockAdminRepository_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.AdminUserFilters))
	})
	return _c
}

func (_c *MockAdminRepository_ListUsers_Call) Return(_a0 []models.AdminUserListItem, _a1 int, _a2 error) *MockAdminRepository_ListUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAdminRepository_ListUsers_Call) RunAndReturn(run func(context.Context, repositories.AdminUserFilters) ([]models.AdminUserListItem, int, error)) *MockAdminRepository_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserName provides a mock function with given fields: ctx, id, name
func (_m *MockAdminRepository) UpdateUserName(ctx context.Context, id string, name string) (bool, error) {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, id, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, id, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_UpdateUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserName'
type MockAdminRepository_UpdateUserName_Call struct {
	*mock.Call
}

// UpdateUserName is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
func (_e *MockAdminRepository_Expecter) UpdateUserName(ctx interface{}, id interface{}, name interface{}) *MockAdminRepository_UpdateUserName_Call {
	return &MockAdminRepository_UpdateUserName_Call{Call: _e.mock.On("UpdateUserName", ctx, id, name)}
}

func (_c *MockAdminRepository_UpdateUserName_Call) Run(run func(ctx context.Context, id string, name string)) *MockAdminRepository_UpdateUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAdminRepository_UpdateUserName_Call) Return(_a0 bool, _a1 error) *MockAdminRepository_UpdateUserName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_UpdateUserName_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockAdminRepository_UpdateUserName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStatus provides a mock function with given fields: ctx, id, status
func (_m *MockAdminRepository) UpdateUserStatus(ctx context.Context, id string, status string) (bool, error) {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatus")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, id, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_UpdateUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStatus'
type MockAdminRepository_UpdateUserStatus_Call struct {
	*mock.Call
}

// UpdateUserStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status string
func (_e *MockAdminRepository_Expecter) UpdateUserStatus(ctx interface{}, id interface{}, status interface{}) *MockAdminRepository_UpdateUserStatus_Call {
	return &MockAdminRepository_UpdateUserStatus_Call{Call: _e.mock.On("UpdateUserStatus", ctx, id, status)}
}

func (_c *MockAdminRepository_UpdateUserStatus_Call) Run(run func(ctx context.Context, id string, status string)) *MockAdminRepository_UpdateUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAdminRepository_UpdateUserStatus_Call) Return(_a0 bool, _a1 error) *MockAdminRepository_UpdateUserStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_UpdateUserStatus_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockAdminRepository_UpdateUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminRepository creates a new instance of MockAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminRepository {
	mock := &MockAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
