// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockFreshnessRuleRepository is an autogenerated mock type for the FreshnessRuleRepository type
type MockFreshnessRuleRepository struct {
	mock.Mock
}

type MockFreshnessRuleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFreshnessRuleRepository) EXPECT() *MockFreshnessRuleRepository_Expecter {
	return &MockFreshnessRuleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, rule
func (_m *MockFreshnessRuleRepository) Create(ctx context.Context, rule *models.FreshnessRule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FreshnessRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFreshnessRuleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFreshnessRuleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *models.FreshnessRule
func (_e *MockFreshnessRuleRepository_Expecter) Create(ctx interface{}, rule interface{}) *MockFreshnessRuleRepository_Create_Call {
	return &MockFreshnessRuleRepository_Create_Call{Call: _e.mock.On("Create", ctx, rule)}
}

func (_c *MockFreshnessRuleRepository_Create_Call) Run(run func(ctx context.Context, rule *models.FreshnessRule)) *MockFreshnessRuleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FreshnessRule))
	})
	return _c
}

func (_c *MockFreshnessRuleRepository_Create_Call) Return(_a0 error) *MockFreshnessRuleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFreshnessRuleRepository_Create_Call) RunAndReturn(run func(context.Context, *models.FreshnessRule) error) *MockFreshnessRuleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, teamID, ruleID
func (_m *MockFreshnessRuleRepository) Delete(ctx context.Context, teamID string, ruleID string) (bool, error) {
	ret := _m.Called(ctx, teamID, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, teamID, ruleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, teamID, ruleID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, teamID, ruleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFreshnessRuleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFreshnessRuleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - ruleID string
func (_e *MockFreshnessRuleRepository_Expecter) Delete(ctx interface{}, teamID interface{}, ruleID interface{}) *MockFreshnessRuleRepository_Delete_Call {
	return &MockFreshnessRuleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, teamID, ruleID)}
}

func (_c *MockFreshnessRuleRepository_Delete_Call) Run(run func(ctx context.Context, teamID string, ruleID string)) *MockFreshnessRuleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFreshnessRuleRepository_Delete_Call) Return(_a0 bool, _a1 error) *MockFreshnessRuleRepository_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFreshnessRuleRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockFreshnessRuleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, teamID, ruleID
func (_m *MockFreshnessRuleRepository) GetByID(ctx context.Context, teamID string, ruleID string) (*models.FreshnessRule, error) {
	ret := _m.Called(ctx, teamID, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.FreshnessRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.FreshnessRule, error)); ok {
		return rf(ctx, teamID, ruleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.FreshnessRule); ok {
		r0 = rf(ctx, teamID, ruleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FreshnessRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, teamID, ruleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFreshnessRuleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockFreshnessRuleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - ruleID string
func (_e *MockFreshnessRuleRepository_Expecter) GetByID(ctx interface{}, teamID interface{}, ruleID interface{}) *MockFreshnessRuleRepository_GetByID_Call {
	return &MockFreshnessRuleRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, teamID, ruleID)}
}

func (_c *MockFreshnessRuleRepository_GetByID_Call) Run(run func(ctx context.Context, teamID string, ruleID string)) *MockFreshnessRuleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFreshnessRuleRepository_GetByID_Call) Return(_a0 *models.FreshnessRule, _a1 error) *MockFreshnessRuleRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFreshnessRuleRepository_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*models.FreshnessRule, error)) *MockFreshnessRuleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTeam provides a mock function with given fields: ctx, teamID, enabledOnly
func (_m *MockFreshnessRuleRepository) ListByTeam(ctx context.Context, teamID string, enabledOnly bool) ([]*models.FreshnessRule, error) {
	ret := _m.Called(ctx, teamID, enabledOnly)

	if len(ret) == 0 {
		panic("no return value specified for ListByTeam")
	}

	var r0 []*models.FreshnessRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) ([]*models.FreshnessRule, error)); ok {
		return rf(ctx, teamID, enabledOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) []*models.FreshnessRule); ok {
		r0 = rf(ctx, teamID, enabledOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FreshnessRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, teamID, enabledOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFreshnessRuleRepository_ListByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTeam'
type MockFreshnessRuleRepository_ListByTeam_Call struct {
	*mock.Call
}

// ListByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - enabledOnly bool
func (_e *MockFreshnessRuleRepository_Expecter) ListByTeam(ctx interface{}, teamID interface{}, enabledOnly interface{}) *MockFreshnessRuleRepository_ListByTeam_Call {
	return &MockFreshnessRuleRepository_ListByTeam_Call{Call: _e.mock.On("ListByTeam", ctx, teamID, enabledOnly)}
}

func (_c *MockFreshnessRuleRepository_ListByTeam_Call) Run(run func(ctx context.Context, teamID string, enabledOnly bool)) *MockFreshnessRuleRepository_ListByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockFreshnessRuleRepository_ListByTeam_Call) Return(_a0 []*models.FreshnessRule, _a1 error) *MockFreshnessRuleRepository_ListByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFreshnessRuleRepository_ListByTeam_Call) RunAndReturn(run func(context.Context, string, bool) ([]*models.FreshnessRule, error)) *MockFreshnessRuleRepository_ListByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// ListTeamIDsMissingSchedule provides a mock function with given fields: ctx, jobType
func (_m *MockFreshnessRuleRepository) ListTeamIDsMissingSchedule(ctx context.Context, jobType string) ([]string, error) {
	ret := _m.Called(ctx, jobType)

	if len(ret) == 0 {
		panic("no return value specified for ListTeamIDsMissingSchedule")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, jobType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, jobType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFreshnessRuleRepository_ListTeamIDsMissingSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeamIDsMissingSchedule'
type MockFreshnessRuleRepository_ListTeamIDsMissingSchedule_Call struct {
	*mock.Call
}

// ListTeamIDsMissingSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - jobType string
func (_e *MockFreshnessRuleRepository_Expecter) ListTeamIDsMissingSchedule(ctx interface{}, jobType interface{}) *MockFreshnessRuleRepository_ListTeamIDsMissingSchedule_Call {
	return &MockFreshnessRuleRepository_ListTeamIDsMissingSchedule_Call{Call: _e.mock.On("ListTeamIDsMissingSchedule", ctx, jobType)}
}

func (_c *MockFreshnessRuleRepository_ListTeamIDsMissingSchedule_Call) Run(run func(ctx context.Context, jobType string)) *MockFreshnessRuleRepository_ListTeamIDsMissingSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFreshnessRuleRepository_ListTeamIDsMissingSchedule_Call) Return(_a0 []string, _a1 error) *MockFreshnessRuleRepository_ListTeamIDsMissingSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFreshnessRuleRepository_ListTeamIDsMissingSchedule_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockFreshnessRuleRepository_ListTeamIDsMissingSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, rule
func (_m *MockFreshnessRuleRepository) Update(ctx context.Context, rule *models.FreshnessRule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FreshnessRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFreshnessRuleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFreshnessRuleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *models.FreshnessRule
func (_e *MockFreshnessRuleRepository_Expecter) Update(ctx interface{}, rule interface{}) *MockFreshnessRuleRepository_Update_Call {
	return &MockFreshnessRuleRepository_Update_Call{Call: _e.mock.On("Update", ctx, rule)}
}

func (_c *MockFreshnessRuleRepository_Update_Call) Run(run func(ctx context.Context, rule *models.FreshnessRule)) *MockFreshnessRuleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FreshnessRule))
	})
	return _c
}

func (_c *MockFreshnessRuleRepository_Update_Call) Return(_a0 error) *MockFreshnessRuleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFreshnessRuleRepository_Update_Call) RunAndReturn(run func(context.Context, *models.FreshnessRule) error) *MockFreshnessRuleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFreshnessRuleRepository creates a new instance of MockFreshnessRuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFreshnessRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFreshnessRuleRepository {
	mock := &MockFreshnessRuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
