// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/vibexp/vibexp/internal/models"
	mock "github.com/stretchr/testify/mock"

	repositories "github.com/vibexp/vibexp/internal/repositories"

	time "time"
)

// MockAgentExecutionRepository is an autogenerated mock type for the AgentExecutionRepository type
type MockAgentExecutionRepository struct {
	mock.Mock
}

type MockAgentExecutionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentExecutionRepository) EXPECT() *MockAgentExecutionRepository_Expecter {
	return &MockAgentExecutionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, execution
func (_m *MockAgentExecutionRepository) Create(ctx context.Context, execution *models.AgentExecution) error {
	ret := _m.Called(ctx, execution)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AgentExecution) error); ok {
		r0 = rf(ctx, execution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentExecutionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAgentExecutionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - execution *models.AgentExecution
func (_e *MockAgentExecutionRepository_Expecter) Create(ctx interface{}, execution interface{}) *MockAgentExecutionRepository_Create_Call {
	return &MockAgentExecutionRepository_Create_Call{Call: _e.mock.On("Create", ctx, execution)}
}

func (_c *MockAgentExecutionRepository_Create_Call) Run(run func(ctx context.Context, execution *models.AgentExecution)) *MockAgentExecutionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.AgentExecution))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_Create_Call) Return(_a0 error) *MockAgentExecutionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentExecutionRepository_Create_Call) RunAndReturn(run func(context.Context, *models.AgentExecution) error) *MockAgentExecutionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAgentID provides a mock function with given fields: ctx, userID, agentID, filters
func (_m *MockAgentExecutionRepository) GetByAgentID(ctx context.Context, userID string, agentID string, filters repositories.AgentExecutionFilters) ([]models.AgentExecution, int, error) {
	ret := _m.Called(ctx, userID, agentID, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetByAgentID")
	}

	var r0 []models.AgentExecution
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, repositories.AgentExecutionFilters) ([]models.AgentExecution, int, error)); ok {
		return rf(ctx, userID, agentID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, repositories.AgentExecutionFilters) []models.AgentExecution); ok {
		r0 = rf(ctx, userID, agentID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AgentExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, repositories.AgentExecutionFilters) int); ok {
		r1 = rf(ctx, userID, agentID, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, repositories.AgentExecutionFilters) error); ok {
		r2 = rf(ctx, userID, agentID, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAgentExecutionRepository_GetByAgentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAgentID'
type MockAgentExecutionRepository_GetByAgentID_Call struct {
	*mock.Call
}

// GetByAgentID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - agentID string
//   - filters repositories.AgentExecutionFilters
func (_e *MockAgentExecutionRepository_Expecter) GetByAgentID(ctx interface{}, userID interface{}, agentID interface{}, filters interface{}) *MockAgentExecutionRepository_GetByAgentID_Call {
	return &MockAgentExecutionRepository_GetByAgentID_Call{Call: _e.mock.On("GetByAgentID", ctx, userID, agentID, filters)}
}

func (_c *MockAgentExecutionRepository_GetByAgentID_Call) Run(run func(ctx context.Context, userID string, agentID string, filters repositories.AgentExecutionFilters)) *MockAgentExecutionRepository_GetByAgentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(repositories.AgentExecutionFilters))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_GetByAgentID_Call) Return(_a0 []models.AgentExecution, _a1 int, _a2 error) *MockAgentExecutionRepository_GetByAgentID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAgentExecutionRepository_GetByAgentID_Call) RunAndReturn(run func(context.Context, string, string, repositories.AgentExecutionFilters) ([]models.AgentExecution, int, error)) *MockAgentExecutionRepository_GetByAgentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByConversationID provides a mock function with given fields: ctx, userID, conversationID, limit, before
func (_m *MockAgentExecutionRepository) GetByConversationID(ctx context.Context, userID string, conversationID string, limit int, before *time.Time) ([]models.AgentExecution, bool, int, error) {
	ret := _m.Called(ctx, userID, conversationID, limit, before)

	if len(ret) == 0 {
		panic("no return value specified for GetByConversationID")
	}

	var r0 []models.AgentExecution
	var r1 bool
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, *time.Time) ([]models.AgentExecution, bool, int, error)); ok {
		return rf(ctx, userID, conversationID, limit, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, *time.Time) []models.AgentExecution); ok {
		r0 = rf(ctx, userID, conversationID, limit, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AgentExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, *time.Time) bool); ok {
		r1 = rf(ctx, userID, conversationID, limit, before)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, *time.Time) int); ok {
		r2 = rf(ctx, userID, conversationID, limit, before)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string, int, *time.Time) error); ok {
		r3 = rf(ctx, userID, conversationID, limit, before)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAgentExecutionRepository_GetByConversationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByConversationID'
type MockAgentExecutionRepository_GetByConversationID_Call struct {
	*mock.Call
}

// GetByConversationID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - conversationID string
//   - limit int
//   - before *time.Time
func (_e *MockAgentExecutionRepository_Expecter) GetByConversationID(ctx interface{}, userID interface{}, conversationID interface{}, limit interface{}, before interface{}) *MockAgentExecutionRepository_GetByConversationID_Call {
	return &MockAgentExecutionRepository_GetByConversationID_Call{Call: _e.mock.On("GetByConversationID", ctx, userID, conversationID, limit, before)}
}

func (_c *MockAgentExecutionRepository_GetByConversationID_Call) Run(run func(ctx context.Context, userID string, conversationID string, limit int, before *time.Time)) *MockAgentExecutionRepository_GetByConversationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(*time.Time))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_GetByConversationID_Call) Return(_a0 []models.AgentExecution, _a1 bool, _a2 int, _a3 error) *MockAgentExecutionRepository_GetByConversationID_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockAgentExecutionRepository_GetByConversationID_Call) RunAndReturn(run func(context.Context, string, string, int, *time.Time) ([]models.AgentExecution, bool, int, error)) *MockAgentExecutionRepository_GetByConversationID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, executionID
func (_m *MockAgentExecutionRepository) GetByID(ctx context.Context, userID string, executionID string) (*models.AgentExecution, error) {
	ret := _m.Called(ctx, userID, executionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.AgentExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.AgentExecution, error)); ok {
		return rf(ctx, userID, executionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.AgentExecution); ok {
		r0 = rf(ctx, userID, executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AgentExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, executionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentExecutionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAgentExecutionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - executionID string
func (_e *MockAgentExecutionRepository_Expecter) GetByID(ctx interface{}, userID interface{}, executionID interface{}) *MockAgentExecutionRepository_GetByID_Call {
	return &MockAgentExecutionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, executionID)}
}

func (_c *MockAgentExecutionRepository_GetByID_Call) Run(run func(ctx context.Context, userID string, executionID string)) *MockAgentExecutionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_GetByID_Call) Return(_a0 *models.AgentExecution, _a1 error) *MockAgentExecutionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentExecutionRepository_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*models.AgentExecution, error)) *MockAgentExecutionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTaskID provides a mock function with given fields: ctx, userID, taskID
func (_m *MockAgentExecutionRepository) GetByTaskID(ctx context.Context, userID string, taskID string) (*models.AgentExecution, error) {
	ret := _m.Called(ctx, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTaskID")
	}

	var r0 *models.AgentExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.AgentExecution, error)); ok {
		return rf(ctx, userID, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.AgentExecution); ok {
		r0 = rf(ctx, userID, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AgentExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentExecutionRepository_GetByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTaskID'
type MockAgentExecutionRepository_GetByTaskID_Call struct {
	*mock.Call
}

// GetByTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - taskID string
func (_e *MockAgentExecutionRepository_Expecter) GetByTaskID(ctx interface{}, userID interface{}, taskID interface{}) *MockAgentExecutionRepository_GetByTaskID_Call {
	return &MockAgentExecutionRepository_GetByTaskID_Call{Call: _e.mock.On("GetByTaskID", ctx, userID, taskID)}
}

func (_c *MockAgentExecutionRepository_GetByTaskID_Call) Run(run func(ctx context.Context, userID string, taskID string)) *MockAgentExecutionRepository_GetByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_GetByTaskID_Call) Return(_a0 *models.AgentExecution, _a1 error) *MockAgentExecutionRepository_GetByTaskID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentExecutionRepository_GetByTaskID_Call) RunAndReturn(run func(context.Context, string, string) (*models.AgentExecution, error)) *MockAgentExecutionRepository_GetByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFirstExecutionInConversation provides a mock function with given fields: ctx, userID, conversationID
func (_m *MockAgentExecutionRepository) GetFirstExecutionInConversation(ctx context.Context, userID string, conversationID string) (*models.AgentExecution, error) {
	ret := _m.Called(ctx, userID, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for GetFirstExecutionInConversation")
	}

	var r0 *models.AgentExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.AgentExecution, error)); ok {
		return rf(ctx, userID, conversationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.AgentExecution); ok {
		r0 = rf(ctx, userID, conversationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AgentExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, conversationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentExecutionRepository_GetFirstExecutionInConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirstExecutionInConversation'
type MockAgentExecutionRepository_GetFirstExecutionInConversation_Call struct {
	*mock.Call
}

// GetFirstExecutionInConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - conversationID string
func (_e *MockAgentExecutionRepository_Expecter) GetFirstExecutionInConversation(ctx interface{}, userID interface{}, conversationID interface{}) *MockAgentExecutionRepository_GetFirstExecutionInConversation_Call {
	return &MockAgentExecutionRepository_GetFirstExecutionInConversation_Call{Call: _e.mock.On("GetFirstExecutionInConversation", ctx, userID, conversationID)}
}

func (_c *MockAgentExecutionRepository_GetFirstExecutionInConversation_Call) Run(run func(ctx context.Context, userID string, conversationID string)) *MockAgentExecutionRepository_GetFirstExecutionInConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_GetFirstExecutionInConversation_Call) Return(_a0 *models.AgentExecution, _a1 error) *MockAgentExecutionRepository_GetFirstExecutionInConversation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentExecutionRepository_GetFirstExecutionInConversation_Call) RunAndReturn(run func(context.Context, string, string) (*models.AgentExecution, error)) *MockAgentExecutionRepository_GetFirstExecutionInConversation_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, filters
func (_m *MockAgentExecutionRepository) List(ctx context.Context, userID string, filters repositories.AgentExecutionFilters) ([]models.AgentExecution, int, error) {
	ret := _m.Called(ctx, userID, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.AgentExecution
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, repositories.AgentExecutionFilters) ([]models.AgentExecution, int, error)); ok {
		return rf(ctx, userID, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, repositories.AgentExecutionFilters) []models.AgentExecution); ok {
		r0 = rf(ctx, userID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AgentExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, repositories.AgentExecutionFilters) int); ok {
		r1 = rf(ctx, userID, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, repositories.AgentExecutionFilters) error); ok {
		r2 = rf(ctx, userID, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAgentExecutionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAgentExecutionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filters repositories.AgentExecutionFilters
func (_e *MockAgentExecutionRepository_Expecter) List(ctx interface{}, userID interface{}, filters interface{}) *MockAgentExecutionRepository_List_Call {
	return &MockAgentExecutionRepository_List_Call{Call: _e.mock.On("List", ctx, userID, filters)}
}

func (_c *MockAgentExecutionRepository_List_Call) Run(run func(ctx context.Context, userID string, filters repositories.AgentExecutionFilters)) *MockAgentExecutionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(repositories.AgentExecutionFilters))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_List_Call) Return(_a0 []models.AgentExecution, _a1 int, _a2 error) *MockAgentExecutionRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAgentExecutionRepository_List_Call) RunAndReturn(run func(context.Context, string, repositories.AgentExecutionFilters) ([]models.AgentExecution, int, error)) *MockAgentExecutionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListConversations provides a mock function with given fields: ctx, userID, agentID, page, limit
func (_m *MockAgentExecutionRepository) ListConversations(ctx context.Context, userID string, agentID string, page int, limit int) ([]models.ConversationSummary, int, error) {
	ret := _m.Called(ctx, userID, agentID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListConversations")
	}

	var r0 []models.ConversationSummary
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]models.ConversationSummary, int, error)); ok {
		return rf(ctx, userID, agentID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []models.ConversationSummary); ok {
		r0 = rf(ctx, userID, agentID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ConversationSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) int); ok {
		r1 = rf(ctx, userID, agentID, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, int) error); ok {
		r2 = rf(ctx, userID, agentID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAgentExecutionRepository_ListConversations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConversations'
type MockAgentExecutionRepository_ListConversations_Call struct {
	*mock.Call
}

// ListConversations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - agentID string
//   - page int
//   - limit int
func (_e *MockAgentExecutionRepository_Expecter) ListConversations(ctx interface{}, userID interface{}, agentID interface{}, page interface{}, limit interface{}) *MockAgentExecutionRepository_ListConversations_Call {
	return &MockAgentExecutionRepository_ListConversations_Call{Call: _e.mock.On("ListConversations", ctx, userID, agentID, page, limit)}
}

func (_c *MockAgentExecutionRepository_ListConversations_Call) Run(run func(ctx context.Context, userID string, agentID string, page int, limit int)) *MockAgentExecutionRepository_ListConversations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_ListConversations_Call) Return(_a0 []models.ConversationSummary, _a1 int, _a2 error) *MockAgentExecutionRepository_ListConversations_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAgentExecutionRepository_ListConversations_Call) RunAndReturn(run func(context.Context, string, string, int, int) ([]models.ConversationSummary, int, error)) *MockAgentExecutionRepository_ListConversations_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, execution
func (_m *MockAgentExecutionRepository) Update(ctx context.Context, execution *models.AgentExecution) error {
	ret := _m.Called(ctx, execution)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AgentExecution) error); ok {
		r0 = rf(ctx, execution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentExecutionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAgentExecutionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - execution *models.AgentExecution
func (_e *MockAgentExecutionRepository_Expecter) Update(ctx interface{}, execution interface{}) *MockAgentExecutionRepository_Update_Call {
	return &MockAgentExecutionRepository_Update_Call{Call: _e.mock.On("Update", ctx, execution)}
}

func (_c *MockAgentExecutionRepository_Update_Call) Run(run func(ctx context.Context, execution *models.AgentExecution)) *MockAgentExecutionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.AgentExecution))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_Update_Call) Return(_a0 error) *MockAgentExecutionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentExecutionRepository_Update_Call) RunAndReturn(run func(context.Context, *models.AgentExecution) error) *MockAgentExecutionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtifacts provides a mock function with given fields: ctx, executionID, artifacts
func (_m *MockAgentExecutionRepository) UpdateArtifacts(ctx context.Context, executionID string, artifacts []map[string]interface{}) error {
	ret := _m.Called(ctx, executionID, artifacts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifacts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []map[string]interface{}) error); ok {
		r0 = rf(ctx, executionID, artifacts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentExecutionRepository_UpdateArtifacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtifacts'
type MockAgentExecutionRepository_UpdateArtifacts_Call struct {
	*mock.Call
}

// UpdateArtifacts is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
//   - artifacts []map[string]interface{}
func (_e *MockAgentExecutionRepository_Expecter) UpdateArtifacts(ctx interface{}, executionID interface{}, artifacts interface{}) *MockAgentExecutionRepository_UpdateArtifacts_Call {
	return &MockAgentExecutionRepository_UpdateArtifacts_Call{Call: _e.mock.On("UpdateArtifacts", ctx, executionID, artifacts)}
}

func (_c *MockAgentExecutionRepository_UpdateArtifacts_Call) Run(run func(ctx context.Context, executionID string, artifacts []map[string]interface{})) *MockAgentExecutionRepository_UpdateArtifacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]map[string]interface{}))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_UpdateArtifacts_Call) Return(_a0 error) *MockAgentExecutionRepository_UpdateArtifacts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentExecutionRepository_UpdateArtifacts_Call) RunAndReturn(run func(context.Context, string, []map[string]interface{}) error) *MockAgentExecutionRepository_UpdateArtifacts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConversationID provides a mock function with given fields: ctx, executionID, conversationID
func (_m *MockAgentExecutionRepository) UpdateConversationID(ctx context.Context, executionID string, conversationID string) error {
	ret := _m.Called(ctx, executionID, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConversationID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, executionID, conversationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentExecutionRepository_UpdateConversationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConversationID'
type MockAgentExecutionRepository_UpdateConversationID_Call struct {
	*mock.Call
}

// UpdateConversationID is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
//   - conversationID string
func (_e *MockAgentExecutionRepository_Expecter) UpdateConversationID(ctx interface{}, executionID interface{}, conversationID interface{}) *MockAgentExecutionRepository_UpdateConversationID_Call {
	return &MockAgentExecutionRepository_UpdateConversationID_Call{Call: _e.mock.On("UpdateConversationID", ctx, executionID, conversationID)}
}

func (_c *MockAgentExecutionRepository_UpdateConversationID_Call) Run(run func(ctx context.Context, executionID string, conversationID string)) *MockAgentExecutionRepository_UpdateConversationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_UpdateConversationID_Call) Return(_a0 error) *MockAgentExecutionRepository_UpdateConversationID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentExecutionRepository_UpdateConversationID_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAgentExecutionRepository_UpdateConversationID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, executionID, status
func (_m *MockAgentExecutionRepository) UpdateStatus(ctx context.Context, executionID string, status string) error {
	ret := _m.Called(ctx, executionID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, executionID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentExecutionRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockAgentExecutionRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
//   - status string
func (_e *MockAgentExecutionRepository_Expecter) UpdateStatus(ctx interface{}, executionID interface{}, status interface{}) *MockAgentExecutionRepository_UpdateStatus_Call {
	return &MockAgentExecutionRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, executionID, status)}
}

func (_c *MockAgentExecutionRepository_UpdateStatus_Call) Run(run func(ctx context.Context, executionID string, status string)) *MockAgentExecutionRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_UpdateStatus_Call) Return(_a0 error) *MockAgentExecutionRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentExecutionRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAgentExecutionRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskInfo provides a mock function with given fields: ctx, executionID, taskID, contextID, currentState
func (_m *MockAgentExecutionRepository) UpdateTaskInfo(ctx context.Context, executionID string, taskID string, contextID string, currentState string) error {
	ret := _m.Called(ctx, executionID, taskID, contextID, currentState)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, executionID, taskID, contextID, currentState)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentExecutionRepository_UpdateTaskInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskInfo'
type MockAgentExecutionRepository_UpdateTaskInfo_Call struct {
	*mock.Call
}

// UpdateTaskInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
//   - taskID string
//   - contextID string
//   - currentState string
func (_e *MockAgentExecutionRepository_Expecter) UpdateTaskInfo(ctx interface{}, executionID interface{}, taskID interface{}, contextID interface{}, currentState interface{}) *MockAgentExecutionRepository_UpdateTaskInfo_Call {
	return &MockAgentExecutionRepository_UpdateTaskInfo_Call{Call: _e.mock.On("UpdateTaskInfo", ctx, executionID, taskID, contextID, currentState)}
}

func (_c *MockAgentExecutionRepository_UpdateTaskInfo_Call) Run(run func(ctx context.Context, executionID string, taskID string, contextID string, currentState string)) *MockAgentExecutionRepository_UpdateTaskInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAgentExecutionRepository_UpdateTaskInfo_Call) Return(_a0 error) *MockAgentExecutionRepository_UpdateTaskInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentExecutionRepository_UpdateTaskInfo_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockAgentExecutionRepository_UpdateTaskInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentExecutionRepository creates a new instance of MockAgentExecutionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentExecutionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentExecutionRepository {
	mock := &MockAgentExecutionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
