// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"

	time "time"
)

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// CountByOwnerID provides a mock function with given fields: ctx, ownerID
func (_m *MockTeamRepository) CountByOwnerID(ctx context.Context, ownerID string) (int, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for CountByOwnerID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, ownerID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_CountByOwnerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByOwnerID'
type MockTeamRepository_CountByOwnerID_Call struct {
	*mock.Call
}

// CountByOwnerID is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
func (_e *MockTeamRepository_Expecter) CountByOwnerID(ctx interface{}, ownerID interface{}) *MockTeamRepository_CountByOwnerID_Call {
	return &MockTeamRepository_CountByOwnerID_Call{Call: _e.mock.On("CountByOwnerID", ctx, ownerID)}
}

func (_c *MockTeamRepository_CountByOwnerID_Call) Run(run func(ctx context.Context, ownerID string)) *MockTeamRepository_CountByOwnerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamRepository_CountByOwnerID_Call) Return(_a0 int, _a1 error) *MockTeamRepository_CountByOwnerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_CountByOwnerID_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockTeamRepository_CountByOwnerID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, team
func (_m *MockTeamRepository) Create(ctx context.Context, team *models.Team) error {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Team) error); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - team *models.Team
func (_e *MockTeamRepository_Expecter) Create(ctx interface{}, team interface{}) *MockTeamRepository_Create_Call {
	return &MockTeamRepository_Create_Call{Call: _e.mock.On("Create", ctx, team)}
}

func (_c *MockTeamRepository_Create_Call) Run(run func(ctx context.Context, team *models.Team)) *MockTeamRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Team))
	})
	return _c
}

func (_c *MockTeamRepository_Create_Call) Return(_a0 error) *MockTeamRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Team) error) *MockTeamRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ownerID, teamID
func (_m *MockTeamRepository) Delete(ctx context.Context, ownerID string, teamID string) error {
	ret := _m.Called(ctx, ownerID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, ownerID, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTeamRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - teamID string
func (_e *MockTeamRepository_Expecter) Delete(ctx interface{}, ownerID interface{}, teamID interface{}) *MockTeamRepository_Delete_Call {
	return &MockTeamRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ownerID, teamID)}
}

func (_c *MockTeamRepository_Delete_Call) Run(run func(ctx context.Context, ownerID string, teamID string)) *MockTeamRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTeamRepository_Delete_Call) Return(_a0 error) *MockTeamRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTeamRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, teamID
func (_m *MockTeamRepository) GetByID(ctx context.Context, teamID string) (*models.Team, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTeamRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockTeamRepository_Expecter) GetByID(ctx interface{}, teamID interface{}) *MockTeamRepository_GetByID_Call {
	return &MockTeamRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, teamID)}
}

func (_c *MockTeamRepository_GetByID_Call) Run(run func(ctx context.Context, teamID string)) *MockTeamRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamRepository_GetByID_Call) Return(_a0 *models.Team, _a1 error) *MockTeamRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*models.Team, error)) *MockTeamRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOwnerAndSlug provides a mock function with given fields: ctx, ownerID, slug
func (_m *MockTeamRepository) GetByOwnerAndSlug(ctx context.Context, ownerID string, slug string) (*models.Team, error) {
	ret := _m.Called(ctx, ownerID, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetByOwnerAndSlug")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Team, error)); ok {
		return rf(ctx, ownerID, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Team); ok {
		r0 = rf(ctx, ownerID, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, ownerID, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_GetByOwnerAndSlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOwnerAndSlug'
type MockTeamRepository_GetByOwnerAndSlug_Call struct {
	*mock.Call
}

// GetByOwnerAndSlug is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - slug string
func (_e *MockTeamRepository_Expecter) GetByOwnerAndSlug(ctx interface{}, ownerID interface{}, slug interface{}) *MockTeamRepository_GetByOwnerAndSlug_Call {
	return &MockTeamRepository_GetByOwnerAndSlug_Call{Call: _e.mock.On("GetByOwnerAndSlug", ctx, ownerID, slug)}
}

func (_c *MockTeamRepository_GetByOwnerAndSlug_Call) Run(run func(ctx context.Context, ownerID string, slug string)) *MockTeamRepository_GetByOwnerAndSlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTeamRepository_GetByOwnerAndSlug_Call) Return(_a0 *models.Team, _a1 error) *MockTeamRepository_GetByOwnerAndSlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetByOwnerAndSlug_Call) RunAndReturn(run func(context.Context, string, string) (*models.Team, error)) *MockTeamRepository_GetByOwnerAndSlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOwnerID provides a mock function with given fields: ctx, ownerID
func (_m *MockTeamRepository) GetByOwnerID(ctx context.Context, ownerID string) (*models.Team, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOwnerID")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_GetByOwnerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOwnerID'
type MockTeamRepository_GetByOwnerID_Call struct {
	*mock.Call
}

// GetByOwnerID is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
func (_e *MockTeamRepository_Expecter) GetByOwnerID(ctx interface{}, ownerID interface{}) *MockTeamRepository_GetByOwnerID_Call {
	return &MockTeamRepository_GetByOwnerID_Call{Call: _e.mock.On("GetByOwnerID", ctx, ownerID)}
}

func (_c *MockTeamRepository_GetByOwnerID_Call) Run(run func(ctx context.Context, ownerID string)) *MockTeamRepository_GetByOwnerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamRepository_GetByOwnerID_Call) Return(_a0 *models.Team, _a1 error) *MockTeamRepository_GetByOwnerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetByOwnerID_Call) RunAndReturn(run func(context.Context, string) (*models.Team, error)) *MockTeamRepository_GetByOwnerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamFeedCreationMetrics provides a mock function with given fields: ctx, teamID, since
func (_m *MockTeamRepository) GetTeamFeedCreationMetrics(ctx context.Context, teamID string, since time.Time) ([]models.TeamFeedCreationCount, error) {
	ret := _m.Called(ctx, teamID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamFeedCreationMetrics")
	}

	var r0 []models.TeamFeedCreationCount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]models.TeamFeedCreationCount, error)); ok {
		return rf(ctx, teamID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []models.TeamFeedCreationCount); ok {
		r0 = rf(ctx, teamID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamFeedCreationCount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, teamID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_GetTeamFeedCreationMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamFeedCreationMetrics'
type MockTeamRepository_GetTeamFeedCreationMetrics_Call struct {
	*mock.Call
}

// GetTeamFeedCreationMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - since time.Time
func (_e *MockTeamRepository_Expecter) GetTeamFeedCreationMetrics(ctx interface{}, teamID interface{}, since interface{}) *MockTeamRepository_GetTeamFeedCreationMetrics_Call {
	return &MockTeamRepository_GetTeamFeedCreationMetrics_Call{Call: _e.mock.On("GetTeamFeedCreationMetrics", ctx, teamID, since)}
}

func (_c *MockTeamRepository_GetTeamFeedCreationMetrics_Call) Run(run func(ctx context.Context, teamID string, since time.Time)) *MockTeamRepository_GetTeamFeedCreationMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamFeedCreationMetrics_Call) Return(_a0 []models.TeamFeedCreationCount, _a1 error) *MockTeamRepository_GetTeamFeedCreationMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetTeamFeedCreationMetrics_Call) RunAndReturn(run func(context.Context, string, time.Time) ([]models.TeamFeedCreationCount, error)) *MockTeamRepository_GetTeamFeedCreationMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamResourceCreationMetrics provides a mock function with given fields: ctx, teamID, since
func (_m *MockTeamRepository) GetTeamResourceCreationMetrics(ctx context.Context, teamID string, since time.Time) ([]models.TeamResourceCreationCount, error) {
	ret := _m.Called(ctx, teamID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamResourceCreationMetrics")
	}

	var r0 []models.TeamResourceCreationCount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]models.TeamResourceCreationCount, error)); ok {
		return rf(ctx, teamID, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []models.TeamResourceCreationCount); ok {
		r0 = rf(ctx, teamID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamResourceCreationCount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, teamID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_GetTeamResourceCreationMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamResourceCreationMetrics'
type MockTeamRepository_GetTeamResourceCreationMetrics_Call struct {
	*mock.Call
}

// GetTeamResourceCreationMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - since time.Time
func (_e *MockTeamRepository_Expecter) GetTeamResourceCreationMetrics(ctx interface{}, teamID interface{}, since interface{}) *MockTeamRepository_GetTeamResourceCreationMetrics_Call {
	return &MockTeamRepository_GetTeamResourceCreationMetrics_Call{Call: _e.mock.On("GetTeamResourceCreationMetrics", ctx, teamID, since)}
}

func (_c *MockTeamRepository_GetTeamResourceCreationMetrics_Call) Run(run func(ctx context.Context, teamID string, since time.Time)) *MockTeamRepository_GetTeamResourceCreationMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamResourceCreationMetrics_Call) Return(_a0 []models.TeamResourceCreationCount, _a1 error) *MockTeamRepository_GetTeamResourceCreationMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetTeamResourceCreationMetrics_Call) RunAndReturn(run func(context.Context, string, time.Time) ([]models.TeamResourceCreationCount, error)) *MockTeamRepository_GetTeamResourceCreationMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamStats provides a mock function with given fields: ctx, teamID
func (_m *MockTeamRepository) GetTeamStats(ctx context.Context, teamID string) (*models.TeamStatsResponse, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamStats")
	}

	var r0 *models.TeamStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.TeamStatsResponse, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.TeamStatsResponse); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamRepository_GetTeamStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamStats'
type MockTeamRepository_GetTeamStats_Call struct {
	*mock.Call
}

// GetTeamStats is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockTeamRepository_Expecter) GetTeamStats(ctx interface{}, teamID interface{}) *MockTeamRepository_GetTeamStats_Call {
	return &MockTeamRepository_GetTeamStats_Call{Call: _e.mock.On("GetTeamStats", ctx, teamID)}
}

func (_c *MockTeamRepository_GetTeamStats_Call) Run(run func(ctx context.Context, teamID string)) *MockTeamRepository_GetTeamStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamRepository_GetTeamStats_Call) Return(_a0 *models.TeamStatsResponse, _a1 error) *MockTeamRepository_GetTeamStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamRepository_GetTeamStats_Call) RunAndReturn(run func(context.Context, string) (*models.TeamStatsResponse, error)) *MockTeamRepository_GetTeamStats_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOwnerID provides a mock function with given fields: ctx, ownerID, limit, offset
func (_m *MockTeamRepository) ListByOwnerID(ctx context.Context, ownerID string, limit int, offset int) ([]models.Team, int, error) {
	ret := _m.Called(ctx, ownerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByOwnerID")
	}

	var r0 []models.Team
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Team, int, error)); ok {
		return rf(ctx, ownerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Team); ok {
		r0 = rf(ctx, ownerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, ownerID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, ownerID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTeamRepository_ListByOwnerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOwnerID'
type MockTeamRepository_ListByOwnerID_Call struct {
	*mock.Call
}

// ListByOwnerID is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - limit int
//   - offset int
func (_e *MockTeamRepository_Expecter) ListByOwnerID(ctx interface{}, ownerID interface{}, limit interface{}, offset interface{}) *MockTeamRepository_ListByOwnerID_Call {
	return &MockTeamRepository_ListByOwnerID_Call{Call: _e.mock.On("ListByOwnerID", ctx, ownerID, limit, offset)}
}

func (_c *MockTeamRepository_ListByOwnerID_Call) Run(run func(ctx context.Context, ownerID string, limit int, offset int)) *MockTeamRepository_ListByOwnerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTeamRepository_ListByOwnerID_Call) Return(_a0 []models.Team, _a1 int, _a2 error) *MockTeamRepository_ListByOwnerID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTeamRepository_ListByOwnerID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]models.Team, int, error)) *MockTeamRepository_ListByOwnerID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockTeamRepository) ListByUserID(ctx context.Context, userID string, limit int, offset int) ([]models.Team, int, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []models.Team
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Team, int, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Team); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTeamRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockTeamRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *MockTeamRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockTeamRepository_ListByUserID_Call {
	return &MockTeamRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, limit, offset)}
}

func (_c *MockTeamRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *MockTeamRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTeamRepository_ListByUserID_Call) Return(_a0 []models.Team, _a1 int, _a2 error) *MockTeamRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTeamRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]models.Team, int, error)) *MockTeamRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, team
func (_m *MockTeamRepository) Update(ctx context.Context, team *models.Team) error {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Team) error); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTeamRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - team *models.Team
func (_e *MockTeamRepository_Expecter) Update(ctx interface{}, team interface{}) *MockTeamRepository_Update_Call {
	return &MockTeamRepository_Update_Call{Call: _e.mock.On("Update", ctx, team)}
}

func (_c *MockTeamRepository_Update_Call) Run(run func(ctx context.Context, team *models.Team)) *MockTeamRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Team))
	})
	return _c
}

func (_c *MockTeamRepository_Update_Call) Return(_a0 error) *MockTeamRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Team) error) *MockTeamRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
