// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockFreshnessAuditRepository is an autogenerated mock type for the FreshnessAuditRepository type
type MockFreshnessAuditRepository struct {
	mock.Mock
}

type MockFreshnessAuditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFreshnessAuditRepository) EXPECT() *MockFreshnessAuditRepository_Expecter {
	return &MockFreshnessAuditRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entry
func (_m *MockFreshnessAuditRepository) Create(ctx context.Context, entry *models.ResourceFreshnessAudit) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ResourceFreshnessAudit) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFreshnessAuditRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFreshnessAuditRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *models.ResourceFreshnessAudit
func (_e *MockFreshnessAuditRepository_Expecter) Create(ctx interface{}, entry interface{}) *MockFreshnessAuditRepository_Create_Call {
	return &MockFreshnessAuditRepository_Create_Call{Call: _e.mock.On("Create", ctx, entry)}
}

func (_c *MockFreshnessAuditRepository_Create_Call) Run(run func(ctx context.Context, entry *models.ResourceFreshnessAudit)) *MockFreshnessAuditRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.ResourceFreshnessAudit))
	})
	return _c
}

func (_c *MockFreshnessAuditRepository_Create_Call) Return(_a0 error) *MockFreshnessAuditRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFreshnessAuditRepository_Create_Call) RunAndReturn(run func(context.Context, *models.ResourceFreshnessAudit) error) *MockFreshnessAuditRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTeam provides a mock function with given fields: ctx, teamID, limit, offset
func (_m *MockFreshnessAuditRepository) ListByTeam(ctx context.Context, teamID string, limit int, offset int) ([]*models.ResourceFreshnessAudit, int, error) {
	ret := _m.Called(ctx, teamID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByTeam")
	}

	var r0 []*models.ResourceFreshnessAudit
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*models.ResourceFreshnessAudit, int, error)); ok {
		return rf(ctx, teamID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*models.ResourceFreshnessAudit); ok {
		r0 = rf(ctx, teamID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ResourceFreshnessAudit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, teamID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, teamID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFreshnessAuditRepository_ListByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTeam'
type MockFreshnessAuditRepository_ListByTeam_Call struct {
	*mock.Call
}

// ListByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - limit int
//   - offset int
func (_e *MockFreshnessAuditRepository_Expecter) ListByTeam(ctx interface{}, teamID interface{}, limit interface{}, offset interface{}) *MockFreshnessAuditRepository_ListByTeam_Call {
	return &MockFreshnessAuditRepository_ListByTeam_Call{Call: _e.mock.On("ListByTeam", ctx, teamID, limit, offset)}
}

func (_c *MockFreshnessAuditRepository_ListByTeam_Call) Run(run func(ctx context.Context, teamID string, limit int, offset int)) *MockFreshnessAuditRepository_ListByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockFreshnessAuditRepository_ListByTeam_Call) Return(_a0 []*models.ResourceFreshnessAudit, _a1 int, _a2 error) *MockFreshnessAuditRepository_ListByTeam_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockFreshnessAuditRepository_ListByTeam_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*models.ResourceFreshnessAudit, int, error)) *MockFreshnessAuditRepository_ListByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFreshnessAuditRepository creates a new instance of MockFreshnessAuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFreshnessAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFreshnessAuditRepository {
	mock := &MockFreshnessAuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
