// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserRepository) Create(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(_a0 error) *MockUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) DeleteByID(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockUserRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) DeleteByID(ctx interface{}, userID interface{}) *MockUserRepository_DeleteByID_Call {
	return &MockUserRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, userID)}
}

func (_c *MockUserRepository_DeleteByID_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_DeleteByID_Call) Return(_a0 error) *MockUserRepository_DeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_DeleteByID_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGoogleID provides a mock function with given fields: ctx, googleID
func (_m *MockUserRepository) GetByGoogleID(ctx context.Context, googleID string) (*models.User, error) {
	ret := _m.Called(ctx, googleID)

	if len(ret) == 0 {
		panic("no return value specified for GetByGoogleID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, googleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, googleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, googleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByGoogleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGoogleID'
type MockUserRepository_GetByGoogleID_Call struct {
	*mock.Call
}

// GetByGoogleID is a helper method to define mock.On call
//   - ctx context.Context
//   - googleID string
func (_e *MockUserRepository_Expecter) GetByGoogleID(ctx interface{}, googleID interface{}) *MockUserRepository_GetByGoogleID_Call {
	return &MockUserRepository_GetByGoogleID_Call{Call: _e.mock.On("GetByGoogleID", ctx, googleID)}
}

func (_c *MockUserRepository_GetByGoogleID_Call) Run(run func(ctx context.Context, googleID string)) *MockUserRepository_GetByGoogleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetByGoogleID_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_GetByGoogleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetByGoogleID_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserRepository_GetByGoogleID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) GetByID(ctx context.Context, userID string) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) GetByID(ctx interface{}, userID interface{}) *MockUserRepository_GetByID_Call {
	return &MockUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID)}
}

func (_c *MockUserRepository_GetByID_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetByID_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDPSubject provides a mock function with given fields: ctx, provider, subject
func (_m *MockUserRepository) GetByIDPSubject(ctx context.Context, provider string, subject string) (*models.User, error) {
	ret := _m.Called(ctx, provider, subject)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDPSubject")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.User, error)); ok {
		return rf(ctx, provider, subject)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.User); ok {
		r0 = rf(ctx, provider, subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, provider, subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByIDPSubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDPSubject'
type MockUserRepository_GetByIDPSubject_Call struct {
	*mock.Call
}

// GetByIDPSubject is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - subject string
func (_e *MockUserRepository_Expecter) GetByIDPSubject(ctx interface{}, provider interface{}, subject interface{}) *MockUserRepository_GetByIDPSubject_Call {
	return &MockUserRepository_GetByIDPSubject_Call{Call: _e.mock.On("GetByIDPSubject", ctx, provider, subject)}
}

func (_c *MockUserRepository_GetByIDPSubject_Call) Run(run func(ctx context.Context, provider string, subject string)) *MockUserRepository_GetByIDPSubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetByIDPSubject_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_GetByIDPSubject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetByIDPSubject_Call) RunAndReturn(run func(context.Context, string, string) (*models.User, error)) *MockUserRepository_GetByIDPSubject_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamesByIDs provides a mock function with given fields: ctx, ids
func (_m *MockUserRepository) GetNamesByIDs(ctx context.Context, ids []string) (map[string]string, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetNamesByIDs")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]string, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]string); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetNamesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamesByIDs'
type MockUserRepository_GetNamesByIDs_Call struct {
	*mock.Call
}

// GetNamesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockUserRepository_Expecter) GetNamesByIDs(ctx interface{}, ids interface{}) *MockUserRepository_GetNamesByIDs_Call {
	return &MockUserRepository_GetNamesByIDs_Call{Call: _e.mock.On("GetNamesByIDs", ctx, ids)}
}

func (_c *MockUserRepository_GetNamesByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockUserRepository_GetNamesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockUserRepository_GetNamesByIDs_Call) Return(_a0 map[string]string, _a1 error) *MockUserRepository_GetNamesByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetNamesByIDs_Call) RunAndReturn(run func(context.Context, []string) (map[string]string, error)) *MockUserRepository_GetNamesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOnboardingCompleted provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) MarkOnboardingCompleted(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkOnboardingCompleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_MarkOnboardingCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOnboardingCompleted'
type MockUserRepository_MarkOnboardingCompleted_Call struct {
	*mock.Call
}

// MarkOnboardingCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) MarkOnboardingCompleted(ctx interface{}, userID interface{}) *MockUserRepository_MarkOnboardingCompleted_Call {
	return &MockUserRepository_MarkOnboardingCompleted_Call{Call: _e.mock.On("MarkOnboardingCompleted", ctx, userID)}
}

func (_c *MockUserRepository_MarkOnboardingCompleted_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_MarkOnboardingCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_MarkOnboardingCompleted_Call) Return(_a0 error) *MockUserRepository_MarkOnboardingCompleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_MarkOnboardingCompleted_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRepository_MarkOnboardingCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockUserRepository) Update(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, user interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDefaultTeamID provides a mock function with given fields: ctx, userID, teamID
func (_m *MockUserRepository) UpdateDefaultTeamID(ctx context.Context, userID string, teamID string) error {
	ret := _m.Called(ctx, userID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDefaultTeamID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateDefaultTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDefaultTeamID'
type MockUserRepository_UpdateDefaultTeamID_Call struct {
	*mock.Call
}

// UpdateDefaultTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
func (_e *MockUserRepository_Expecter) UpdateDefaultTeamID(ctx interface{}, userID interface{}, teamID interface{}) *MockUserRepository_UpdateDefaultTeamID_Call {
	return &MockUserRepository_UpdateDefaultTeamID_Call{Call: _e.mock.On("UpdateDefaultTeamID", ctx, userID, teamID)}
}

func (_c *MockUserRepository_UpdateDefaultTeamID_Call) Run(run func(ctx context.Context, userID string, teamID string)) *MockUserRepository_UpdateDefaultTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_UpdateDefaultTeamID_Call) Return(_a0 error) *MockUserRepository_UpdateDefaultTeamID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateDefaultTeamID_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserRepository_UpdateDefaultTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
