// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"

	repositories "github.com/vibexp/vibexp/internal/repositories"

	time "time"
)

// MockActivityRepository is an autogenerated mock type for the ActivityRepository type
type MockActivityRepository struct {
	mock.Mock
}

type MockActivityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityRepository) EXPECT() *MockActivityRepository_Expecter {
	return &MockActivityRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, activity
func (_m *MockActivityRepository) Create(ctx context.Context, activity *models.Activity) error {
	ret := _m.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Activity) error); ok {
		r0 = rf(ctx, activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockActivityRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockActivityRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - activity *models.Activity
func (_e *MockActivityRepository_Expecter) Create(ctx interface{}, activity interface{}) *MockActivityRepository_Create_Call {
	return &MockActivityRepository_Create_Call{Call: _e.mock.On("Create", ctx, activity)}
}

func (_c *MockActivityRepository_Create_Call) Run(run func(ctx context.Context, activity *models.Activity)) *MockActivityRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Activity))
	})
	return _c
}

func (_c *MockActivityRepository_Create_Call) Return(_a0 error) *MockActivityRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockActivityRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Activity) error) *MockActivityRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, activityID
func (_m *MockActivityRepository) Delete(ctx context.Context, activityID string) error {
	ret := _m.Called(ctx, activityID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, activityID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockActivityRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockActivityRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID string
func (_e *MockActivityRepository_Expecter) Delete(ctx interface{}, activityID interface{}) *MockActivityRepository_Delete_Call {
	return &MockActivityRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, activityID)}
}

func (_c *MockActivityRepository_Delete_Call) Run(run func(ctx context.Context, activityID string)) *MockActivityRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockActivityRepository_Delete_Call) Return(_a0 error) *MockActivityRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockActivityRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockActivityRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function with given fields: ctx, before
func (_m *MockActivityRepository) DeleteOlderThan(ctx context.Context, before time.Time) (int64, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivityRepository_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type MockActivityRepository_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockActivityRepository_Expecter) DeleteOlderThan(ctx interface{}, before interface{}) *MockActivityRepository_DeleteOlderThan_Call {
	return &MockActivityRepository_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", ctx, before)}
}

func (_c *MockActivityRepository_DeleteOlderThan_Call) Run(run func(ctx context.Context, before time.Time)) *MockActivityRepository_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockActivityRepository_DeleteOlderThan_Call) Return(_a0 int64, _a1 error) *MockActivityRepository_DeleteOlderThan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivityRepository_DeleteOlderThan_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *MockActivityRepository_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, activityID
func (_m *MockActivityRepository) GetByID(ctx context.Context, userID string, activityID string) (*models.Activity, error) {
	ret := _m.Called(ctx, userID, activityID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Activity, error)); ok {
		return rf(ctx, userID, activityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Activity); ok {
		r0 = rf(ctx, userID, activityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, activityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivityRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockActivityRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - activityID string
func (_e *MockActivityRepository_Expecter) GetByID(ctx interface{}, userID interface{}, activityID interface{}) *MockActivityRepository_GetByID_Call {
	return &MockActivityRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, activityID)}
}

func (_c *MockActivityRepository_GetByID_Call) Run(run func(ctx context.Context, userID string, activityID string)) *MockActivityRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockActivityRepository_GetByID_Call) Return(_a0 *models.Activity, _a1 error) *MockActivityRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivityRepository_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*models.Activity, error)) *MockActivityRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx, userID
func (_m *MockActivityRepository) GetStats(ctx context.Context, userID string) (*models.ActivityStatsResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *models.ActivityStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.ActivityStatsResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ActivityStatsResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ActivityStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivityRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockActivityRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockActivityRepository_Expecter) GetStats(ctx interface{}, userID interface{}) *MockActivityRepository_GetStats_Call {
	return &MockActivityRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, userID)}
}

func (_c *MockActivityRepository_GetStats_Call) Run(run func(ctx context.Context, userID string)) *MockActivityRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockActivityRepository_GetStats_Call) Return(_a0 *models.ActivityStatsResponse, _a1 error) *MockActivityRepository_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivityRepository_GetStats_Call) RunAndReturn(run func(context.Context, string) (*models.ActivityStatsResponse, error)) *MockActivityRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filters
func (_m *MockActivityRepository) List(ctx context.Context, filters repositories.ActivityFilters) (*models.ActivityListResponse, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *models.ActivityListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.ActivityFilters) (*models.ActivityListResponse, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repositories.ActivityFilters) *models.ActivityListResponse); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ActivityListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repositories.ActivityFilters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivityRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockActivityRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filters repositories.ActivityFilters
func (_e *MockActivityRepository_Expecter) List(ctx interface{}, filters interface{}) *MockActivityRepository_List_Call {
	return &MockActivityRepository_List_Call{Call: _e.mock.On("List", ctx, filters)}
}

func (_c *MockActivityRepository_List_Call) Run(run func(ctx context.Context, filters repositories.ActivityFilters)) *MockActivityRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.ActivityFilters))
	})
	return _c
}

func (_c *MockActivityRepository_List_Call) Return(_a0 *models.ActivityListResponse, _a1 error) *MockActivityRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivityRepository_List_Call) RunAndReturn(run func(context.Context, repositories.ActivityFilters) (*models.ActivityListResponse, error)) *MockActivityRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActivityRepository creates a new instance of MockActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityRepository {
	mock := &MockActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
