// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockInstanceAuthAllowlistRepository is an autogenerated mock type for the InstanceAuthAllowlistRepository type
type MockInstanceAuthAllowlistRepository struct {
	mock.Mock
}

type MockInstanceAuthAllowlistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstanceAuthAllowlistRepository) EXPECT() *MockInstanceAuthAllowlistRepository_Expecter {
	return &MockInstanceAuthAllowlistRepository_Expecter{mock: &_m.Mock}
}

// CountUsersOutside provides a mock function with given fields: ctx, domains, emails, exemptEmails, sampleLimit
func (_m *MockInstanceAuthAllowlistRepository) CountUsersOutside(ctx context.Context, domains []string, emails []string, exemptEmails []string, sampleLimit int) (int, []string, error) {
	ret := _m.Called(ctx, domains, emails, exemptEmails, sampleLimit)

	if len(ret) == 0 {
		panic("no return value specified for CountUsersOutside")
	}

	var r0 int
	var r1 []string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string, []string, int) (int, []string, error)); ok {
		return rf(ctx, domains, emails, exemptEmails, sampleLimit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string, []string, int) int); ok {
		r0 = rf(ctx, domains, emails, exemptEmails, sampleLimit)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []string, []string, int) []string); ok {
		r1 = rf(ctx, domains, emails, exemptEmails, sampleLimit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, []string, []string, []string, int) error); ok {
		r2 = rf(ctx, domains, emails, exemptEmails, sampleLimit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockInstanceAuthAllowlistRepository_CountUsersOutside_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUsersOutside'
type MockInstanceAuthAllowlistRepository_CountUsersOutside_Call struct {
	*mock.Call
}

// CountUsersOutside is a helper method to define mock.On call
//   - ctx context.Context
//   - domains []string
//   - emails []string
//   - exemptEmails []string
//   - sampleLimit int
func (_e *MockInstanceAuthAllowlistRepository_Expecter) CountUsersOutside(ctx interface{}, domains interface{}, emails interface{}, exemptEmails interface{}, sampleLimit interface{}) *MockInstanceAuthAllowlistRepository_CountUsersOutside_Call {
	return &MockInstanceAuthAllowlistRepository_CountUsersOutside_Call{Call: _e.mock.On("CountUsersOutside", ctx, domains, emails, exemptEmails, sampleLimit)}
}

func (_c *MockInstanceAuthAllowlistRepository_CountUsersOutside_Call) Run(run func(ctx context.Context, domains []string, emails []string, exemptEmails []string, sampleLimit int)) *MockInstanceAuthAllowlistRepository_CountUsersOutside_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].([]string), args[3].([]string), args[4].(int))
	})
	return _c
}

func (_c *MockInstanceAuthAllowlistRepository_CountUsersOutside_Call) Return(count int, sample []string, err error) *MockInstanceAuthAllowlistRepository_CountUsersOutside_Call {
	_c.Call.Return(count, sample, err)
	return _c
}

func (_c *MockInstanceAuthAllowlistRepository_CountUsersOutside_Call) RunAndReturn(run func(context.Context, []string, []string, []string, int) (int, []string, error)) *MockInstanceAuthAllowlistRepository_CountUsersOutside_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAudited provides a mock function with given fields: ctx, actorUserID
func (_m *MockInstanceAuthAllowlistRepository) DeleteAudited(ctx context.Context, actorUserID *string) (bool, error) {
	ret := _m.Called(ctx, actorUserID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAudited")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (bool, error)); ok {
		return rf(ctx, actorUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) bool); ok {
		r0 = rf(ctx, actorUserID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, actorUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceAuthAllowlistRepository_DeleteAudited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAudited'
type MockInstanceAuthAllowlistRepository_DeleteAudited_Call struct {
	*mock.Call
}

// DeleteAudited is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID *string
func (_e *MockInstanceAuthAllowlistRepository_Expecter) DeleteAudited(ctx interface{}, actorUserID interface{}) *MockInstanceAuthAllowlistRepository_DeleteAudited_Call {
	return &MockInstanceAuthAllowlistRepository_DeleteAudited_Call{Call: _e.mock.On("DeleteAudited", ctx, actorUserID)}
}

func (_c *MockInstanceAuthAllowlistRepository_DeleteAudited_Call) Run(run func(ctx context.Context, actorUserID *string)) *MockInstanceAuthAllowlistRepository_DeleteAudited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string))
	})
	return _c
}

func (_c *MockInstanceAuthAllowlistRepository_DeleteAudited_Call) Return(deleted bool, err error) *MockInstanceAuthAllowlistRepository_DeleteAudited_Call {
	_c.Call.Return(deleted, err)
	return _c
}

func (_c *MockInstanceAuthAllowlistRepository_DeleteAudited_Call) RunAndReturn(run func(context.Context, *string) (bool, error)) *MockInstanceAuthAllowlistRepository_DeleteAudited_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx
func (_m *MockInstanceAuthAllowlistRepository) Get(ctx context.Context) (*models.InstanceAuthAllowlist, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.InstanceAuthAllowlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.InstanceAuthAllowlist, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.InstanceAuthAllowlist); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InstanceAuthAllowlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceAuthAllowlistRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInstanceAuthAllowlistRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstanceAuthAllowlistRepository_Expecter) Get(ctx interface{}) *MockInstanceAuthAllowlistRepository_Get_Call {
	return &MockInstanceAuthAllowlistRepository_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockInstanceAuthAllowlistRepository_Get_Call) Run(run func(ctx context.Context)) *MockInstanceAuthAllowlistRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInstanceAuthAllowlistRepository_Get_Call) Return(_a0 *models.InstanceAuthAllowlist, _a1 error) *MockInstanceAuthAllowlistRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInstanceAuthAllowlistRepository_Get_Call) RunAndReturn(run func(context.Context) (*models.InstanceAuthAllowlist, error)) *MockInstanceAuthAllowlistRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InsertIfAbsent provides a mock function with given fields: ctx, allowlist
func (_m *MockInstanceAuthAllowlistRepository) InsertIfAbsent(ctx context.Context, allowlist *models.InstanceAuthAllowlist) (bool, error) {
	ret := _m.Called(ctx, allowlist)

	if len(ret) == 0 {
		panic("no return value specified for InsertIfAbsent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.InstanceAuthAllowlist) (bool, error)); ok {
		return rf(ctx, allowlist)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.InstanceAuthAllowlist) bool); ok {
		r0 = rf(ctx, allowlist)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.InstanceAuthAllowlist) error); ok {
		r1 = rf(ctx, allowlist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceAuthAllowlistRepository_InsertIfAbsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertIfAbsent'
type MockInstanceAuthAllowlistRepository_InsertIfAbsent_Call struct {
	*mock.Call
}

// InsertIfAbsent is a helper method to define mock.On call
//   - ctx context.Context
//   - allowlist *models.InstanceAuthAllowlist
func (_e *MockInstanceAuthAllowlistRepository_Expecter) InsertIfAbsent(ctx interface{}, allowlist interface{}) *MockInstanceAuthAllowlistRepository_InsertIfAbsent_Call {
	return &MockInstanceAuthAllowlistRepository_InsertIfAbsent_Call{Call: _e.mock.On("InsertIfAbsent", ctx, allowlist)}
}

func (_c *MockInstanceAuthAllowlistRepository_InsertIfAbsent_Call) Run(run func(ctx context.Context, allowlist *models.InstanceAuthAllowlist)) *MockInstanceAuthAllowlistRepository_InsertIfAbsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.InstanceAuthAllowlist))
	})
	return _c
}

func (_c *MockInstanceAuthAllowlistRepository_InsertIfAbsent_Call) Return(inserted bool, err error) *MockInstanceAuthAllowlistRepository_InsertIfAbsent_Call {
	_c.Call.Return(inserted, err)
	return _c
}

func (_c *MockInstanceAuthAllowlistRepository_InsertIfAbsent_Call) RunAndReturn(run func(context.Context, *models.InstanceAuthAllowlist) (bool, error)) *MockInstanceAuthAllowlistRepository_InsertIfAbsent_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAudited provides a mock function with given fields: ctx, allowlist, actorUserID, expectedVersion
func (_m *MockInstanceAuthAllowlistRepository) UpsertAudited(ctx context.Context, allowlist *models.InstanceAuthAllowlist, actorUserID *string, expectedVersion *int64) error {
	ret := _m.Called(ctx, allowlist, actorUserID, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAudited")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.InstanceAuthAllowlist, *string, *int64) error); ok {
		r0 = rf(ctx, allowlist, actorUserID, expectedVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceAuthAllowlistRepository_UpsertAudited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAudited'
type MockInstanceAuthAllowlistRepository_UpsertAudited_Call struct {
	*mock.Call
}

// UpsertAudited is a helper method to define mock.On call
//   - ctx context.Context
//   - allowlist *models.InstanceAuthAllowlist
//   - actorUserID *string
//   - expectedVersion *int64
func (_e *MockInstanceAuthAllowlistRepository_Expecter) UpsertAudited(ctx interface{}, allowlist interface{}, actorUserID interface{}, expectedVersion interface{}) *MockInstanceAuthAllowlistRepository_UpsertAudited_Call {
	return &MockInstanceAuthAllowlistRepository_UpsertAudited_Call{Call: _e.mock.On("UpsertAudited", ctx, allowlist, actorUserID, expectedVersion)}
}

func (_c *MockInstanceAuthAllowlistRepository_UpsertAudited_Call) Run(run func(ctx context.Context, allowlist *models.InstanceAuthAllowlist, actorUserID *string, expectedVersion *int64)) *MockInstanceAuthAllowlistRepository_UpsertAudited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.InstanceAuthAllowlist), args[2].(*string), args[3].(*int64))
	})
	return _c
}

func (_c *MockInstanceAuthAllowlistRepository_UpsertAudited_Call) Return(_a0 error) *MockInstanceAuthAllowlistRepository_UpsertAudited_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceAuthAllowlistRepository_UpsertAudited_Call) RunAndReturn(run func(context.Context, *models.InstanceAuthAllowlist, *string, *int64) error) *MockInstanceAuthAllowlistRepository_UpsertAudited_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstanceAuthAllowlistRepository creates a new instance of MockInstanceAuthAllowlistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstanceAuthAllowlistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstanceAuthAllowlistRepository {
	mock := &MockInstanceAuthAllowlistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
