// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockResourceUsageRepository is an autogenerated mock type for the ResourceUsageRepository type
type MockResourceUsageRepository struct {
	mock.Mock
}

type MockResourceUsageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceUsageRepository) EXPECT() *MockResourceUsageRepository_Expecter {
	return &MockResourceUsageRepository_Expecter{mock: &_m.Mock}
}

// DecrementUsage provides a mock function with given fields: ctx, userID, resourceType, periodStart, periodEnd
func (_m *MockResourceUsageRepository) DecrementUsage(ctx context.Context, userID string, resourceType string, periodStart time.Time, periodEnd time.Time) error {
	ret := _m.Called(ctx, userID, resourceType, periodStart, periodEnd)

	if len(ret) == 0 {
		panic("no return value specified for DecrementUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r0 = rf(ctx, userID, resourceType, periodStart, periodEnd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResourceUsageRepository_DecrementUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementUsage'
type MockResourceUsageRepository_DecrementUsage_Call struct {
	*mock.Call
}

// DecrementUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - resourceType string
//   - periodStart time.Time
//   - periodEnd time.Time
func (_e *MockResourceUsageRepository_Expecter) DecrementUsage(ctx interface{}, userID interface{}, resourceType interface{}, periodStart interface{}, periodEnd interface{}) *MockResourceUsageRepository_DecrementUsage_Call {
	return &MockResourceUsageRepository_DecrementUsage_Call{Call: _e.mock.On("DecrementUsage", ctx, userID, resourceType, periodStart, periodEnd)}
}

func (_c *MockResourceUsageRepository_DecrementUsage_Call) Run(run func(ctx context.Context, userID string, resourceType string, periodStart time.Time, periodEnd time.Time)) *MockResourceUsageRepository_DecrementUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockResourceUsageRepository_DecrementUsage_Call) Return(_a0 error) *MockResourceUsageRepository_DecrementUsage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceUsageRepository_DecrementUsage_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) error) *MockResourceUsageRepository_DecrementUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceCounts provides a mock function with given fields: ctx, userID, periodStart, periodEnd
func (_m *MockResourceUsageRepository) GetResourceCounts(ctx context.Context, userID string, periodStart time.Time, periodEnd time.Time) (map[string]int, error) {
	ret := _m.Called(ctx, userID, periodStart, periodEnd)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceCounts")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (map[string]int, error)); ok {
		return rf(ctx, userID, periodStart, periodEnd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) map[string]int); ok {
		r0 = rf(ctx, userID, periodStart, periodEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, periodStart, periodEnd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceUsageRepository_GetResourceCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceCounts'
type MockResourceUsageRepository_GetResourceCounts_Call struct {
	*mock.Call
}

// GetResourceCounts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - periodStart time.Time
//   - periodEnd time.Time
func (_e *MockResourceUsageRepository_Expecter) GetResourceCounts(ctx interface{}, userID interface{}, periodStart interface{}, periodEnd interface{}) *MockResourceUsageRepository_GetResourceCounts_Call {
	return &MockResourceUsageRepository_GetResourceCounts_Call{Call: _e.mock.On("GetResourceCounts", ctx, userID, periodStart, periodEnd)}
}

func (_c *MockResourceUsageRepository_GetResourceCounts_Call) Run(run func(ctx context.Context, userID string, periodStart time.Time, periodEnd time.Time)) *MockResourceUsageRepository_GetResourceCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockResourceUsageRepository_GetResourceCounts_Call) Return(_a0 map[string]int, _a1 error) *MockResourceUsageRepository_GetResourceCounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceUsageRepository_GetResourceCounts_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) (map[string]int, error)) *MockResourceUsageRepository_GetResourceCounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsageCount provides a mock function with given fields: ctx, userID, resourceType, periodStart, periodEnd
func (_m *MockResourceUsageRepository) GetUsageCount(ctx context.Context, userID string, resourceType string, periodStart time.Time, periodEnd time.Time) (int, error) {
	ret := _m.Called(ctx, userID, resourceType, periodStart, periodEnd)

	if len(ret) == 0 {
		panic("no return value specified for GetUsageCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) (int, error)); ok {
		return rf(ctx, userID, resourceType, periodStart, periodEnd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) int); ok {
		r0 = rf(ctx, userID, resourceType, periodStart, periodEnd)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, resourceType, periodStart, periodEnd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceUsageRepository_GetUsageCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsageCount'
type MockResourceUsageRepository_GetUsageCount_Call struct {
	*mock.Call
}

// GetUsageCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - resourceType string
//   - periodStart time.Time
//   - periodEnd time.Time
func (_e *MockResourceUsageRepository_Expecter) GetUsageCount(ctx interface{}, userID interface{}, resourceType interface{}, periodStart interface{}, periodEnd interface{}) *MockResourceUsageRepository_GetUsageCount_Call {
	return &MockResourceUsageRepository_GetUsageCount_Call{Call: _e.mock.On("GetUsageCount", ctx, userID, resourceType, periodStart, periodEnd)}
}

func (_c *MockResourceUsageRepository_GetUsageCount_Call) Run(run func(ctx context.Context, userID string, resourceType string, periodStart time.Time, periodEnd time.Time)) *MockResourceUsageRepository_GetUsageCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockResourceUsageRepository_GetUsageCount_Call) Return(_a0 int, _a1 error) *MockResourceUsageRepository_GetUsageCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceUsageRepository_GetUsageCount_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) (int, error)) *MockResourceUsageRepository_GetUsageCount_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementUsage provides a mock function with given fields: ctx, userID, resourceType, periodStart, periodEnd
func (_m *MockResourceUsageRepository) IncrementUsage(ctx context.Context, userID string, resourceType string, periodStart time.Time, periodEnd time.Time) error {
	ret := _m.Called(ctx, userID, resourceType, periodStart, periodEnd)

	if len(ret) == 0 {
		panic("no return value specified for IncrementUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r0 = rf(ctx, userID, resourceType, periodStart, periodEnd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResourceUsageRepository_IncrementUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementUsage'
type MockResourceUsageRepository_IncrementUsage_Call struct {
	*mock.Call
}

// IncrementUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - resourceType string
//   - periodStart time.Time
//   - periodEnd time.Time
func (_e *MockResourceUsageRepository_Expecter) IncrementUsage(ctx interface{}, userID interface{}, resourceType interface{}, periodStart interface{}, periodEnd interface{}) *MockResourceUsageRepository_IncrementUsage_Call {
	return &MockResourceUsageRepository_IncrementUsage_Call{Call: _e.mock.On("IncrementUsage", ctx, userID, resourceType, periodStart, periodEnd)}
}

func (_c *MockResourceUsageRepository_IncrementUsage_Call) Run(run func(ctx context.Context, userID string, resourceType string, periodStart time.Time, periodEnd time.Time)) *MockResourceUsageRepository_IncrementUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockResourceUsageRepository_IncrementUsage_Call) Return(_a0 error) *MockResourceUsageRepository_IncrementUsage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceUsageRepository_IncrementUsage_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) error) *MockResourceUsageRepository_IncrementUsage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResourceUsageRepository creates a new instance of MockResourceUsageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceUsageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceUsageRepository {
	mock := &MockResourceUsageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
