// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"

	repositories "github.com/vibexp/vibexp/internal/repositories"
)

// MockPromptGalleryRepository is an autogenerated mock type for the PromptGalleryRepository type
type MockPromptGalleryRepository struct {
	mock.Mock
}

type MockPromptGalleryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPromptGalleryRepository) EXPECT() *MockPromptGalleryRepository_Expecter {
	return &MockPromptGalleryRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, promptID
func (_m *MockPromptGalleryRepository) GetByID(ctx context.Context, promptID string) (*models.PromptGalleryTemplate, error) {
	ret := _m.Called(ctx, promptID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.PromptGalleryTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PromptGalleryTemplate, error)); ok {
		return rf(ctx, promptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PromptGalleryTemplate); ok {
		r0 = rf(ctx, promptID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PromptGalleryTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, promptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPromptGalleryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPromptGalleryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - promptID string
func (_e *MockPromptGalleryRepository_Expecter) GetByID(ctx interface{}, promptID interface{}) *MockPromptGalleryRepository_GetByID_Call {
	return &MockPromptGalleryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, promptID)}
}

func (_c *MockPromptGalleryRepository_GetByID_Call) Run(run func(ctx context.Context, promptID string)) *MockPromptGalleryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPromptGalleryRepository_GetByID_Call) Return(_a0 *models.PromptGalleryTemplate, _a1 error) *MockPromptGalleryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPromptGalleryRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*models.PromptGalleryTemplate, error)) *MockPromptGalleryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategories provides a mock function with given fields: ctx
func (_m *MockPromptGalleryRepository) GetCategories(ctx context.Context) ([]models.PromptGalleryCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCategories")
	}

	var r0 []models.PromptGalleryCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.PromptGalleryCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.PromptGalleryCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PromptGalleryCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPromptGalleryRepository_GetCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategories'
type MockPromptGalleryRepository_GetCategories_Call struct {
	*mock.Call
}

// GetCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPromptGalleryRepository_Expecter) GetCategories(ctx interface{}) *MockPromptGalleryRepository_GetCategories_Call {
	return &MockPromptGalleryRepository_GetCategories_Call{Call: _e.mock.On("GetCategories", ctx)}
}

func (_c *MockPromptGalleryRepository_GetCategories_Call) Run(run func(ctx context.Context)) *MockPromptGalleryRepository_GetCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPromptGalleryRepository_GetCategories_Call) Return(_a0 []models.PromptGalleryCategory, _a1 error) *MockPromptGalleryRepository_GetCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPromptGalleryRepository_GetCategories_Call) RunAndReturn(run func(context.Context) ([]models.PromptGalleryCategory, error)) *MockPromptGalleryRepository_GetCategories_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filters
func (_m *MockPromptGalleryRepository) List(ctx context.Context, filters repositories.PromptGalleryFilters) ([]models.PromptGalleryTemplate, int, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.PromptGalleryTemplate
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.PromptGalleryFilters) ([]models.PromptGalleryTemplate, int, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repositories.PromptGalleryFilters) []models.PromptGalleryTemplate); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PromptGalleryTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repositories.PromptGalleryFilters) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repositories.PromptGalleryFilters) error); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPromptGalleryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPromptGalleryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filters repositories.PromptGalleryFilters
func (_e *MockPromptGalleryRepository_Expecter) List(ctx interface{}, filters interface{}) *MockPromptGalleryRepository_List_Call {
	return &MockPromptGalleryRepository_List_Call{Call: _e.mock.On("List", ctx, filters)}
}

func (_c *MockPromptGalleryRepository_List_Call) Run(run func(ctx context.Context, filters repositories.PromptGalleryFilters)) *MockPromptGalleryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.PromptGalleryFilters))
	})
	return _c
}

func (_c *MockPromptGalleryRepository_List_Call) Return(_a0 []models.PromptGalleryTemplate, _a1 int, _a2 error) *MockPromptGalleryRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPromptGalleryRepository_List_Call) RunAndReturn(run func(context.Context, repositories.PromptGalleryFilters) ([]models.PromptGalleryTemplate, int, error)) *MockPromptGalleryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPromptGalleryRepository creates a new instance of MockPromptGalleryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPromptGalleryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPromptGalleryRepository {
	mock := &MockPromptGalleryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
