// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/vibexp/vibexp/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockEmbeddingBackfillRepository is an autogenerated mock type for the EmbeddingBackfillRepository type
type MockEmbeddingBackfillRepository struct {
	mock.Mock
}

type MockEmbeddingBackfillRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingBackfillRepository) EXPECT() *MockEmbeddingBackfillRepository_Expecter {
	return &MockEmbeddingBackfillRepository_Expecter{mock: &_m.Mock}
}

// ListEntities provides a mock function with given fields: ctx, entityType, modelID, missingOnly, limit, offset
func (_m *MockEmbeddingBackfillRepository) ListEntities(ctx context.Context, entityType string, modelID string, missingOnly bool, limit int, offset int) ([]models.BackfillEntity, error) {
	ret := _m.Called(ctx, entityType, modelID, missingOnly, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListEntities")
	}

	var r0 []models.BackfillEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool, int, int) ([]models.BackfillEntity, error)); ok {
		return rf(ctx, entityType, modelID, missingOnly, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool, int, int) []models.BackfillEntity); ok {
		r0 = rf(ctx, entityType, modelID, missingOnly, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BackfillEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool, int, int) error); ok {
		r1 = rf(ctx, entityType, modelID, missingOnly, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingBackfillRepository_ListEntities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEntities'
type MockEmbeddingBackfillRepository_ListEntities_Call struct {
	*mock.Call
}

// ListEntities is a helper method to define mock.On call
//   - ctx context.Context
//   - entityType string
//   - modelID string
//   - missingOnly bool
//   - limit int
//   - offset int
func (_e *MockEmbeddingBackfillRepository_Expecter) ListEntities(ctx interface{}, entityType interface{}, modelID interface{}, missingOnly interface{}, limit interface{}, offset interface{}) *MockEmbeddingBackfillRepository_ListEntities_Call {
	return &MockEmbeddingBackfillRepository_ListEntities_Call{Call: _e.mock.On("ListEntities", ctx, entityType, modelID, missingOnly, limit, offset)}
}

func (_c *MockEmbeddingBackfillRepository_ListEntities_Call) Run(run func(ctx context.Context, entityType string, modelID string, missingOnly bool, limit int, offset int)) *MockEmbeddingBackfillRepository_ListEntities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockEmbeddingBackfillRepository_ListEntities_Call) Return(_a0 []models.BackfillEntity, _a1 error) *MockEmbeddingBackfillRepository_ListEntities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingBackfillRepository_ListEntities_Call) RunAndReturn(run func(context.Context, string, string, bool, int, int) ([]models.BackfillEntity, error)) *MockEmbeddingBackfillRepository_ListEntities_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingBackfillRepository creates a new instance of MockEmbeddingBackfillRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingBackfillRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingBackfillRepository {
	mock := &MockEmbeddingBackfillRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
