// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockRelationRepository is an autogenerated mock type for the RelationRepository type
type MockRelationRepository struct {
	mock.Mock
}

type MockRelationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelationRepository) EXPECT() *MockRelationRepository_Expecter {
	return &MockRelationRepository_Expecter{mock: &_m.Mock}
}

// Confirm provides a mock function with given fields: ctx, teamID, id, confirmedBy
func (_m *MockRelationRepository) Confirm(ctx context.Context, teamID string, id string, confirmedBy string) (*models.Relation, error) {
	ret := _m.Called(ctx, teamID, id, confirmedBy)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 *models.Relation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.Relation, error)); ok {
		return rf(ctx, teamID, id, confirmedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.Relation); ok {
		r0 = rf(ctx, teamID, id, confirmedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Relation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, teamID, id, confirmedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRelationRepository_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockRelationRepository_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - id string
//   - confirmedBy string
func (_e *MockRelationRepository_Expecter) Confirm(ctx interface{}, teamID interface{}, id interface{}, confirmedBy interface{}) *MockRelationRepository_Confirm_Call {
	return &MockRelationRepository_Confirm_Call{Call: _e.mock.On("Confirm", ctx, teamID, id, confirmedBy)}
}

func (_c *MockRelationRepository_Confirm_Call) Run(run func(ctx context.Context, teamID string, id string, confirmedBy string)) *MockRelationRepository_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRelationRepository_Confirm_Call) Return(_a0 *models.Relation, _a1 error) *MockRelationRepository_Confirm_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRelationRepository_Confirm_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.Relation, error)) *MockRelationRepository_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, relation
func (_m *MockRelationRepository) Create(ctx context.Context, relation *models.Relation) (*models.Relation, error) {
	ret := _m.Called(ctx, relation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Relation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Relation) (*models.Relation, error)); ok {
		return rf(ctx, relation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Relation) *models.Relation); ok {
		r0 = rf(ctx, relation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Relation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Relation) error); ok {
		r1 = rf(ctx, relation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRelationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRelationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - relation *models.Relation
func (_e *MockRelationRepository_Expecter) Create(ctx interface{}, relation interface{}) *MockRelationRepository_Create_Call {
	return &MockRelationRepository_Create_Call{Call: _e.mock.On("Create", ctx, relation)}
}

func (_c *MockRelationRepository_Create_Call) Run(run func(ctx context.Context, relation *models.Relation)) *MockRelationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Relation))
	})
	return _c
}

func (_c *MockRelationRepository_Create_Call) Return(_a0 *models.Relation, _a1 error) *MockRelationRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRelationRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Relation) (*models.Relation, error)) *MockRelationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, teamID, id
func (_m *MockRelationRepository) Delete(ctx context.Context, teamID string, id string) error {
	ret := _m.Called(ctx, teamID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, teamID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRelationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRelationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - id string
func (_e *MockRelationRepository_Expecter) Delete(ctx interface{}, teamID interface{}, id interface{}) *MockRelationRepository_Delete_Call {
	return &MockRelationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, teamID, id)}
}

func (_c *MockRelationRepository_Delete_Call) Run(run func(ctx context.Context, teamID string, id string)) *MockRelationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRelationRepository_Delete_Call) Return(_a0 error) *MockRelationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRelationRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRelationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByResource provides a mock function with given fields: ctx, teamID, resourceType, resourceID
func (_m *MockRelationRepository) DeleteByResource(ctx context.Context, teamID string, resourceType string, resourceID string) (int64, error) {
	ret := _m.Called(ctx, teamID, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByResource")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (int64, error)); ok {
		return rf(ctx, teamID, resourceType, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) int64); ok {
		r0 = rf(ctx, teamID, resourceType, resourceID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, teamID, resourceType, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRelationRepository_DeleteByResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByResource'
type MockRelationRepository_DeleteByResource_Call struct {
	*mock.Call
}

// DeleteByResource is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - resourceType string
//   - resourceID string
func (_e *MockRelationRepository_Expecter) DeleteByResource(ctx interface{}, teamID interface{}, resourceType interface{}, resourceID interface{}) *MockRelationRepository_DeleteByResource_Call {
	return &MockRelationRepository_DeleteByResource_Call{Call: _e.mock.On("DeleteByResource", ctx, teamID, resourceType, resourceID)}
}

func (_c *MockRelationRepository_DeleteByResource_Call) Run(run func(ctx context.Context, teamID string, resourceType string, resourceID string)) *MockRelationRepository_DeleteByResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRelationRepository_DeleteByResource_Call) Return(_a0 int64, _a1 error) *MockRelationRepository_DeleteByResource_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRelationRepository_DeleteByResource_Call) RunAndReturn(run func(context.Context, string, string, string) (int64, error)) *MockRelationRepository_DeleteByResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, teamID, id
func (_m *MockRelationRepository) GetByID(ctx context.Context, teamID string, id string) (*models.Relation, error) {
	ret := _m.Called(ctx, teamID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Relation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Relation, error)); ok {
		return rf(ctx, teamID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Relation); ok {
		r0 = rf(ctx, teamID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Relation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, teamID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRelationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRelationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - id string
func (_e *MockRelationRepository_Expecter) GetByID(ctx interface{}, teamID interface{}, id interface{}) *MockRelationRepository_GetByID_Call {
	return &MockRelationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, teamID, id)}
}

func (_c *MockRelationRepository_GetByID_Call) Run(run func(ctx context.Context, teamID string, id string)) *MockRelationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRelationRepository_GetByID_Call) Return(_a0 *models.Relation, _a1 error) *MockRelationRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRelationRepository_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*models.Relation, error)) *MockRelationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByResource provides a mock function with given fields: ctx, teamID, resourceType, resourceID, page, limit
func (_m *MockRelationRepository) ListByResource(ctx context.Context, teamID string, resourceType string, resourceID string, page int, limit int) ([]models.RelatedResource, int, error) {
	ret := _m.Called(ctx, teamID, resourceType, resourceID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByResource")
	}

	var r0 []models.RelatedResource
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) ([]models.RelatedResource, int, error)); ok {
		return rf(ctx, teamID, resourceType, resourceID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) []models.RelatedResource); ok {
		r0 = rf(ctx, teamID, resourceType, resourceID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RelatedResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, int) int); ok {
		r1 = rf(ctx, teamID, resourceType, resourceID, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, int, int) error); ok {
		r2 = rf(ctx, teamID, resourceType, resourceID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRelationRepository_ListByResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByResource'
type MockRelationRepository_ListByResource_Call struct {
	*mock.Call
}

// ListByResource is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - resourceType string
//   - resourceID string
//   - page int
//   - limit int
func (_e *MockRelationRepository_Expecter) ListByResource(ctx interface{}, teamID interface{}, resourceType interface{}, resourceID interface{}, page interface{}, limit interface{}) *MockRelationRepository_ListByResource_Call {
	return &MockRelationRepository_ListByResource_Call{Call: _e.mock.On("ListByResource", ctx, teamID, resourceType, resourceID, page, limit)}
}

func (_c *MockRelationRepository_ListByResource_Call) Run(run func(ctx context.Context, teamID string, resourceType string, resourceID string, page int, limit int)) *MockRelationRepository_ListByResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockRelationRepository_ListByResource_Call) Return(_a0 []models.RelatedResource, _a1 int, _a2 error) *MockRelationRepository_ListByResource_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRelationRepository_ListByResource_Call) RunAndReturn(run func(context.Context, string, string, string, int, int) ([]models.RelatedResource, int, error)) *MockRelationRepository_ListByResource_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceProjectID provides a mock function with given fields: ctx, teamID, resourceType, resourceID
func (_m *MockRelationRepository) ResourceProjectID(ctx context.Context, teamID string, resourceType string, resourceID string) (string, bool, error) {
	ret := _m.Called(ctx, teamID, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for ResourceProjectID")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, bool, error)); ok {
		return rf(ctx, teamID, resourceType, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, teamID, resourceType, resourceID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) bool); ok {
		r1 = rf(ctx, teamID, resourceType, resourceID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, teamID, resourceType, resourceID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRelationRepository_ResourceProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceProjectID'
type MockRelationRepository_ResourceProjectID_Call struct {
	*mock.Call
}

// ResourceProjectID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - resourceType string
//   - resourceID string
func (_e *MockRelationRepository_Expecter) ResourceProjectID(ctx interface{}, teamID interface{}, resourceType interface{}, resourceID interface{}) *MockRelationRepository_ResourceProjectID_Call {
	return &MockRelationRepository_ResourceProjectID_Call{Call: _e.mock.On("ResourceProjectID", ctx, teamID, resourceType, resourceID)}
}

func (_c *MockRelationRepository_ResourceProjectID_Call) Run(run func(ctx context.Context, teamID string, resourceType string, resourceID string)) *MockRelationRepository_ResourceProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRelationRepository_ResourceProjectID_Call) Return(projectID string, exists bool, err error) *MockRelationRepository_ResourceProjectID_Call {
	_c.Call.Return(projectID, exists, err)
	return _c
}

func (_c *MockRelationRepository_ResourceProjectID_Call) RunAndReturn(run func(context.Context, string, string, string) (string, bool, error)) *MockRelationRepository_ResourceProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRelationRepository creates a new instance of MockRelationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelationRepository {
	mock := &MockRelationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
