// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockTeamSearchSettingsRepository is an autogenerated mock type for the TeamSearchSettingsRepository type
type MockTeamSearchSettingsRepository struct {
	mock.Mock
}

type MockTeamSearchSettingsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamSearchSettingsRepository) EXPECT() *MockTeamSearchSettingsRepository_Expecter {
	return &MockTeamSearchSettingsRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, teamID
func (_m *MockTeamSearchSettingsRepository) Delete(ctx context.Context, teamID string) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamSearchSettingsRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTeamSearchSettingsRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockTeamSearchSettingsRepository_Expecter) Delete(ctx interface{}, teamID interface{}) *MockTeamSearchSettingsRepository_Delete_Call {
	return &MockTeamSearchSettingsRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, teamID)}
}

func (_c *MockTeamSearchSettingsRepository_Delete_Call) Run(run func(ctx context.Context, teamID string)) *MockTeamSearchSettingsRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamSearchSettingsRepository_Delete_Call) Return(_a0 error) *MockTeamSearchSettingsRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamSearchSettingsRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockTeamSearchSettingsRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, teamID
func (_m *MockTeamSearchSettingsRepository) Get(ctx context.Context, teamID string) (*models.TeamSearchSettings, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.TeamSearchSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.TeamSearchSettings, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.TeamSearchSettings); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamSearchSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamSearchSettingsRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTeamSearchSettingsRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockTeamSearchSettingsRepository_Expecter) Get(ctx interface{}, teamID interface{}) *MockTeamSearchSettingsRepository_Get_Call {
	return &MockTeamSearchSettingsRepository_Get_Call{Call: _e.mock.On("Get", ctx, teamID)}
}

func (_c *MockTeamSearchSettingsRepository_Get_Call) Run(run func(ctx context.Context, teamID string)) *MockTeamSearchSettingsRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamSearchSettingsRepository_Get_Call) Return(_a0 *models.TeamSearchSettings, _a1 error) *MockTeamSearchSettingsRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamSearchSettingsRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*models.TeamSearchSettings, error)) *MockTeamSearchSettingsRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, settings
func (_m *MockTeamSearchSettingsRepository) Upsert(ctx context.Context, settings *models.TeamSearchSettings) error {
	ret := _m.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TeamSearchSettings) error); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamSearchSettingsRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockTeamSearchSettingsRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.TeamSearchSettings
func (_e *MockTeamSearchSettingsRepository_Expecter) Upsert(ctx interface{}, settings interface{}) *MockTeamSearchSettingsRepository_Upsert_Call {
	return &MockTeamSearchSettingsRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, settings)}
}

func (_c *MockTeamSearchSettingsRepository_Upsert_Call) Run(run func(ctx context.Context, settings *models.TeamSearchSettings)) *MockTeamSearchSettingsRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.TeamSearchSettings))
	})
	return _c
}

func (_c *MockTeamSearchSettingsRepository_Upsert_Call) Return(_a0 error) *MockTeamSearchSettingsRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamSearchSettingsRepository_Upsert_Call) RunAndReturn(run func(context.Context, *models.TeamSearchSettings) error) *MockTeamSearchSettingsRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamSearchSettingsRepository creates a new instance of MockTeamSearchSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamSearchSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamSearchSettingsRepository {
	mock := &MockTeamSearchSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
