// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"

	repositories "github.com/vibexp/vibexp/internal/repositories"
)

// MockInstanceAISummarySettingsRepository is an autogenerated mock type for the InstanceAISummarySettingsRepository type
type MockInstanceAISummarySettingsRepository struct {
	mock.Mock
}

type MockInstanceAISummarySettingsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstanceAISummarySettingsRepository) EXPECT() *MockInstanceAISummarySettingsRepository_Expecter {
	return &MockInstanceAISummarySettingsRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx
func (_m *MockInstanceAISummarySettingsRepository) Delete(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceAISummarySettingsRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInstanceAISummarySettingsRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstanceAISummarySettingsRepository_Expecter) Delete(ctx interface{}) *MockInstanceAISummarySettingsRepository_Delete_Call {
	return &MockInstanceAISummarySettingsRepository_Delete_Call{Call: _e.mock.On("Delete", ctx)}
}

func (_c *MockInstanceAISummarySettingsRepository_Delete_Call) Run(run func(ctx context.Context)) *MockInstanceAISummarySettingsRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_Delete_Call) Return(_a0 error) *MockInstanceAISummarySettingsRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_Delete_Call) RunAndReturn(run func(context.Context) error) *MockInstanceAISummarySettingsRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAudited provides a mock function with given fields: ctx, audit
func (_m *MockInstanceAISummarySettingsRepository) DeleteAudited(ctx context.Context, audit repositories.InstanceAISummarySettingsAuditFunc) (bool, error) {
	ret := _m.Called(ctx, audit)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAudited")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repositories.InstanceAISummarySettingsAuditFunc) (bool, error)); ok {
		return rf(ctx, audit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repositories.InstanceAISummarySettingsAuditFunc) bool); ok {
		r0 = rf(ctx, audit)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repositories.InstanceAISummarySettingsAuditFunc) error); ok {
		r1 = rf(ctx, audit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceAISummarySettingsRepository_DeleteAudited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAudited'
type MockInstanceAISummarySettingsRepository_DeleteAudited_Call struct {
	*mock.Call
}

// DeleteAudited is a helper method to define mock.On call
//   - ctx context.Context
//   - audit repositories.InstanceAISummarySettingsAuditFunc
func (_e *MockInstanceAISummarySettingsRepository_Expecter) DeleteAudited(ctx interface{}, audit interface{}) *MockInstanceAISummarySettingsRepository_DeleteAudited_Call {
	return &MockInstanceAISummarySettingsRepository_DeleteAudited_Call{Call: _e.mock.On("DeleteAudited", ctx, audit)}
}

func (_c *MockInstanceAISummarySettingsRepository_DeleteAudited_Call) Run(run func(ctx context.Context, audit repositories.InstanceAISummarySettingsAuditFunc)) *MockInstanceAISummarySettingsRepository_DeleteAudited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositories.InstanceAISummarySettingsAuditFunc))
	})
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_DeleteAudited_Call) Return(deleted bool, err error) *MockInstanceAISummarySettingsRepository_DeleteAudited_Call {
	_c.Call.Return(deleted, err)
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_DeleteAudited_Call) RunAndReturn(run func(context.Context, repositories.InstanceAISummarySettingsAuditFunc) (bool, error)) *MockInstanceAISummarySettingsRepository_DeleteAudited_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx
func (_m *MockInstanceAISummarySettingsRepository) Get(ctx context.Context) (*models.InstanceAISummarySettings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.InstanceAISummarySettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.InstanceAISummarySettings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.InstanceAISummarySettings); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InstanceAISummarySettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceAISummarySettingsRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInstanceAISummarySettingsRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstanceAISummarySettingsRepository_Expecter) Get(ctx interface{}) *MockInstanceAISummarySettingsRepository_Get_Call {
	return &MockInstanceAISummarySettingsRepository_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockInstanceAISummarySettingsRepository_Get_Call) Run(run func(ctx context.Context)) *MockInstanceAISummarySettingsRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_Get_Call) Return(_a0 *models.InstanceAISummarySettings, _a1 error) *MockInstanceAISummarySettingsRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_Get_Call) RunAndReturn(run func(context.Context) (*models.InstanceAISummarySettings, error)) *MockInstanceAISummarySettingsRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InsertIfAbsent provides a mock function with given fields: ctx, settings
func (_m *MockInstanceAISummarySettingsRepository) InsertIfAbsent(ctx context.Context, settings *models.InstanceAISummarySettings) (bool, error) {
	ret := _m.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for InsertIfAbsent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.InstanceAISummarySettings) (bool, error)); ok {
		return rf(ctx, settings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.InstanceAISummarySettings) bool); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.InstanceAISummarySettings) error); ok {
		r1 = rf(ctx, settings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceAISummarySettingsRepository_InsertIfAbsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertIfAbsent'
type MockInstanceAISummarySettingsRepository_InsertIfAbsent_Call struct {
	*mock.Call
}

// InsertIfAbsent is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.InstanceAISummarySettings
func (_e *MockInstanceAISummarySettingsRepository_Expecter) InsertIfAbsent(ctx interface{}, settings interface{}) *MockInstanceAISummarySettingsRepository_InsertIfAbsent_Call {
	return &MockInstanceAISummarySettingsRepository_InsertIfAbsent_Call{Call: _e.mock.On("InsertIfAbsent", ctx, settings)}
}

func (_c *MockInstanceAISummarySettingsRepository_InsertIfAbsent_Call) Run(run func(ctx context.Context, settings *models.InstanceAISummarySettings)) *MockInstanceAISummarySettingsRepository_InsertIfAbsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.InstanceAISummarySettings))
	})
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_InsertIfAbsent_Call) Return(inserted bool, err error) *MockInstanceAISummarySettingsRepository_InsertIfAbsent_Call {
	_c.Call.Return(inserted, err)
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_InsertIfAbsent_Call) RunAndReturn(run func(context.Context, *models.InstanceAISummarySettings) (bool, error)) *MockInstanceAISummarySettingsRepository_InsertIfAbsent_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, settings
func (_m *MockInstanceAISummarySettingsRepository) Upsert(ctx context.Context, settings *models.InstanceAISummarySettings) error {
	ret := _m.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.InstanceAISummarySettings) error); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceAISummarySettingsRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockInstanceAISummarySettingsRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.InstanceAISummarySettings
func (_e *MockInstanceAISummarySettingsRepository_Expecter) Upsert(ctx interface{}, settings interface{}) *MockInstanceAISummarySettingsRepository_Upsert_Call {
	return &MockInstanceAISummarySettingsRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, settings)}
}

func (_c *MockInstanceAISummarySettingsRepository_Upsert_Call) Run(run func(ctx context.Context, settings *models.InstanceAISummarySettings)) *MockInstanceAISummarySettingsRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.InstanceAISummarySettings))
	})
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_Upsert_Call) Return(_a0 error) *MockInstanceAISummarySettingsRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_Upsert_Call) RunAndReturn(run func(context.Context, *models.InstanceAISummarySettings) error) *MockInstanceAISummarySettingsRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAudited provides a mock function with given fields: ctx, settings, audit
func (_m *MockInstanceAISummarySettingsRepository) UpsertAudited(ctx context.Context, settings *models.InstanceAISummarySettings, audit repositories.InstanceAISummarySettingsAuditFunc) error {
	ret := _m.Called(ctx, settings, audit)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAudited")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.InstanceAISummarySettings, repositories.InstanceAISummarySettingsAuditFunc) error); ok {
		r0 = rf(ctx, settings, audit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceAISummarySettingsRepository_UpsertAudited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAudited'
type MockInstanceAISummarySettingsRepository_UpsertAudited_Call struct {
	*mock.Call
}

// UpsertAudited is a helper method to define mock.On call
//   - ctx context.Context
//   - settings *models.InstanceAISummarySettings
//   - audit repositories.InstanceAISummarySettingsAuditFunc
func (_e *MockInstanceAISummarySettingsRepository_Expecter) UpsertAudited(ctx interface{}, settings interface{}, audit interface{}) *MockInstanceAISummarySettingsRepository_UpsertAudited_Call {
	return &MockInstanceAISummarySettingsRepository_UpsertAudited_Call{Call: _e.mock.On("UpsertAudited", ctx, settings, audit)}
}

func (_c *MockInstanceAISummarySettingsRepository_UpsertAudited_Call) Run(run func(ctx context.Context, settings *models.InstanceAISummarySettings, audit repositories.InstanceAISummarySettingsAuditFunc)) *MockInstanceAISummarySettingsRepository_UpsertAudited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.InstanceAISummarySettings), args[2].(repositories.InstanceAISummarySettingsAuditFunc))
	})
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_UpsertAudited_Call) Return(_a0 error) *MockInstanceAISummarySettingsRepository_UpsertAudited_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceAISummarySettingsRepository_UpsertAudited_Call) RunAndReturn(run func(context.Context, *models.InstanceAISummarySettings, repositories.InstanceAISummarySettingsAuditFunc) error) *MockInstanceAISummarySettingsRepository_UpsertAudited_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstanceAISummarySettingsRepository creates a new instance of MockInstanceAISummarySettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstanceAISummarySettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstanceAISummarySettingsRepository {
	mock := &MockInstanceAISummarySettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
