// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/vibexp/vibexp/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockAgentCardFetcherInterface is an autogenerated mock type for the AgentCardFetcherInterface type
type MockAgentCardFetcherInterface struct {
	mock.Mock
}

type MockAgentCardFetcherInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentCardFetcherInterface) EXPECT() *MockAgentCardFetcherInterface_Expecter {
	return &MockAgentCardFetcherInterface_Expecter{mock: &_m.Mock}
}

// FetchAgentCard provides a mock function with given fields: ctx, cardURL
func (_m *MockAgentCardFetcherInterface) FetchAgentCard(ctx context.Context, cardURL string) (*models.AgentCard, error) {
	ret := _m.Called(ctx, cardURL)

	if len(ret) == 0 {
		panic("no return value specified for FetchAgentCard")
	}

	var r0 *models.AgentCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.AgentCard, error)); ok {
		return rf(ctx, cardURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.AgentCard); ok {
		r0 = rf(ctx, cardURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AgentCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cardURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentCardFetcherInterface_FetchAgentCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAgentCard'
type MockAgentCardFetcherInterface_FetchAgentCard_Call struct {
	*mock.Call
}

// FetchAgentCard is a helper method to define mock.On call
//   - ctx context.Context
//   - cardURL string
func (_e *MockAgentCardFetcherInterface_Expecter) FetchAgentCard(ctx interface{}, cardURL interface{}) *MockAgentCardFetcherInterface_FetchAgentCard_Call {
	return &MockAgentCardFetcherInterface_FetchAgentCard_Call{Call: _e.mock.On("FetchAgentCard", ctx, cardURL)}
}

func (_c *MockAgentCardFetcherInterface_FetchAgentCard_Call) Run(run func(ctx context.Context, cardURL string)) *MockAgentCardFetcherInterface_FetchAgentCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAgentCardFetcherInterface_FetchAgentCard_Call) Return(_a0 *models.AgentCard, _a1 error) *MockAgentCardFetcherInterface_FetchAgentCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentCardFetcherInterface_FetchAgentCard_Call) RunAndReturn(run func(context.Context, string) (*models.AgentCard, error)) *MockAgentCardFetcherInterface_FetchAgentCard_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentCardFetcherInterface creates a new instance of MockAgentCardFetcherInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentCardFetcherInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentCardFetcherInterface {
	mock := &MockAgentCardFetcherInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
