// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockGitHubAppServiceInterface is an autogenerated mock type for the GitHubAppServiceInterface type
type MockGitHubAppServiceInterface struct {
	mock.Mock
}

type MockGitHubAppServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitHubAppServiceInterface) EXPECT() *MockGitHubAppServiceInterface_Expecter {
	return &MockGitHubAppServiceInterface_Expecter{mock: &_m.Mock}
}

// DisconnectInstallation provides a mock function with given fields: ctx, userID, teamID
func (_m *MockGitHubAppServiceInterface) DisconnectInstallation(ctx context.Context, userID string, teamID string) error {
	ret := _m.Called(ctx, userID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for DisconnectInstallation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitHubAppServiceInterface_DisconnectInstallation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectInstallation'
type MockGitHubAppServiceInterface_DisconnectInstallation_Call struct {
	*mock.Call
}

// DisconnectInstallation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
func (_e *MockGitHubAppServiceInterface_Expecter) DisconnectInstallation(ctx interface{}, userID interface{}, teamID interface{}) *MockGitHubAppServiceInterface_DisconnectInstallation_Call {
	return &MockGitHubAppServiceInterface_DisconnectInstallation_Call{Call: _e.mock.On("DisconnectInstallation", ctx, userID, teamID)}
}

func (_c *MockGitHubAppServiceInterface_DisconnectInstallation_Call) Run(run func(ctx context.Context, userID string, teamID string)) *MockGitHubAppServiceInterface_DisconnectInstallation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGitHubAppServiceInterface_DisconnectInstallation_Call) Return(_a0 error) *MockGitHubAppServiceInterface_DisconnectInstallation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitHubAppServiceInterface_DisconnectInstallation_Call) RunAndReturn(run func(context.Context, string, string) error) *MockGitHubAppServiceInterface_DisconnectInstallation_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessibleRepoURLs provides a mock function with given fields: ctx, teamID
func (_m *MockGitHubAppServiceInterface) GetAccessibleRepoURLs(ctx context.Context, teamID string) (map[string]bool, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessibleRepoURLs")
	}

	var r0 map[string]bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]bool, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]bool); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitHubAppServiceInterface_GetAccessibleRepoURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessibleRepoURLs'
type MockGitHubAppServiceInterface_GetAccessibleRepoURLs_Call struct {
	*mock.Call
}

// GetAccessibleRepoURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockGitHubAppServiceInterface_Expecter) GetAccessibleRepoURLs(ctx interface{}, teamID interface{}) *MockGitHubAppServiceInterface_GetAccessibleRepoURLs_Call {
	return &MockGitHubAppServiceInterface_GetAccessibleRepoURLs_Call{Call: _e.mock.On("GetAccessibleRepoURLs", ctx, teamID)}
}

func (_c *MockGitHubAppServiceInterface_GetAccessibleRepoURLs_Call) Run(run func(ctx context.Context, teamID string)) *MockGitHubAppServiceInterface_GetAccessibleRepoURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGitHubAppServiceInterface_GetAccessibleRepoURLs_Call) Return(_a0 map[string]bool, _a1 error) *MockGitHubAppServiceInterface_GetAccessibleRepoURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitHubAppServiceInterface_GetAccessibleRepoURLs_Call) RunAndReturn(run func(context.Context, string) (map[string]bool, error)) *MockGitHubAppServiceInterface_GetAccessibleRepoURLs_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstallationStatus provides a mock function with given fields: ctx, teamID
func (_m *MockGitHubAppServiceInterface) GetInstallationStatus(ctx context.Context, teamID string) (*models.GitHubInstallationStatus, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetInstallationStatus")
	}

	var r0 *models.GitHubInstallationStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.GitHubInstallationStatus, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.GitHubInstallationStatus); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GitHubInstallationStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitHubAppServiceInterface_GetInstallationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstallationStatus'
type MockGitHubAppServiceInterface_GetInstallationStatus_Call struct {
	*mock.Call
}

// GetInstallationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockGitHubAppServiceInterface_Expecter) GetInstallationStatus(ctx interface{}, teamID interface{}) *MockGitHubAppServiceInterface_GetInstallationStatus_Call {
	return &MockGitHubAppServiceInterface_GetInstallationStatus_Call{Call: _e.mock.On("GetInstallationStatus", ctx, teamID)}
}

func (_c *MockGitHubAppServiceInterface_GetInstallationStatus_Call) Run(run func(ctx context.Context, teamID string)) *MockGitHubAppServiceInterface_GetInstallationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGitHubAppServiceInterface_GetInstallationStatus_Call) Return(_a0 *models.GitHubInstallationStatus, _a1 error) *MockGitHubAppServiceInterface_GetInstallationStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitHubAppServiceInterface_GetInstallationStatus_Call) RunAndReturn(run func(context.Context, string) (*models.GitHubInstallationStatus, error)) *MockGitHubAppServiceInterface_GetInstallationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepositories provides a mock function with given fields: ctx, teamID, userID, page
func (_m *MockGitHubAppServiceInterface) GetRepositories(ctx context.Context, teamID string, userID string, page int) (*models.GitHubRepositoriesResponse, error) {
	ret := _m.Called(ctx, teamID, userID, page)

	if len(ret) == 0 {
		panic("no return value specified for GetRepositories")
	}

	var r0 *models.GitHubRepositoriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*models.GitHubRepositoriesResponse, error)); ok {
		return rf(ctx, teamID, userID, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *models.GitHubRepositoriesResponse); ok {
		r0 = rf(ctx, teamID, userID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GitHubRepositoriesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, teamID, userID, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitHubAppServiceInterface_GetRepositories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepositories'
type MockGitHubAppServiceInterface_GetRepositories_Call struct {
	*mock.Call
}

// GetRepositories is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - userID string
//   - page int
func (_e *MockGitHubAppServiceInterface_Expecter) GetRepositories(ctx interface{}, teamID interface{}, userID interface{}, page interface{}) *MockGitHubAppServiceInterface_GetRepositories_Call {
	return &MockGitHubAppServiceInterface_GetRepositories_Call{Call: _e.mock.On("GetRepositories", ctx, teamID, userID, page)}
}

func (_c *MockGitHubAppServiceInterface_GetRepositories_Call) Run(run func(ctx context.Context, teamID string, userID string, page int)) *MockGitHubAppServiceInterface_GetRepositories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockGitHubAppServiceInterface_GetRepositories_Call) Return(_a0 *models.GitHubRepositoriesResponse, _a1 error) *MockGitHubAppServiceInterface_GetRepositories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitHubAppServiceInterface_GetRepositories_Call) RunAndReturn(run func(context.Context, string, string, int) (*models.GitHubRepositoriesResponse, error)) *MockGitHubAppServiceInterface_GetRepositories_Call {
	_c.Call.Return(run)
	return _c
}

// HandleInstallationCallback provides a mock function with given fields: ctx, userID, teamID, installationID
func (_m *MockGitHubAppServiceInterface) HandleInstallationCallback(ctx context.Context, userID string, teamID string, installationID int64) (bool, error) {
	ret := _m.Called(ctx, userID, teamID, installationID)

	if len(ret) == 0 {
		panic("no return value specified for HandleInstallationCallback")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) (bool, error)); ok {
		return rf(ctx, userID, teamID, installationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) bool); ok {
		r0 = rf(ctx, userID, teamID, installationID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, userID, teamID, installationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitHubAppServiceInterface_HandleInstallationCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleInstallationCallback'
type MockGitHubAppServiceInterface_HandleInstallationCallback_Call struct {
	*mock.Call
}

// HandleInstallationCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - installationID int64
func (_e *MockGitHubAppServiceInterface_Expecter) HandleInstallationCallback(ctx interface{}, userID interface{}, teamID interface{}, installationID interface{}) *MockGitHubAppServiceInterface_HandleInstallationCallback_Call {
	return &MockGitHubAppServiceInterface_HandleInstallationCallback_Call{Call: _e.mock.On("HandleInstallationCallback", ctx, userID, teamID, installationID)}
}

func (_c *MockGitHubAppServiceInterface_HandleInstallationCallback_Call) Run(run func(ctx context.Context, userID string, teamID string, installationID int64)) *MockGitHubAppServiceInterface_HandleInstallationCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockGitHubAppServiceInterface_HandleInstallationCallback_Call) Return(_a0 bool, _a1 error) *MockGitHubAppServiceInterface_HandleInstallationCallback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitHubAppServiceInterface_HandleInstallationCallback_Call) RunAndReturn(run func(context.Context, string, string, int64) (bool, error)) *MockGitHubAppServiceInterface_HandleInstallationCallback_Call {
	_c.Call.Return(run)
	return _c
}

// HandleWebhookEvent provides a mock function with given fields: ctx, eventType, installationID, action
func (_m *MockGitHubAppServiceInterface) HandleWebhookEvent(ctx context.Context, eventType string, installationID int64, action string) error {
	ret := _m.Called(ctx, eventType, installationID, action)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebhookEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string) error); ok {
		r0 = rf(ctx, eventType, installationID, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitHubAppServiceInterface_HandleWebhookEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleWebhookEvent'
type MockGitHubAppServiceInterface_HandleWebhookEvent_Call struct {
	*mock.Call
}

// HandleWebhookEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType string
//   - installationID int64
//   - action string
func (_e *MockGitHubAppServiceInterface_Expecter) HandleWebhookEvent(ctx interface{}, eventType interface{}, installationID interface{}, action interface{}) *MockGitHubAppServiceInterface_HandleWebhookEvent_Call {
	return &MockGitHubAppServiceInterface_HandleWebhookEvent_Call{Call: _e.mock.On("HandleWebhookEvent", ctx, eventType, installationID, action)}
}

func (_c *MockGitHubAppServiceInterface_HandleWebhookEvent_Call) Run(run func(ctx context.Context, eventType string, installationID int64, action string)) *MockGitHubAppServiceInterface_HandleWebhookEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MockGitHubAppServiceInterface_HandleWebhookEvent_Call) Return(_a0 error) *MockGitHubAppServiceInterface_HandleWebhookEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitHubAppServiceInterface_HandleWebhookEvent_Call) RunAndReturn(run func(context.Context, string, int64, string) error) *MockGitHubAppServiceInterface_HandleWebhookEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ImportBlueprintsFromRepository provides a mock function with given fields: ctx, userID, teamID, repoID
func (_m *MockGitHubAppServiceInterface) ImportBlueprintsFromRepository(ctx context.Context, userID string, teamID string, repoID int64) (*models.BlueprintImportReport, error) {
	ret := _m.Called(ctx, userID, teamID, repoID)

	if len(ret) == 0 {
		panic("no return value specified for ImportBlueprintsFromRepository")
	}

	var r0 *models.BlueprintImportReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) (*models.BlueprintImportReport, error)); ok {
		return rf(ctx, userID, teamID, repoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) *models.BlueprintImportReport); ok {
		r0 = rf(ctx, userID, teamID, repoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BlueprintImportReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, userID, teamID, repoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitHubAppServiceInterface_ImportBlueprintsFromRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportBlueprintsFromRepository'
type MockGitHubAppServiceInterface_ImportBlueprintsFromRepository_Call struct {
	*mock.Call
}

// ImportBlueprintsFromRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - repoID int64
func (_e *MockGitHubAppServiceInterface_Expecter) ImportBlueprintsFromRepository(ctx interface{}, userID interface{}, teamID interface{}, repoID interface{}) *MockGitHubAppServiceInterface_ImportBlueprintsFromRepository_Call {
	return &MockGitHubAppServiceInterface_ImportBlueprintsFromRepository_Call{Call: _e.mock.On("ImportBlueprintsFromRepository", ctx, userID, teamID, repoID)}
}

func (_c *MockGitHubAppServiceInterface_ImportBlueprintsFromRepository_Call) Run(run func(ctx context.Context, userID string, teamID string, repoID int64)) *MockGitHubAppServiceInterface_ImportBlueprintsFromRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockGitHubAppServiceInterface_ImportBlueprintsFromRepository_Call) Return(_a0 *models.BlueprintImportReport, _a1 error) *MockGitHubAppServiceInterface_ImportBlueprintsFromRepository_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitHubAppServiceInterface_ImportBlueprintsFromRepository_Call) RunAndReturn(run func(context.Context, string, string, int64) (*models.BlueprintImportReport, error)) *MockGitHubAppServiceInterface_ImportBlueprintsFromRepository_Call {
	_c.Call.Return(run)
	return _c
}

// ImportProjectFromRepository provides a mock function with given fields: ctx, userID, teamID, repoID
func (_m *MockGitHubAppServiceInterface) ImportProjectFromRepository(ctx context.Context, userID string, teamID string, repoID int64) (*models.Project, bool, error) {
	ret := _m.Called(ctx, userID, teamID, repoID)

	if len(ret) == 0 {
		panic("no return value specified for ImportProjectFromRepository")
	}

	var r0 *models.Project
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) (*models.Project, bool, error)); ok {
		return rf(ctx, userID, teamID, repoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) *models.Project); ok {
		r0 = rf(ctx, userID, teamID, repoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) bool); ok {
		r1 = rf(ctx, userID, teamID, repoID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int64) error); ok {
		r2 = rf(ctx, userID, teamID, repoID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockGitHubAppServiceInterface_ImportProjectFromRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportProjectFromRepository'
type MockGitHubAppServiceInterface_ImportProjectFromRepository_Call struct {
	*mock.Call
}

// ImportProjectFromRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - repoID int64
func (_e *MockGitHubAppServiceInterface_Expecter) ImportProjectFromRepository(ctx interface{}, userID interface{}, teamID interface{}, repoID interface{}) *MockGitHubAppServiceInterface_ImportProjectFromRepository_Call {
	return &MockGitHubAppServiceInterface_ImportProjectFromRepository_Call{Call: _e.mock.On("ImportProjectFromRepository", ctx, userID, teamID, repoID)}
}

func (_c *MockGitHubAppServiceInterface_ImportProjectFromRepository_Call) Run(run func(ctx context.Context, userID string, teamID string, repoID int64)) *MockGitHubAppServiceInterface_ImportProjectFromRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockGitHubAppServiceInterface_ImportProjectFromRepository_Call) Return(_a0 *models.Project, _a1 bool, _a2 error) *MockGitHubAppServiceInterface_ImportProjectFromRepository_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockGitHubAppServiceInterface_ImportProjectFromRepository_Call) RunAndReturn(run func(context.Context, string, string, int64) (*models.Project, bool, error)) *MockGitHubAppServiceInterface_ImportProjectFromRepository_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshInstallationToken provides a mock function with given fields: ctx, teamID
func (_m *MockGitHubAppServiceInterface) RefreshInstallationToken(ctx context.Context, teamID string) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshInstallationToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitHubAppServiceInterface_RefreshInstallationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshInstallationToken'
type MockGitHubAppServiceInterface_RefreshInstallationToken_Call struct {
	*mock.Call
}

// RefreshInstallationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockGitHubAppServiceInterface_Expecter) RefreshInstallationToken(ctx interface{}, teamID interface{}) *MockGitHubAppServiceInterface_RefreshInstallationToken_Call {
	return &MockGitHubAppServiceInterface_RefreshInstallationToken_Call{Call: _e.mock.On("RefreshInstallationToken", ctx, teamID)}
}

func (_c *MockGitHubAppServiceInterface_RefreshInstallationToken_Call) Run(run func(ctx context.Context, teamID string)) *MockGitHubAppServiceInterface_RefreshInstallationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGitHubAppServiceInterface_RefreshInstallationToken_Call) Return(_a0 error) *MockGitHubAppServiceInterface_RefreshInstallationToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitHubAppServiceInterface_RefreshInstallationToken_Call) RunAndReturn(run func(context.Context, string) error) *MockGitHubAppServiceInterface_RefreshInstallationToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGitHubAppServiceInterface creates a new instance of MockGitHubAppServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitHubAppServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitHubAppServiceInterface {
	mock := &MockGitHubAppServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
