// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockInstanceSearchSettingsServiceInterface is an autogenerated mock type for the InstanceSearchSettingsServiceInterface type
type MockInstanceSearchSettingsServiceInterface struct {
	mock.Mock
}

type MockInstanceSearchSettingsServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstanceSearchSettingsServiceInterface) EXPECT() *MockInstanceSearchSettingsServiceInterface_Expecter {
	return &MockInstanceSearchSettingsServiceInterface_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx
func (_m *MockInstanceSearchSettingsServiceInterface) Get(ctx context.Context) (*models.InstanceSearchSettingsView, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.InstanceSearchSettingsView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.InstanceSearchSettingsView, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.InstanceSearchSettingsView); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InstanceSearchSettingsView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceSearchSettingsServiceInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInstanceSearchSettingsServiceInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstanceSearchSettingsServiceInterface_Expecter) Get(ctx interface{}) *MockInstanceSearchSettingsServiceInterface_Get_Call {
	return &MockInstanceSearchSettingsServiceInterface_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockInstanceSearchSettingsServiceInterface_Get_Call) Run(run func(ctx context.Context)) *MockInstanceSearchSettingsServiceInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInstanceSearchSettingsServiceInterface_Get_Call) Return(_a0 *models.InstanceSearchSettingsView, _a1 error) *MockInstanceSearchSettingsServiceInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInstanceSearchSettingsServiceInterface_Get_Call) RunAndReturn(run func(context.Context) (*models.InstanceSearchSettingsView, error)) *MockInstanceSearchSettingsServiceInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with given fields: ctx, actorUserID
func (_m *MockInstanceSearchSettingsServiceInterface) Reset(ctx context.Context, actorUserID string) error {
	ret := _m.Called(ctx, actorUserID)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, actorUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstanceSearchSettingsServiceInterface_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockInstanceSearchSettingsServiceInterface_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID string
func (_e *MockInstanceSearchSettingsServiceInterface_Expecter) Reset(ctx interface{}, actorUserID interface{}) *MockInstanceSearchSettingsServiceInterface_Reset_Call {
	return &MockInstanceSearchSettingsServiceInterface_Reset_Call{Call: _e.mock.On("Reset", ctx, actorUserID)}
}

func (_c *MockInstanceSearchSettingsServiceInterface_Reset_Call) Run(run func(ctx context.Context, actorUserID string)) *MockInstanceSearchSettingsServiceInterface_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInstanceSearchSettingsServiceInterface_Reset_Call) Return(_a0 error) *MockInstanceSearchSettingsServiceInterface_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceSearchSettingsServiceInterface_Reset_Call) RunAndReturn(run func(context.Context, string) error) *MockInstanceSearchSettingsServiceInterface_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: ctx
func (_m *MockInstanceSearchSettingsServiceInterface) Resolve(ctx context.Context) models.InstanceSearchSettingsValues {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 models.InstanceSearchSettingsValues
	if rf, ok := ret.Get(0).(func(context.Context) models.InstanceSearchSettingsValues); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.InstanceSearchSettingsValues)
	}

	return r0
}

// MockInstanceSearchSettingsServiceInterface_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockInstanceSearchSettingsServiceInterface_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstanceSearchSettingsServiceInterface_Expecter) Resolve(ctx interface{}) *MockInstanceSearchSettingsServiceInterface_Resolve_Call {
	return &MockInstanceSearchSettingsServiceInterface_Resolve_Call{Call: _e.mock.On("Resolve", ctx)}
}

func (_c *MockInstanceSearchSettingsServiceInterface_Resolve_Call) Run(run func(ctx context.Context)) *MockInstanceSearchSettingsServiceInterface_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInstanceSearchSettingsServiceInterface_Resolve_Call) Return(_a0 models.InstanceSearchSettingsValues) *MockInstanceSearchSettingsServiceInterface_Resolve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceSearchSettingsServiceInterface_Resolve_Call) RunAndReturn(run func(context.Context) models.InstanceSearchSettingsValues) *MockInstanceSearchSettingsServiceInterface_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, actorUserID, values, expectedVersion
func (_m *MockInstanceSearchSettingsServiceInterface) Update(ctx context.Context, actorUserID string, values models.InstanceSearchSettingsValues, expectedVersion *int64) (*models.InstanceSearchSettingsView, error) {
	ret := _m.Called(ctx, actorUserID, values, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.InstanceSearchSettingsView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.InstanceSearchSettingsValues, *int64) (*models.InstanceSearchSettingsView, error)); ok {
		return rf(ctx, actorUserID, values, expectedVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.InstanceSearchSettingsValues, *int64) *models.InstanceSearchSettingsView); ok {
		r0 = rf(ctx, actorUserID, values, expectedVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InstanceSearchSettingsView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.InstanceSearchSettingsValues, *int64) error); ok {
		r1 = rf(ctx, actorUserID, values, expectedVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstanceSearchSettingsServiceInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockInstanceSearchSettingsServiceInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID string
//   - values models.InstanceSearchSettingsValues
//   - expectedVersion *int64
func (_e *MockInstanceSearchSettingsServiceInterface_Expecter) Update(ctx interface{}, actorUserID interface{}, values interface{}, expectedVersion interface{}) *MockInstanceSearchSettingsServiceInterface_Update_Call {
	return &MockInstanceSearchSettingsServiceInterface_Update_Call{Call: _e.mock.On("Update", ctx, actorUserID, values, expectedVersion)}
}

func (_c *MockInstanceSearchSettingsServiceInterface_Update_Call) Run(run func(ctx context.Context, actorUserID string, values models.InstanceSearchSettingsValues, expectedVersion *int64)) *MockInstanceSearchSettingsServiceInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.InstanceSearchSettingsValues), args[3].(*int64))
	})
	return _c
}

func (_c *MockInstanceSearchSettingsServiceInterface_Update_Call) Return(_a0 *models.InstanceSearchSettingsView, _a1 error) *MockInstanceSearchSettingsServiceInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInstanceSearchSettingsServiceInterface_Update_Call) RunAndReturn(run func(context.Context, string, models.InstanceSearchSettingsValues, *int64) (*models.InstanceSearchSettingsView, error)) *MockInstanceSearchSettingsServiceInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstanceSearchSettingsServiceInterface creates a new instance of MockInstanceSearchSettingsServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstanceSearchSettingsServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstanceSearchSettingsServiceInterface {
	mock := &MockInstanceSearchSettingsServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
