// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	services "github.com/vibexp/vibexp/internal/services"
)

// MockActiveEmbeddingProviderResolver is an autogenerated mock type for the ActiveEmbeddingProviderResolver type
type MockActiveEmbeddingProviderResolver struct {
	mock.Mock
}

type MockActiveEmbeddingProviderResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActiveEmbeddingProviderResolver) EXPECT() *MockActiveEmbeddingProviderResolver_Expecter {
	return &MockActiveEmbeddingProviderResolver_Expecter{mock: &_m.Mock}
}

// ResolveActiveProvider provides a mock function with given fields: ctx, model, dimensions
func (_m *MockActiveEmbeddingProviderResolver) ResolveActiveProvider(ctx context.Context, model string, dimensions int) (services.EmbeddingProvider, error) {
	ret := _m.Called(ctx, model, dimensions)

	if len(ret) == 0 {
		panic("no return value specified for ResolveActiveProvider")
	}

	var r0 services.EmbeddingProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (services.EmbeddingProvider, error)); ok {
		return rf(ctx, model, dimensions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) services.EmbeddingProvider); ok {
		r0 = rf(ctx, model, dimensions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(services.EmbeddingProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, model, dimensions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActiveEmbeddingProviderResolver_ResolveActiveProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveActiveProvider'
type MockActiveEmbeddingProviderResolver_ResolveActiveProvider_Call struct {
	*mock.Call
}

// ResolveActiveProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - dimensions int
func (_e *MockActiveEmbeddingProviderResolver_Expecter) ResolveActiveProvider(ctx interface{}, model interface{}, dimensions interface{}) *MockActiveEmbeddingProviderResolver_ResolveActiveProvider_Call {
	return &MockActiveEmbeddingProviderResolver_ResolveActiveProvider_Call{Call: _e.mock.On("ResolveActiveProvider", ctx, model, dimensions)}
}

func (_c *MockActiveEmbeddingProviderResolver_ResolveActiveProvider_Call) Run(run func(ctx context.Context, model string, dimensions int)) *MockActiveEmbeddingProviderResolver_ResolveActiveProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockActiveEmbeddingProviderResolver_ResolveActiveProvider_Call) Return(_a0 services.EmbeddingProvider, _a1 error) *MockActiveEmbeddingProviderResolver_ResolveActiveProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActiveEmbeddingProviderResolver_ResolveActiveProvider_Call) RunAndReturn(run func(context.Context, string, int) (services.EmbeddingProvider, error)) *MockActiveEmbeddingProviderResolver_ResolveActiveProvider_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActiveEmbeddingProviderResolver creates a new instance of MockActiveEmbeddingProviderResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActiveEmbeddingProviderResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActiveEmbeddingProviderResolver {
	mock := &MockActiveEmbeddingProviderResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
