// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockInstanceAdminPredicate is an autogenerated mock type for the InstanceAdminPredicate type
type MockInstanceAdminPredicate struct {
	mock.Mock
}

type MockInstanceAdminPredicate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstanceAdminPredicate) EXPECT() *MockInstanceAdminPredicate_Expecter {
	return &MockInstanceAdminPredicate_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: email
func (_m *MockInstanceAdminPredicate) Execute(email string) bool {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockInstanceAdminPredicate_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockInstanceAdminPredicate_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - email string
func (_e *MockInstanceAdminPredicate_Expecter) Execute(email interface{}) *MockInstanceAdminPredicate_Execute_Call {
	return &MockInstanceAdminPredicate_Execute_Call{Call: _e.mock.On("Execute", email)}
}

func (_c *MockInstanceAdminPredicate_Execute_Call) Run(run func(email string)) *MockInstanceAdminPredicate_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockInstanceAdminPredicate_Execute_Call) Return(_a0 bool) *MockInstanceAdminPredicate_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstanceAdminPredicate_Execute_Call) RunAndReturn(run func(string) bool) *MockInstanceAdminPredicate_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstanceAdminPredicate creates a new instance of MockInstanceAdminPredicate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstanceAdminPredicate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstanceAdminPredicate {
	mock := &MockInstanceAdminPredicate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
