// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	services "github.com/vibexp/vibexp/internal/services"
)

// MockA2AStreamProcessorInterface is an autogenerated mock type for the A2AStreamProcessorInterface type
type MockA2AStreamProcessorInterface struct {
	mock.Mock
}

type MockA2AStreamProcessorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockA2AStreamProcessorInterface) EXPECT() *MockA2AStreamProcessorInterface_Expecter {
	return &MockA2AStreamProcessorInterface_Expecter{mock: &_m.Mock}
}

// ProcessStream provides a mock function with given fields: ctx, executionID, eventChan
func (_m *MockA2AStreamProcessorInterface) ProcessStream(ctx context.Context, executionID string, eventChan <-chan *services.A2AStreamEvent) error {
	ret := _m.Called(ctx, executionID, eventChan)

	if len(ret) == 0 {
		panic("no return value specified for ProcessStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, <-chan *services.A2AStreamEvent) error); ok {
		r0 = rf(ctx, executionID, eventChan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockA2AStreamProcessorInterface_ProcessStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessStream'
type MockA2AStreamProcessorInterface_ProcessStream_Call struct {
	*mock.Call
}

// ProcessStream is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
//   - eventChan <-chan *services.A2AStreamEvent
func (_e *MockA2AStreamProcessorInterface_Expecter) ProcessStream(ctx interface{}, executionID interface{}, eventChan interface{}) *MockA2AStreamProcessorInterface_ProcessStream_Call {
	return &MockA2AStreamProcessorInterface_ProcessStream_Call{Call: _e.mock.On("ProcessStream", ctx, executionID, eventChan)}
}

func (_c *MockA2AStreamProcessorInterface_ProcessStream_Call) Run(run func(ctx context.Context, executionID string, eventChan <-chan *services.A2AStreamEvent)) *MockA2AStreamProcessorInterface_ProcessStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(<-chan *services.A2AStreamEvent))
	})
	return _c
}

func (_c *MockA2AStreamProcessorInterface_ProcessStream_Call) Return(_a0 error) *MockA2AStreamProcessorInterface_ProcessStream_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockA2AStreamProcessorInterface_ProcessStream_Call) RunAndReturn(run func(context.Context, string, <-chan *services.A2AStreamEvent) error) *MockA2AStreamProcessorInterface_ProcessStream_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockA2AStreamProcessorInterface creates a new instance of MockA2AStreamProcessorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockA2AStreamProcessorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockA2AStreamProcessorInterface {
	mock := &MockA2AStreamProcessorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
