// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	projectmigration "github.com/vibexp/vibexp/internal/services/projectmigration"
)

// MockProjectMigrationServiceInterface is an autogenerated mock type for the ProjectMigrationServiceInterface type
type MockProjectMigrationServiceInterface struct {
	mock.Mock
}

type MockProjectMigrationServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectMigrationServiceInterface) EXPECT() *MockProjectMigrationServiceInterface_Expecter {
	return &MockProjectMigrationServiceInterface_Expecter{mock: &_m.Mock}
}

// GetInventory provides a mock function with given fields: ctx, userID, teamID, projectID
func (_m *MockProjectMigrationServiceInterface) GetInventory(ctx context.Context, userID string, teamID string, projectID string) (*projectmigration.MigrationInventory, error) {
	ret := _m.Called(ctx, userID, teamID, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetInventory")
	}

	var r0 *projectmigration.MigrationInventory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*projectmigration.MigrationInventory, error)); ok {
		return rf(ctx, userID, teamID, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *projectmigration.MigrationInventory); ok {
		r0 = rf(ctx, userID, teamID, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*projectmigration.MigrationInventory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, teamID, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectMigrationServiceInterface_GetInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInventory'
type MockProjectMigrationServiceInterface_GetInventory_Call struct {
	*mock.Call
}

// GetInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - projectID string
func (_e *MockProjectMigrationServiceInterface_Expecter) GetInventory(ctx interface{}, userID interface{}, teamID interface{}, projectID interface{}) *MockProjectMigrationServiceInterface_GetInventory_Call {
	return &MockProjectMigrationServiceInterface_GetInventory_Call{Call: _e.mock.On("GetInventory", ctx, userID, teamID, projectID)}
}

func (_c *MockProjectMigrationServiceInterface_GetInventory_Call) Run(run func(ctx context.Context, userID string, teamID string, projectID string)) *MockProjectMigrationServiceInterface_GetInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockProjectMigrationServiceInterface_GetInventory_Call) Return(_a0 *projectmigration.MigrationInventory, _a1 error) *MockProjectMigrationServiceInterface_GetInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectMigrationServiceInterface_GetInventory_Call) RunAndReturn(run func(context.Context, string, string, string) (*projectmigration.MigrationInventory, error)) *MockProjectMigrationServiceInterface_GetInventory_Call {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function with given fields: ctx, userID, teamID, sourceProjectID, req
func (_m *MockProjectMigrationServiceInterface) Migrate(ctx context.Context, userID string, teamID string, sourceProjectID string, req *projectmigration.MigrationRequest) (*projectmigration.MigrationResult, error) {
	ret := _m.Called(ctx, userID, teamID, sourceProjectID, req)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 *projectmigration.MigrationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *projectmigration.MigrationRequest) (*projectmigration.MigrationResult, error)); ok {
		return rf(ctx, userID, teamID, sourceProjectID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *projectmigration.MigrationRequest) *projectmigration.MigrationResult); ok {
		r0 = rf(ctx, userID, teamID, sourceProjectID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*projectmigration.MigrationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *projectmigration.MigrationRequest) error); ok {
		r1 = rf(ctx, userID, teamID, sourceProjectID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectMigrationServiceInterface_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type MockProjectMigrationServiceInterface_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - sourceProjectID string
//   - req *projectmigration.MigrationRequest
func (_e *MockProjectMigrationServiceInterface_Expecter) Migrate(ctx interface{}, userID interface{}, teamID interface{}, sourceProjectID interface{}, req interface{}) *MockProjectMigrationServiceInterface_Migrate_Call {
	return &MockProjectMigrationServiceInterface_Migrate_Call{Call: _e.mock.On("Migrate", ctx, userID, teamID, sourceProjectID, req)}
}

func (_c *MockProjectMigrationServiceInterface_Migrate_Call) Run(run func(ctx context.Context, userID string, teamID string, sourceProjectID string, req *projectmigration.MigrationRequest)) *MockProjectMigrationServiceInterface_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*projectmigration.MigrationRequest))
	})
	return _c
}

func (_c *MockProjectMigrationServiceInterface_Migrate_Call) Return(_a0 *projectmigration.MigrationResult, _a1 error) *MockProjectMigrationServiceInterface_Migrate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectMigrationServiceInterface_Migrate_Call) RunAndReturn(run func(context.Context, string, string, string, *projectmigration.MigrationRequest) (*projectmigration.MigrationResult, error)) *MockProjectMigrationServiceInterface_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectMigrationServiceInterface creates a new instance of MockProjectMigrationServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectMigrationServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectMigrationServiceInterface {
	mock := &MockProjectMigrationServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
