// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
	services "github.com/vibexp/vibexp/internal/services"
)

// MockEmbeddingServiceInterface is an autogenerated mock type for the EmbeddingServiceInterface type
type MockEmbeddingServiceInterface struct {
	mock.Mock
}

type MockEmbeddingServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingServiceInterface) EXPECT() *MockEmbeddingServiceInterface_Expecter {
	return &MockEmbeddingServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteEmbeddingsByEntity provides a mock function with given fields: entityType, entityID
func (_m *MockEmbeddingServiceInterface) DeleteEmbeddingsByEntity(entityType string, entityID string) error {
	ret := _m.Called(entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEmbeddingsByEntity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(entityType, entityID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmbeddingServiceInterface_DeleteEmbeddingsByEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEmbeddingsByEntity'
type MockEmbeddingServiceInterface_DeleteEmbeddingsByEntity_Call struct {
	*mock.Call
}

// DeleteEmbeddingsByEntity is a helper method to define mock.On call
//   - entityType string
//   - entityID string
func (_e *MockEmbeddingServiceInterface_Expecter) DeleteEmbeddingsByEntity(entityType interface{}, entityID interface{}) *MockEmbeddingServiceInterface_DeleteEmbeddingsByEntity_Call {
	return &MockEmbeddingServiceInterface_DeleteEmbeddingsByEntity_Call{Call: _e.mock.On("DeleteEmbeddingsByEntity", entityType, entityID)}
}

func (_c *MockEmbeddingServiceInterface_DeleteEmbeddingsByEntity_Call) Run(run func(entityType string, entityID string)) *MockEmbeddingServiceInterface_DeleteEmbeddingsByEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockEmbeddingServiceInterface_DeleteEmbeddingsByEntity_Call) Return(_a0 error) *MockEmbeddingServiceInterface_DeleteEmbeddingsByEntity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingServiceInterface_DeleteEmbeddingsByEntity_Call) RunAndReturn(run func(string, string) error) *MockEmbeddingServiceInterface_DeleteEmbeddingsByEntity_Call {
	_c.Call.Return(run)
	return _c
}

// FindSimilar provides a mock function with given fields: userID, entityType, vector, limit
func (_m *MockEmbeddingServiceInterface) FindSimilar(userID string, entityType string, vector []float32, limit int) ([]models.EmbeddingSimilarity, error) {
	ret := _m.Called(userID, entityType, vector, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindSimilar")
	}

	var r0 []models.EmbeddingSimilarity
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, []float32, int) ([]models.EmbeddingSimilarity, error)); ok {
		return rf(userID, entityType, vector, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, []float32, int) []models.EmbeddingSimilarity); ok {
		r0 = rf(userID, entityType, vector, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EmbeddingSimilarity)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, []float32, int) error); ok {
		r1 = rf(userID, entityType, vector, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingServiceInterface_FindSimilar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSimilar'
type MockEmbeddingServiceInterface_FindSimilar_Call struct {
	*mock.Call
}

// FindSimilar is a helper method to define mock.On call
//   - userID string
//   - entityType string
//   - vector []float32
//   - limit int
func (_e *MockEmbeddingServiceInterface_Expecter) FindSimilar(userID interface{}, entityType interface{}, vector interface{}, limit interface{}) *MockEmbeddingServiceInterface_FindSimilar_Call {
	return &MockEmbeddingServiceInterface_FindSimilar_Call{Call: _e.mock.On("FindSimilar", userID, entityType, vector, limit)}
}

func (_c *MockEmbeddingServiceInterface_FindSimilar_Call) Run(run func(userID string, entityType string, vector []float32, limit int)) *MockEmbeddingServiceInterface_FindSimilar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]float32), args[3].(int))
	})
	return _c
}

func (_c *MockEmbeddingServiceInterface_FindSimilar_Call) Return(_a0 []models.EmbeddingSimilarity, _a1 error) *MockEmbeddingServiceInterface_FindSimilar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingServiceInterface_FindSimilar_Call) RunAndReturn(run func(string, string, []float32, int) ([]models.EmbeddingSimilarity, error)) *MockEmbeddingServiceInterface_FindSimilar_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmbeddingsByEntity provides a mock function with given fields: userID, entityType, entityID
func (_m *MockEmbeddingServiceInterface) GetEmbeddingsByEntity(userID string, entityType string, entityID string) ([]models.Embedding, error) {
	ret := _m.Called(userID, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetEmbeddingsByEntity")
	}

	var r0 []models.Embedding
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]models.Embedding, error)); ok {
		return rf(userID, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []models.Embedding); ok {
		r0 = rf(userID, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Embedding)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(userID, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingServiceInterface_GetEmbeddingsByEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbeddingsByEntity'
type MockEmbeddingServiceInterface_GetEmbeddingsByEntity_Call struct {
	*mock.Call
}

// GetEmbeddingsByEntity is a helper method to define mock.On call
//   - userID string
//   - entityType string
//   - entityID string
func (_e *MockEmbeddingServiceInterface_Expecter) GetEmbeddingsByEntity(userID interface{}, entityType interface{}, entityID interface{}) *MockEmbeddingServiceInterface_GetEmbeddingsByEntity_Call {
	return &MockEmbeddingServiceInterface_GetEmbeddingsByEntity_Call{Call: _e.mock.On("GetEmbeddingsByEntity", userID, entityType, entityID)}
}

func (_c *MockEmbeddingServiceInterface_GetEmbeddingsByEntity_Call) Run(run func(userID string, entityType string, entityID string)) *MockEmbeddingServiceInterface_GetEmbeddingsByEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEmbeddingServiceInterface_GetEmbeddingsByEntity_Call) Return(_a0 []models.Embedding, _a1 error) *MockEmbeddingServiceInterface_GetEmbeddingsByEntity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingServiceInterface_GetEmbeddingsByEntity_Call) RunAndReturn(run func(string, string, string) ([]models.Embedding, error)) *MockEmbeddingServiceInterface_GetEmbeddingsByEntity_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEmbedding provides a mock function with given fields: userID, entityType, entityID, modelID, vectors
func (_m *MockEmbeddingServiceInterface) SaveEmbedding(userID string, entityType string, entityID string, modelID string, vectors [][]float32) error {
	ret := _m.Called(userID, entityType, entityID, modelID, vectors)

	if len(ret) == 0 {
		panic("no return value specified for SaveEmbedding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, [][]float32) error); ok {
		r0 = rf(userID, entityType, entityID, modelID, vectors)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmbeddingServiceInterface_SaveEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEmbedding'
type MockEmbeddingServiceInterface_SaveEmbedding_Call struct {
	*mock.Call
}

// SaveEmbedding is a helper method to define mock.On call
//   - userID string
//   - entityType string
//   - entityID string
//   - modelID string
//   - vectors [][]float32
func (_e *MockEmbeddingServiceInterface_Expecter) SaveEmbedding(userID interface{}, entityType interface{}, entityID interface{}, modelID interface{}, vectors interface{}) *MockEmbeddingServiceInterface_SaveEmbedding_Call {
	return &MockEmbeddingServiceInterface_SaveEmbedding_Call{Call: _e.mock.On("SaveEmbedding", userID, entityType, entityID, modelID, vectors)}
}

func (_c *MockEmbeddingServiceInterface_SaveEmbedding_Call) Run(run func(userID string, entityType string, entityID string, modelID string, vectors [][]float32)) *MockEmbeddingServiceInterface_SaveEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].([][]float32))
	})
	return _c
}

func (_c *MockEmbeddingServiceInterface_SaveEmbedding_Call) Return(_a0 error) *MockEmbeddingServiceInterface_SaveEmbedding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingServiceInterface_SaveEmbedding_Call) RunAndReturn(run func(string, string, string, string, [][]float32) error) *MockEmbeddingServiceInterface_SaveEmbedding_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEmbeddingChunks provides a mock function with given fields: userID, entityType, entityID, modelID, chunks
func (_m *MockEmbeddingServiceInterface) SaveEmbeddingChunks(userID string, entityType string, entityID string, modelID string, chunks []services.EmbeddingChunk) error {
	ret := _m.Called(userID, entityType, entityID, modelID, chunks)

	if len(ret) == 0 {
		panic("no return value specified for SaveEmbeddingChunks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, []services.EmbeddingChunk) error); ok {
		r0 = rf(userID, entityType, entityID, modelID, chunks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmbeddingServiceInterface_SaveEmbeddingChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEmbeddingChunks'
type MockEmbeddingServiceInterface_SaveEmbeddingChunks_Call struct {
	*mock.Call
}

// SaveEmbeddingChunks is a helper method to define mock.On call
//   - userID string
//   - entityType string
//   - entityID string
//   - modelID string
//   - chunks []services.EmbeddingChunk
func (_e *MockEmbeddingServiceInterface_Expecter) SaveEmbeddingChunks(userID interface{}, entityType interface{}, entityID interface{}, modelID interface{}, chunks interface{}) *MockEmbeddingServiceInterface_SaveEmbeddingChunks_Call {
	return &MockEmbeddingServiceInterface_SaveEmbeddingChunks_Call{Call: _e.mock.On("SaveEmbeddingChunks", userID, entityType, entityID, modelID, chunks)}
}

func (_c *MockEmbeddingServiceInterface_SaveEmbeddingChunks_Call) Run(run func(userID string, entityType string, entityID string, modelID string, chunks []services.EmbeddingChunk)) *MockEmbeddingServiceInterface_SaveEmbeddingChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].([]services.EmbeddingChunk))
	})
	return _c
}

func (_c *MockEmbeddingServiceInterface_SaveEmbeddingChunks_Call) Return(_a0 error) *MockEmbeddingServiceInterface_SaveEmbeddingChunks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingServiceInterface_SaveEmbeddingChunks_Call) RunAndReturn(run func(string, string, string, string, []services.EmbeddingChunk) error) *MockEmbeddingServiceInterface_SaveEmbeddingChunks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingServiceInterface creates a new instance of MockEmbeddingServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingServiceInterface {
	mock := &MockEmbeddingServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
