// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockSearchSummaryServiceInterface is an autogenerated mock type for the SearchSummaryServiceInterface type
type MockSearchSummaryServiceInterface struct {
	mock.Mock
}

type MockSearchSummaryServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchSummaryServiceInterface) EXPECT() *MockSearchSummaryServiceInterface_Expecter {
	return &MockSearchSummaryServiceInterface_Expecter{mock: &_m.Mock}
}

// Summarize provides a mock function with given fields: ctx, teamID, req
func (_m *MockSearchSummaryServiceInterface) Summarize(ctx context.Context, teamID string, req *models.SearchSummaryRequest) (*models.SearchSummary, error) {
	ret := _m.Called(ctx, teamID, req)

	if len(ret) == 0 {
		panic("no return value specified for Summarize")
	}

	var r0 *models.SearchSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.SearchSummaryRequest) (*models.SearchSummary, error)); ok {
		return rf(ctx, teamID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.SearchSummaryRequest) *models.SearchSummary); ok {
		r0 = rf(ctx, teamID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SearchSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.SearchSummaryRequest) error); ok {
		r1 = rf(ctx, teamID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchSummaryServiceInterface_Summarize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Summarize'
type MockSearchSummaryServiceInterface_Summarize_Call struct {
	*mock.Call
}

// Summarize is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - req *models.SearchSummaryRequest
func (_e *MockSearchSummaryServiceInterface_Expecter) Summarize(ctx interface{}, teamID interface{}, req interface{}) *MockSearchSummaryServiceInterface_Summarize_Call {
	return &MockSearchSummaryServiceInterface_Summarize_Call{Call: _e.mock.On("Summarize", ctx, teamID, req)}
}

func (_c *MockSearchSummaryServiceInterface_Summarize_Call) Run(run func(ctx context.Context, teamID string, req *models.SearchSummaryRequest)) *MockSearchSummaryServiceInterface_Summarize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.SearchSummaryRequest))
	})
	return _c
}

func (_c *MockSearchSummaryServiceInterface_Summarize_Call) Return(_a0 *models.SearchSummary, _a1 error) *MockSearchSummaryServiceInterface_Summarize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchSummaryServiceInterface_Summarize_Call) RunAndReturn(run func(context.Context, string, *models.SearchSummaryRequest) (*models.SearchSummary, error)) *MockSearchSummaryServiceInterface_Summarize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchSummaryServiceInterface creates a new instance of MockSearchSummaryServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchSummaryServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchSummaryServiceInterface {
	mock := &MockSearchSummaryServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
