// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/vibexp/vibexp/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockResourceUsageServiceInterface is an autogenerated mock type for the ResourceUsageServiceInterface type
type MockResourceUsageServiceInterface struct {
	mock.Mock
}

type MockResourceUsageServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceUsageServiceInterface) EXPECT() *MockResourceUsageServiceInterface_Expecter {
	return &MockResourceUsageServiceInterface_Expecter{mock: &_m.Mock}
}

// CheckResourceLimit provides a mock function with given fields: ctx, userID, resourceType
func (_m *MockResourceUsageServiceInterface) CheckResourceLimit(ctx context.Context, userID string, resourceType string) (bool, error) {
	ret := _m.Called(ctx, userID, resourceType)

	if len(ret) == 0 {
		panic("no return value specified for CheckResourceLimit")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userID, resourceType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userID, resourceType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, resourceType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceUsageServiceInterface_CheckResourceLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckResourceLimit'
type MockResourceUsageServiceInterface_CheckResourceLimit_Call struct {
	*mock.Call
}

// CheckResourceLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - resourceType string
func (_e *MockResourceUsageServiceInterface_Expecter) CheckResourceLimit(ctx interface{}, userID interface{}, resourceType interface{}) *MockResourceUsageServiceInterface_CheckResourceLimit_Call {
	return &MockResourceUsageServiceInterface_CheckResourceLimit_Call{Call: _e.mock.On("CheckResourceLimit", ctx, userID, resourceType)}
}

func (_c *MockResourceUsageServiceInterface_CheckResourceLimit_Call) Run(run func(ctx context.Context, userID string, resourceType string)) *MockResourceUsageServiceInterface_CheckResourceLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockResourceUsageServiceInterface_CheckResourceLimit_Call) Return(_a0 bool, _a1 error) *MockResourceUsageServiceInterface_CheckResourceLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceUsageServiceInterface_CheckResourceLimit_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockResourceUsageServiceInterface_CheckResourceLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceUsage provides a mock function with given fields: ctx, userID
func (_m *MockResourceUsageServiceInterface) GetResourceUsage(ctx context.Context, userID string) (*models.ResourceUsageResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceUsage")
	}

	var r0 *models.ResourceUsageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.ResourceUsageResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ResourceUsageResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResourceUsageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResourceUsageServiceInterface_GetResourceUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceUsage'
type MockResourceUsageServiceInterface_GetResourceUsage_Call struct {
	*mock.Call
}

// GetResourceUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockResourceUsageServiceInterface_Expecter) GetResourceUsage(ctx interface{}, userID interface{}) *MockResourceUsageServiceInterface_GetResourceUsage_Call {
	return &MockResourceUsageServiceInterface_GetResourceUsage_Call{Call: _e.mock.On("GetResourceUsage", ctx, userID)}
}

func (_c *MockResourceUsageServiceInterface_GetResourceUsage_Call) Run(run func(ctx context.Context, userID string)) *MockResourceUsageServiceInterface_GetResourceUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockResourceUsageServiceInterface_GetResourceUsage_Call) Return(_a0 *models.ResourceUsageResponse, _a1 error) *MockResourceUsageServiceInterface_GetResourceUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceUsageServiceInterface_GetResourceUsage_Call) RunAndReturn(run func(context.Context, string) (*models.ResourceUsageResponse, error)) *MockResourceUsageServiceInterface_GetResourceUsage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResourceUsageServiceInterface creates a new instance of MockResourceUsageServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceUsageServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceUsageServiceInterface {
	mock := &MockResourceUsageServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
