// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockCommentServiceInterface is an autogenerated mock type for the CommentServiceInterface type
type MockCommentServiceInterface struct {
	mock.Mock
}

type MockCommentServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentServiceInterface) EXPECT() *MockCommentServiceInterface_Expecter {
	return &MockCommentServiceInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, teamID, req
func (_m *MockCommentServiceInterface) Create(ctx context.Context, userID string, teamID string, req *models.CreateCommentRequest) (*models.Comment, error) {
	ret := _m.Called(ctx, userID, teamID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *models.CreateCommentRequest) (*models.Comment, error)); ok {
		return rf(ctx, userID, teamID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *models.CreateCommentRequest) *models.Comment); ok {
		r0 = rf(ctx, userID, teamID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *models.CreateCommentRequest) error); ok {
		r1 = rf(ctx, userID, teamID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentServiceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCommentServiceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - req *models.CreateCommentRequest
func (_e *MockCommentServiceInterface_Expecter) Create(ctx interface{}, userID interface{}, teamID interface{}, req interface{}) *MockCommentServiceInterface_Create_Call {
	return &MockCommentServiceInterface_Create_Call{Call: _e.mock.On("Create", ctx, userID, teamID, req)}
}

func (_c *MockCommentServiceInterface_Create_Call) Run(run func(ctx context.Context, userID string, teamID string, req *models.CreateCommentRequest)) *MockCommentServiceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*models.CreateCommentRequest))
	})
	return _c
}

func (_c *MockCommentServiceInterface_Create_Call) Return(_a0 *models.Comment, _a1 error) *MockCommentServiceInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentServiceInterface_Create_Call) RunAndReturn(run func(context.Context, string, string, *models.CreateCommentRequest) (*models.Comment, error)) *MockCommentServiceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, teamID, commentID
func (_m *MockCommentServiceInterface) Delete(ctx context.Context, userID string, teamID string, commentID string) error {
	ret := _m.Called(ctx, userID, teamID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, teamID, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommentServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCommentServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - commentID string
func (_e *MockCommentServiceInterface_Expecter) Delete(ctx interface{}, userID interface{}, teamID interface{}, commentID interface{}) *MockCommentServiceInterface_Delete_Call {
	return &MockCommentServiceInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, teamID, commentID)}
}

func (_c *MockCommentServiceInterface_Delete_Call) Run(run func(ctx context.Context, userID string, teamID string, commentID string)) *MockCommentServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCommentServiceInterface_Delete_Call) Return(_a0 error) *MockCommentServiceInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommentServiceInterface_Delete_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockCommentServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByResource provides a mock function with given fields: ctx, userID, teamID, resourceType, resourceID, page, limit
func (_m *MockCommentServiceInterface) ListByResource(ctx context.Context, userID string, teamID string, resourceType string, resourceID string, page int, limit int) (*models.CommentListResponse, error) {
	ret := _m.Called(ctx, userID, teamID, resourceType, resourceID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByResource")
	}

	var r0 *models.CommentListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, int) (*models.CommentListResponse, error)); ok {
		return rf(ctx, userID, teamID, resourceType, resourceID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, int) *models.CommentListResponse); ok {
		r0 = rf(ctx, userID, teamID, resourceType, resourceID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CommentListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int, int) error); ok {
		r1 = rf(ctx, userID, teamID, resourceType, resourceID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentServiceInterface_ListByResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByResource'
type MockCommentServiceInterface_ListByResource_Call struct {
	*mock.Call
}

// ListByResource is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - resourceType string
//   - resourceID string
//   - page int
//   - limit int
func (_e *MockCommentServiceInterface_Expecter) ListByResource(ctx interface{}, userID interface{}, teamID interface{}, resourceType interface{}, resourceID interface{}, page interface{}, limit interface{}) *MockCommentServiceInterface_ListByResource_Call {
	return &MockCommentServiceInterface_ListByResource_Call{Call: _e.mock.On("ListByResource", ctx, userID, teamID, resourceType, resourceID, page, limit)}
}

func (_c *MockCommentServiceInterface_ListByResource_Call) Run(run func(ctx context.Context, userID string, teamID string, resourceType string, resourceID string, page int, limit int)) *MockCommentServiceInterface_ListByResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(int), args[6].(int))
	})
	return _c
}

func (_c *MockCommentServiceInterface_ListByResource_Call) Return(_a0 *models.CommentListResponse, _a1 error) *MockCommentServiceInterface_ListByResource_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentServiceInterface_ListByResource_Call) RunAndReturn(run func(context.Context, string, string, string, string, int, int) (*models.CommentListResponse, error)) *MockCommentServiceInterface_ListByResource_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecentByTeam provides a mock function with given fields: ctx, userID, teamID, limit
func (_m *MockCommentServiceInterface) ListRecentByTeam(ctx context.Context, userID string, teamID string, limit int) ([]models.CommentActivity, error) {
	ret := _m.Called(ctx, userID, teamID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRecentByTeam")
	}

	var r0 []models.CommentActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) ([]models.CommentActivity, error)); ok {
		return rf(ctx, userID, teamID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) []models.CommentActivity); ok {
		r0 = rf(ctx, userID, teamID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CommentActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, userID, teamID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentServiceInterface_ListRecentByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecentByTeam'
type MockCommentServiceInterface_ListRecentByTeam_Call struct {
	*mock.Call
}

// ListRecentByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - limit int
func (_e *MockCommentServiceInterface_Expecter) ListRecentByTeam(ctx interface{}, userID interface{}, teamID interface{}, limit interface{}) *MockCommentServiceInterface_ListRecentByTeam_Call {
	return &MockCommentServiceInterface_ListRecentByTeam_Call{Call: _e.mock.On("ListRecentByTeam", ctx, userID, teamID, limit)}
}

func (_c *MockCommentServiceInterface_ListRecentByTeam_Call) Run(run func(ctx context.Context, userID string, teamID string, limit int)) *MockCommentServiceInterface_ListRecentByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockCommentServiceInterface_ListRecentByTeam_Call) Return(_a0 []models.CommentActivity, _a1 error) *MockCommentServiceInterface_ListRecentByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentServiceInterface_ListRecentByTeam_Call) RunAndReturn(run func(context.Context, string, string, int) ([]models.CommentActivity, error)) *MockCommentServiceInterface_ListRecentByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, teamID, commentID, req
func (_m *MockCommentServiceInterface) Update(ctx context.Context, userID string, teamID string, commentID string, req *models.UpdateCommentRequest) (*models.Comment, error) {
	ret := _m.Called(ctx, userID, teamID, commentID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *models.UpdateCommentRequest) (*models.Comment, error)); ok {
		return rf(ctx, userID, teamID, commentID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *models.UpdateCommentRequest) *models.Comment); ok {
		r0 = rf(ctx, userID, teamID, commentID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *models.UpdateCommentRequest) error); ok {
		r1 = rf(ctx, userID, teamID, commentID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentServiceInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCommentServiceInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - commentID string
//   - req *models.UpdateCommentRequest
func (_e *MockCommentServiceInterface_Expecter) Update(ctx interface{}, userID interface{}, teamID interface{}, commentID interface{}, req interface{}) *MockCommentServiceInterface_Update_Call {
	return &MockCommentServiceInterface_Update_Call{Call: _e.mock.On("Update", ctx, userID, teamID, commentID, req)}
}

func (_c *MockCommentServiceInterface_Update_Call) Run(run func(ctx context.Context, userID string, teamID string, commentID string, req *models.UpdateCommentRequest)) *MockCommentServiceInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*models.UpdateCommentRequest))
	})
	return _c
}

func (_c *MockCommentServiceInterface_Update_Call) Return(_a0 *models.Comment, _a1 error) *MockCommentServiceInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentServiceInterface_Update_Call) RunAndReturn(run func(context.Context, string, string, string, *models.UpdateCommentRequest) (*models.Comment, error)) *MockCommentServiceInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommentServiceInterface creates a new instance of MockCommentServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentServiceInterface {
	mock := &MockCommentServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
