// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/vibexp/vibexp/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUserPreferencesServiceInterface is an autogenerated mock type for the UserPreferencesServiceInterface type
type MockUserPreferencesServiceInterface struct {
	mock.Mock
}

type MockUserPreferencesServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserPreferencesServiceInterface) EXPECT() *MockUserPreferencesServiceInterface_Expecter {
	return &MockUserPreferencesServiceInterface_Expecter{mock: &_m.Mock}
}

// GetPreferences provides a mock function with given fields: ctx, userID
func (_m *MockUserPreferencesServiceInterface) GetPreferences(ctx context.Context, userID string) (*models.PreferencesResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferences")
	}

	var r0 *models.PreferencesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PreferencesResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PreferencesResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PreferencesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserPreferencesServiceInterface_GetPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreferences'
type MockUserPreferencesServiceInterface_GetPreferences_Call struct {
	*mock.Call
}

// GetPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserPreferencesServiceInterface_Expecter) GetPreferences(ctx interface{}, userID interface{}) *MockUserPreferencesServiceInterface_GetPreferences_Call {
	return &MockUserPreferencesServiceInterface_GetPreferences_Call{Call: _e.mock.On("GetPreferences", ctx, userID)}
}

func (_c *MockUserPreferencesServiceInterface_GetPreferences_Call) Run(run func(ctx context.Context, userID string)) *MockUserPreferencesServiceInterface_GetPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserPreferencesServiceInterface_GetPreferences_Call) Return(_a0 *models.PreferencesResponse, _a1 error) *MockUserPreferencesServiceInterface_GetPreferences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserPreferencesServiceInterface_GetPreferences_Call) RunAndReturn(run func(context.Context, string) (*models.PreferencesResponse, error)) *MockUserPreferencesServiceInterface_GetPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePreferences provides a mock function with given fields: ctx, userID, req
func (_m *MockUserPreferencesServiceInterface) UpdatePreferences(ctx context.Context, userID string, req models.UpdatePreferencesRequest) (*models.PreferencesResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreferences")
	}

	var r0 *models.PreferencesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.UpdatePreferencesRequest) (*models.PreferencesResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.UpdatePreferencesRequest) *models.PreferencesResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PreferencesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.UpdatePreferencesRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserPreferencesServiceInterface_UpdatePreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePreferences'
type MockUserPreferencesServiceInterface_UpdatePreferences_Call struct {
	*mock.Call
}

// UpdatePreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req models.UpdatePreferencesRequest
func (_e *MockUserPreferencesServiceInterface_Expecter) UpdatePreferences(ctx interface{}, userID interface{}, req interface{}) *MockUserPreferencesServiceInterface_UpdatePreferences_Call {
	return &MockUserPreferencesServiceInterface_UpdatePreferences_Call{Call: _e.mock.On("UpdatePreferences", ctx, userID, req)}
}

func (_c *MockUserPreferencesServiceInterface_UpdatePreferences_Call) Run(run func(ctx context.Context, userID string, req models.UpdatePreferencesRequest)) *MockUserPreferencesServiceInterface_UpdatePreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.UpdatePreferencesRequest))
	})
	return _c
}

func (_c *MockUserPreferencesServiceInterface_UpdatePreferences_Call) Return(_a0 *models.PreferencesResponse, _a1 error) *MockUserPreferencesServiceInterface_UpdatePreferences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserPreferencesServiceInterface_UpdatePreferences_Call) RunAndReturn(run func(context.Context, string, models.UpdatePreferencesRequest) (*models.PreferencesResponse, error)) *MockUserPreferencesServiceInterface_UpdatePreferences_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserPreferencesServiceInterface creates a new instance of MockUserPreferencesServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserPreferencesServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserPreferencesServiceInterface {
	mock := &MockUserPreferencesServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
