// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockChunker is an autogenerated mock type for the Chunker type
type MockChunker struct {
	mock.Mock
}

type MockChunker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunker) EXPECT() *MockChunker_Expecter {
	return &MockChunker_Expecter{mock: &_m.Mock}
}

// Chunk provides a mock function with given fields: text
func (_m *MockChunker) Chunk(text string) []string {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for Chunk")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockChunker_Chunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chunk'
type MockChunker_Chunk_Call struct {
	*mock.Call
}

// Chunk is a helper method to define mock.On call
//   - text string
func (_e *MockChunker_Expecter) Chunk(text interface{}) *MockChunker_Chunk_Call {
	return &MockChunker_Chunk_Call{Call: _e.mock.On("Chunk", text)}
}

func (_c *MockChunker_Chunk_Call) Run(run func(text string)) *MockChunker_Chunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChunker_Chunk_Call) Return(_a0 []string) *MockChunker_Chunk_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChunker_Chunk_Call) RunAndReturn(run func(string) []string) *MockChunker_Chunk_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChunker creates a new instance of MockChunker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunker {
	mock := &MockChunker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
