// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAttachmentOwnerAuthorizer is an autogenerated mock type for the AttachmentOwnerAuthorizer type
type MockAttachmentOwnerAuthorizer struct {
	mock.Mock
}

type MockAttachmentOwnerAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttachmentOwnerAuthorizer) EXPECT() *MockAttachmentOwnerAuthorizer_Expecter {
	return &MockAttachmentOwnerAuthorizer_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, userID, teamID, ownerID
func (_m *MockAttachmentOwnerAuthorizer) Execute(ctx context.Context, userID string, teamID string, ownerID string) error {
	ret := _m.Called(ctx, userID, teamID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, teamID, ownerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttachmentOwnerAuthorizer_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAttachmentOwnerAuthorizer_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - ownerID string
func (_e *MockAttachmentOwnerAuthorizer_Expecter) Execute(ctx interface{}, userID interface{}, teamID interface{}, ownerID interface{}) *MockAttachmentOwnerAuthorizer_Execute_Call {
	return &MockAttachmentOwnerAuthorizer_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, teamID, ownerID)}
}

func (_c *MockAttachmentOwnerAuthorizer_Execute_Call) Run(run func(ctx context.Context, userID string, teamID string, ownerID string)) *MockAttachmentOwnerAuthorizer_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAttachmentOwnerAuthorizer_Execute_Call) Return(_a0 error) *MockAttachmentOwnerAuthorizer_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttachmentOwnerAuthorizer_Execute_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockAttachmentOwnerAuthorizer_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAttachmentOwnerAuthorizer creates a new instance of MockAttachmentOwnerAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttachmentOwnerAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttachmentOwnerAuthorizer {
	mock := &MockAttachmentOwnerAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
