// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"

	services "github.com/vibexp/vibexp/internal/services"
)

// MockTypeServiceInterface is an autogenerated mock type for the TypeServiceInterface type
type MockTypeServiceInterface struct {
	mock.Mock
}

type MockTypeServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTypeServiceInterface) EXPECT() *MockTypeServiceInterface_Expecter {
	return &MockTypeServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateCustom provides a mock function with given fields: ctx, params
func (_m *MockTypeServiceInterface) CreateCustom(ctx context.Context, params services.CreateTypeParams) (*models.Type, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustom")
	}

	var r0 *models.Type
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.CreateTypeParams) (*models.Type, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.CreateTypeParams) *models.Type); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Type)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.CreateTypeParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTypeServiceInterface_CreateCustom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustom'
type MockTypeServiceInterface_CreateCustom_Call struct {
	*mock.Call
}

// CreateCustom is a helper method to define mock.On call
//   - ctx context.Context
//   - params services.CreateTypeParams
func (_e *MockTypeServiceInterface_Expecter) CreateCustom(ctx interface{}, params interface{}) *MockTypeServiceInterface_CreateCustom_Call {
	return &MockTypeServiceInterface_CreateCustom_Call{Call: _e.mock.On("CreateCustom", ctx, params)}
}

func (_c *MockTypeServiceInterface_CreateCustom_Call) Run(run func(ctx context.Context, params services.CreateTypeParams)) *MockTypeServiceInterface_CreateCustom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.CreateTypeParams))
	})
	return _c
}

func (_c *MockTypeServiceInterface_CreateCustom_Call) Return(_a0 *models.Type, _a1 error) *MockTypeServiceInterface_CreateCustom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTypeServiceInterface_CreateCustom_Call) RunAndReturn(run func(context.Context, services.CreateTypeParams) (*models.Type, error)) *MockTypeServiceInterface_CreateCustom_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, teamID, id
func (_m *MockTypeServiceInterface) Delete(ctx context.Context, teamID string, id string) error {
	ret := _m.Called(ctx, teamID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, teamID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTypeServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTypeServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - id string
func (_e *MockTypeServiceInterface_Expecter) Delete(ctx interface{}, teamID interface{}, id interface{}) *MockTypeServiceInterface_Delete_Call {
	return &MockTypeServiceInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, teamID, id)}
}

func (_c *MockTypeServiceInterface_Delete_Call) Run(run func(ctx context.Context, teamID string, id string)) *MockTypeServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTypeServiceInterface_Delete_Call) Return(_a0 error) *MockTypeServiceInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTypeServiceInterface_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTypeServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, teamID, resourceType
func (_m *MockTypeServiceInterface) List(ctx context.Context, teamID string, resourceType string) ([]models.Type, error) {
	ret := _m.Called(ctx, teamID, resourceType)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Type
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]models.Type, error)); ok {
		return rf(ctx, teamID, resourceType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []models.Type); ok {
		r0 = rf(ctx, teamID, resourceType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Type)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, teamID, resourceType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTypeServiceInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTypeServiceInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - resourceType string
func (_e *MockTypeServiceInterface_Expecter) List(ctx interface{}, teamID interface{}, resourceType interface{}) *MockTypeServiceInterface_List_Call {
	return &MockTypeServiceInterface_List_Call{Call: _e.mock.On("List", ctx, teamID, resourceType)}
}

func (_c *MockTypeServiceInterface_List_Call) Run(run func(ctx context.Context, teamID string, resourceType string)) *MockTypeServiceInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTypeServiceInterface_List_Call) Return(_a0 []models.Type, _a1 error) *MockTypeServiceInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTypeServiceInterface_List_Call) RunAndReturn(run func(context.Context, string, string) ([]models.Type, error)) *MockTypeServiceInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateType provides a mock function with given fields: ctx, teamID, resourceType, slug
func (_m *MockTypeServiceInterface) ValidateType(ctx context.Context, teamID string, resourceType string, slug string) (bool, error) {
	ret := _m.Called(ctx, teamID, resourceType, slug)

	if len(ret) == 0 {
		panic("no return value specified for ValidateType")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, teamID, resourceType, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, teamID, resourceType, slug)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, teamID, resourceType, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTypeServiceInterface_ValidateType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateType'
type MockTypeServiceInterface_ValidateType_Call struct {
	*mock.Call
}

// ValidateType is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - resourceType string
//   - slug string
func (_e *MockTypeServiceInterface_Expecter) ValidateType(ctx interface{}, teamID interface{}, resourceType interface{}, slug interface{}) *MockTypeServiceInterface_ValidateType_Call {
	return &MockTypeServiceInterface_ValidateType_Call{Call: _e.mock.On("ValidateType", ctx, teamID, resourceType, slug)}
}

func (_c *MockTypeServiceInterface_ValidateType_Call) Run(run func(ctx context.Context, teamID string, resourceType string, slug string)) *MockTypeServiceInterface_ValidateType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTypeServiceInterface_ValidateType_Call) Return(_a0 bool, _a1 error) *MockTypeServiceInterface_ValidateType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTypeServiceInterface_ValidateType_Call) RunAndReturn(run func(context.Context, string, string, string) (bool, error)) *MockTypeServiceInterface_ValidateType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTypeServiceInterface creates a new instance of MockTypeServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTypeServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTypeServiceInterface {
	mock := &MockTypeServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
