// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/vibexp/vibexp/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockSearchServiceInterface is an autogenerated mock type for the SearchServiceInterface type
type MockSearchServiceInterface struct {
	mock.Mock
}

type MockSearchServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchServiceInterface) EXPECT() *MockSearchServiceInterface_Expecter {
	return &MockSearchServiceInterface_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: ctx, teamID, req
func (_m *MockSearchServiceInterface) Search(ctx context.Context, teamID string, req *models.SearchRequest) (*models.SearchResultsResponse, error) {
	ret := _m.Called(ctx, teamID, req)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *models.SearchResultsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.SearchRequest) (*models.SearchResultsResponse, error)); ok {
		return rf(ctx, teamID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.SearchRequest) *models.SearchResultsResponse); ok {
		r0 = rf(ctx, teamID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SearchResultsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.SearchRequest) error); ok {
		r1 = rf(ctx, teamID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchServiceInterface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSearchServiceInterface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - req *models.SearchRequest
func (_e *MockSearchServiceInterface_Expecter) Search(ctx interface{}, teamID interface{}, req interface{}) *MockSearchServiceInterface_Search_Call {
	return &MockSearchServiceInterface_Search_Call{Call: _e.mock.On("Search", ctx, teamID, req)}
}

func (_c *MockSearchServiceInterface_Search_Call) Run(run func(ctx context.Context, teamID string, req *models.SearchRequest)) *MockSearchServiceInterface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.SearchRequest))
	})
	return _c
}

func (_c *MockSearchServiceInterface_Search_Call) Return(_a0 *models.SearchResultsResponse, _a1 error) *MockSearchServiceInterface_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchServiceInterface_Search_Call) RunAndReturn(run func(context.Context, string, *models.SearchRequest) (*models.SearchResultsResponse, error)) *MockSearchServiceInterface_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchServiceInterface creates a new instance of MockSearchServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchServiceInterface {
	mock := &MockSearchServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
