// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/vibexp/vibexp/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockAPIKeyServiceInterface is an autogenerated mock type for the APIKeyServiceInterface type
type MockAPIKeyServiceInterface struct {
	mock.Mock
}

type MockAPIKeyServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyServiceInterface) EXPECT() *MockAPIKeyServiceInterface_Expecter {
	return &MockAPIKeyServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteAPIKey provides a mock function with given fields: ctx, userID, apiKeyID
func (_m *MockAPIKeyServiceInterface) DeleteAPIKey(ctx context.Context, userID string, apiKeyID string) error {
	ret := _m.Called(ctx, userID, apiKeyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAPIKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, apiKeyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPIKeyServiceInterface_DeleteAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAPIKey'
type MockAPIKeyServiceInterface_DeleteAPIKey_Call struct {
	*mock.Call
}

// DeleteAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - apiKeyID string
func (_e *MockAPIKeyServiceInterface_Expecter) DeleteAPIKey(ctx interface{}, userID interface{}, apiKeyID interface{}) *MockAPIKeyServiceInterface_DeleteAPIKey_Call {
	return &MockAPIKeyServiceInterface_DeleteAPIKey_Call{Call: _e.mock.On("DeleteAPIKey", ctx, userID, apiKeyID)}
}

func (_c *MockAPIKeyServiceInterface_DeleteAPIKey_Call) Run(run func(ctx context.Context, userID string, apiKeyID string)) *MockAPIKeyServiceInterface_DeleteAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAPIKeyServiceInterface_DeleteAPIKey_Call) Return(_a0 error) *MockAPIKeyServiceInterface_DeleteAPIKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIKeyServiceInterface_DeleteAPIKey_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAPIKeyServiceInterface_DeleteAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAPIKey provides a mock function with given fields: ctx, userID, name, integrationCodes
func (_m *MockAPIKeyServiceInterface) GenerateAPIKey(ctx context.Context, userID string, name string, integrationCodes []string) (*models.APIKey, string, error) {
	ret := _m.Called(ctx, userID, name, integrationCodes)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAPIKey")
	}

	var r0 *models.APIKey
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) (*models.APIKey, string, error)); ok {
		return rf(ctx, userID, name, integrationCodes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) *models.APIKey); ok {
		r0 = rf(ctx, userID, name, integrationCodes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string) string); ok {
		r1 = rf(ctx, userID, name, integrationCodes)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, []string) error); ok {
		r2 = rf(ctx, userID, name, integrationCodes)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAPIKeyServiceInterface_GenerateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAPIKey'
type MockAPIKeyServiceInterface_GenerateAPIKey_Call struct {
	*mock.Call
}

// GenerateAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - integrationCodes []string
func (_e *MockAPIKeyServiceInterface_Expecter) GenerateAPIKey(ctx interface{}, userID interface{}, name interface{}, integrationCodes interface{}) *MockAPIKeyServiceInterface_GenerateAPIKey_Call {
	return &MockAPIKeyServiceInterface_GenerateAPIKey_Call{Call: _e.mock.On("GenerateAPIKey", ctx, userID, name, integrationCodes)}
}

func (_c *MockAPIKeyServiceInterface_GenerateAPIKey_Call) Run(run func(ctx context.Context, userID string, name string, integrationCodes []string)) *MockAPIKeyServiceInterface_GenerateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockAPIKeyServiceInterface_GenerateAPIKey_Call) Return(_a0 *models.APIKey, _a1 string, _a2 error) *MockAPIKeyServiceInterface_GenerateAPIKey_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAPIKeyServiceInterface_GenerateAPIKey_Call) RunAndReturn(run func(context.Context, string, string, []string) (*models.APIKey, string, error)) *MockAPIKeyServiceInterface_GenerateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAPIKeyLegacy provides a mock function with given fields: ctx, userID, name, usageType
func (_m *MockAPIKeyServiceInterface) GenerateAPIKeyLegacy(ctx context.Context, userID string, name string, usageType string) (*models.APIKey, string, error) {
	ret := _m.Called(ctx, userID, name, usageType)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAPIKeyLegacy")
	}

	var r0 *models.APIKey
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.APIKey, string, error)); ok {
		return rf(ctx, userID, name, usageType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.APIKey); ok {
		r0 = rf(ctx, userID, name, usageType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) string); ok {
		r1 = rf(ctx, userID, name, usageType)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, userID, name, usageType)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAPIKeyServiceInterface_GenerateAPIKeyLegacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAPIKeyLegacy'
type MockAPIKeyServiceInterface_GenerateAPIKeyLegacy_Call struct {
	*mock.Call
}

// GenerateAPIKeyLegacy is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - usageType string
func (_e *MockAPIKeyServiceInterface_Expecter) GenerateAPIKeyLegacy(ctx interface{}, userID interface{}, name interface{}, usageType interface{}) *MockAPIKeyServiceInterface_GenerateAPIKeyLegacy_Call {
	return &MockAPIKeyServiceInterface_GenerateAPIKeyLegacy_Call{Call: _e.mock.On("GenerateAPIKeyLegacy", ctx, userID, name, usageType)}
}

func (_c *MockAPIKeyServiceInterface_GenerateAPIKeyLegacy_Call) Run(run func(ctx context.Context, userID string, name string, usageType string)) *MockAPIKeyServiceInterface_GenerateAPIKeyLegacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAPIKeyServiceInterface_GenerateAPIKeyLegacy_Call) Return(_a0 *models.APIKey, _a1 string, _a2 error) *MockAPIKeyServiceInterface_GenerateAPIKeyLegacy_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAPIKeyServiceInterface_GenerateAPIKeyLegacy_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.APIKey, string, error)) *MockAPIKeyServiceInterface_GenerateAPIKeyLegacy_Call {
	_c.Call.Return(run)
	return _c
}

// GetAPIKeysByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAPIKeyServiceInterface) GetAPIKeysByUserID(ctx context.Context, userID string) ([]models.APIKey, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAPIKeysByUserID")
	}

	var r0 []models.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.APIKey, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.APIKey); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyServiceInterface_GetAPIKeysByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIKeysByUserID'
type MockAPIKeyServiceInterface_GetAPIKeysByUserID_Call struct {
	*mock.Call
}

// GetAPIKeysByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAPIKeyServiceInterface_Expecter) GetAPIKeysByUserID(ctx interface{}, userID interface{}) *MockAPIKeyServiceInterface_GetAPIKeysByUserID_Call {
	return &MockAPIKeyServiceInterface_GetAPIKeysByUserID_Call{Call: _e.mock.On("GetAPIKeysByUserID", ctx, userID)}
}

func (_c *MockAPIKeyServiceInterface_GetAPIKeysByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAPIKeyServiceInterface_GetAPIKeysByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyServiceInterface_GetAPIKeysByUserID_Call) Return(_a0 []models.APIKey, _a1 error) *MockAPIKeyServiceInterface_GetAPIKeysByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyServiceInterface_GetAPIKeysByUserID_Call) RunAndReturn(run func(context.Context, string) ([]models.APIKey, error)) *MockAPIKeyServiceInterface_GetAPIKeysByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAPIKey provides a mock function with given fields: ctx, key
func (_m *MockAPIKeyServiceInterface) ValidateAPIKey(ctx context.Context, key string) (*models.APIKey, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAPIKey")
	}

	var r0 *models.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.APIKey, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.APIKey); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyServiceInterface_ValidateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAPIKey'
type MockAPIKeyServiceInterface_ValidateAPIKey_Call struct {
	*mock.Call
}

// ValidateAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAPIKeyServiceInterface_Expecter) ValidateAPIKey(ctx interface{}, key interface{}) *MockAPIKeyServiceInterface_ValidateAPIKey_Call {
	return &MockAPIKeyServiceInterface_ValidateAPIKey_Call{Call: _e.mock.On("ValidateAPIKey", ctx, key)}
}

func (_c *MockAPIKeyServiceInterface_ValidateAPIKey_Call) Run(run func(ctx context.Context, key string)) *MockAPIKeyServiceInterface_ValidateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyServiceInterface_ValidateAPIKey_Call) Return(_a0 *models.APIKey, _a1 error) *MockAPIKeyServiceInterface_ValidateAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyServiceInterface_ValidateAPIKey_Call) RunAndReturn(run func(context.Context, string) (*models.APIKey, error)) *MockAPIKeyServiceInterface_ValidateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAPIKeyForIntegration provides a mock function with given fields: ctx, key, integrationCode
func (_m *MockAPIKeyServiceInterface) ValidateAPIKeyForIntegration(ctx context.Context, key string, integrationCode string) (*models.APIKey, error) {
	ret := _m.Called(ctx, key, integrationCode)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAPIKeyForIntegration")
	}

	var r0 *models.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.APIKey, error)); ok {
		return rf(ctx, key, integrationCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.APIKey); ok {
		r0 = rf(ctx, key, integrationCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, integrationCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyServiceInterface_ValidateAPIKeyForIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAPIKeyForIntegration'
type MockAPIKeyServiceInterface_ValidateAPIKeyForIntegration_Call struct {
	*mock.Call
}

// ValidateAPIKeyForIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - integrationCode string
func (_e *MockAPIKeyServiceInterface_Expecter) ValidateAPIKeyForIntegration(ctx interface{}, key interface{}, integrationCode interface{}) *MockAPIKeyServiceInterface_ValidateAPIKeyForIntegration_Call {
	return &MockAPIKeyServiceInterface_ValidateAPIKeyForIntegration_Call{Call: _e.mock.On("ValidateAPIKeyForIntegration", ctx, key, integrationCode)}
}

func (_c *MockAPIKeyServiceInterface_ValidateAPIKeyForIntegration_Call) Run(run func(ctx context.Context, key string, integrationCode string)) *MockAPIKeyServiceInterface_ValidateAPIKeyForIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAPIKeyServiceInterface_ValidateAPIKeyForIntegration_Call) Return(_a0 *models.APIKey, _a1 error) *MockAPIKeyServiceInterface_ValidateAPIKeyForIntegration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyServiceInterface_ValidateAPIKeyForIntegration_Call) RunAndReturn(run func(context.Context, string, string) (*models.APIKey, error)) *MockAPIKeyServiceInterface_ValidateAPIKeyForIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIKeyServiceInterface creates a new instance of MockAPIKeyServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyServiceInterface {
	mock := &MockAPIKeyServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
