// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"

	services "github.com/vibexp/vibexp/internal/services"
)

// MockTeamSettingsAuditServiceInterface is an autogenerated mock type for the TeamSettingsAuditServiceInterface type
type MockTeamSettingsAuditServiceInterface struct {
	mock.Mock
}

type MockTeamSettingsAuditServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamSettingsAuditServiceInterface) EXPECT() *MockTeamSettingsAuditServiceInterface_Expecter {
	return &MockTeamSettingsAuditServiceInterface_Expecter{mock: &_m.Mock}
}

// ListAudit provides a mock function with given fields: ctx, userID, teamID, page, limit
func (_m *MockTeamSettingsAuditServiceInterface) ListAudit(ctx context.Context, userID string, teamID string, page int, limit int) (*models.TeamSettingsAuditPage, error) {
	ret := _m.Called(ctx, userID, teamID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListAudit")
	}

	var r0 *models.TeamSettingsAuditPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) (*models.TeamSettingsAuditPage, error)); ok {
		return rf(ctx, userID, teamID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) *models.TeamSettingsAuditPage); ok {
		r0 = rf(ctx, userID, teamID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamSettingsAuditPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, userID, teamID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamSettingsAuditServiceInterface_ListAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAudit'
type MockTeamSettingsAuditServiceInterface_ListAudit_Call struct {
	*mock.Call
}

// ListAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - teamID string
//   - page int
//   - limit int
func (_e *MockTeamSettingsAuditServiceInterface_Expecter) ListAudit(ctx interface{}, userID interface{}, teamID interface{}, page interface{}, limit interface{}) *MockTeamSettingsAuditServiceInterface_ListAudit_Call {
	return &MockTeamSettingsAuditServiceInterface_ListAudit_Call{Call: _e.mock.On("ListAudit", ctx, userID, teamID, page, limit)}
}

func (_c *MockTeamSettingsAuditServiceInterface_ListAudit_Call) Run(run func(ctx context.Context, userID string, teamID string, page int, limit int)) *MockTeamSettingsAuditServiceInterface_ListAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockTeamSettingsAuditServiceInterface_ListAudit_Call) Return(_a0 *models.TeamSettingsAuditPage, _a1 error) *MockTeamSettingsAuditServiceInterface_ListAudit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamSettingsAuditServiceInterface_ListAudit_Call) RunAndReturn(run func(context.Context, string, string, int, int) (*models.TeamSettingsAuditPage, error)) *MockTeamSettingsAuditServiceInterface_ListAudit_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function with given fields: ctx, record
func (_m *MockTeamSettingsAuditServiceInterface) Record(ctx context.Context, record services.TeamSettingsAuditRecord) (*models.TeamSettingsAudit, error) {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 *models.TeamSettingsAudit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.TeamSettingsAuditRecord) (*models.TeamSettingsAudit, error)); ok {
		return rf(ctx, record)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.TeamSettingsAuditRecord) *models.TeamSettingsAudit); ok {
		r0 = rf(ctx, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamSettingsAudit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.TeamSettingsAuditRecord) error); ok {
		r1 = rf(ctx, record)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamSettingsAuditServiceInterface_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockTeamSettingsAuditServiceInterface_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - record services.TeamSettingsAuditRecord
func (_e *MockTeamSettingsAuditServiceInterface_Expecter) Record(ctx interface{}, record interface{}) *MockTeamSettingsAuditServiceInterface_Record_Call {
	return &MockTeamSettingsAuditServiceInterface_Record_Call{Call: _e.mock.On("Record", ctx, record)}
}

func (_c *MockTeamSettingsAuditServiceInterface_Record_Call) Run(run func(ctx context.Context, record services.TeamSettingsAuditRecord)) *MockTeamSettingsAuditServiceInterface_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.TeamSettingsAuditRecord))
	})
	return _c
}

func (_c *MockTeamSettingsAuditServiceInterface_Record_Call) Return(_a0 *models.TeamSettingsAudit, _a1 error) *MockTeamSettingsAuditServiceInterface_Record_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamSettingsAuditServiceInterface_Record_Call) RunAndReturn(run func(context.Context, services.TeamSettingsAuditRecord) (*models.TeamSettingsAudit, error)) *MockTeamSettingsAuditServiceInterface_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamSettingsAuditServiceInterface creates a new instance of MockTeamSettingsAuditServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamSettingsAuditServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamSettingsAuditServiceInterface {
	mock := &MockTeamSettingsAuditServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
