// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"

	time "time"
)

// MockBackofficeServiceInterface is an autogenerated mock type for the BackofficeServiceInterface type
type MockBackofficeServiceInterface struct {
	mock.Mock
}

type MockBackofficeServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackofficeServiceInterface) EXPECT() *MockBackofficeServiceInterface_Expecter {
	return &MockBackofficeServiceInterface_Expecter{mock: &_m.Mock}
}

// GetUsageAndGrowth provides a mock function with given fields: ctx, fromDate, toDate
func (_m *MockBackofficeServiceInterface) GetUsageAndGrowth(ctx context.Context, fromDate *time.Time, toDate *time.Time) (*models.UsageAndGrowthResponse, error) {
	ret := _m.Called(ctx, fromDate, toDate)

	if len(ret) == 0 {
		panic("no return value specified for GetUsageAndGrowth")
	}

	var r0 *models.UsageAndGrowthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) (*models.UsageAndGrowthResponse, error)); ok {
		return rf(ctx, fromDate, toDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) *models.UsageAndGrowthResponse); ok {
		r0 = rf(ctx, fromDate, toDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UsageAndGrowthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time) error); ok {
		r1 = rf(ctx, fromDate, toDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBackofficeServiceInterface_GetUsageAndGrowth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsageAndGrowth'
type MockBackofficeServiceInterface_GetUsageAndGrowth_Call struct {
	*mock.Call
}

// GetUsageAndGrowth is a helper method to define mock.On call
//   - ctx context.Context
//   - fromDate *time.Time
//   - toDate *time.Time
func (_e *MockBackofficeServiceInterface_Expecter) GetUsageAndGrowth(ctx interface{}, fromDate interface{}, toDate interface{}) *MockBackofficeServiceInterface_GetUsageAndGrowth_Call {
	return &MockBackofficeServiceInterface_GetUsageAndGrowth_Call{Call: _e.mock.On("GetUsageAndGrowth", ctx, fromDate, toDate)}
}

func (_c *MockBackofficeServiceInterface_GetUsageAndGrowth_Call) Run(run func(ctx context.Context, fromDate *time.Time, toDate *time.Time)) *MockBackofficeServiceInterface_GetUsageAndGrowth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*time.Time), args[2].(*time.Time))
	})
	return _c
}

func (_c *MockBackofficeServiceInterface_GetUsageAndGrowth_Call) Return(_a0 *models.UsageAndGrowthResponse, _a1 error) *MockBackofficeServiceInterface_GetUsageAndGrowth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackofficeServiceInterface_GetUsageAndGrowth_Call) RunAndReturn(run func(context.Context, *time.Time, *time.Time) (*models.UsageAndGrowthResponse, error)) *MockBackofficeServiceInterface_GetUsageAndGrowth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBackofficeServiceInterface creates a new instance of MockBackofficeServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackofficeServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackofficeServiceInterface {
	mock := &MockBackofficeServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
