// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	services "github.com/vibexp/vibexp/internal/services"
)

// MockEmailSenderResolver is an autogenerated mock type for the EmailSenderResolver type
type MockEmailSenderResolver struct {
	mock.Mock
}

type MockEmailSenderResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailSenderResolver) EXPECT() *MockEmailSenderResolver_Expecter {
	return &MockEmailSenderResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx, teamID
func (_m *MockEmailSenderResolver) Resolve(ctx context.Context, teamID string) (*services.ResolvedEmailSender, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 *services.ResolvedEmailSender
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*services.ResolvedEmailSender, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *services.ResolvedEmailSender); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ResolvedEmailSender)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmailSenderResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockEmailSenderResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
func (_e *MockEmailSenderResolver_Expecter) Resolve(ctx interface{}, teamID interface{}) *MockEmailSenderResolver_Resolve_Call {
	return &MockEmailSenderResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, teamID)}
}

func (_c *MockEmailSenderResolver_Resolve_Call) Run(run func(ctx context.Context, teamID string)) *MockEmailSenderResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmailSenderResolver_Resolve_Call) Return(_a0 *services.ResolvedEmailSender, _a1 error) *MockEmailSenderResolver_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmailSenderResolver_Resolve_Call) RunAndReturn(run func(context.Context, string) (*services.ResolvedEmailSender, error)) *MockEmailSenderResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailSenderResolver creates a new instance of MockEmailSenderResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailSenderResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailSenderResolver {
	mock := &MockEmailSenderResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
