// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/vibexp/vibexp/internal/models"
)

// MockAdminServiceInterface is an autogenerated mock type for the AdminServiceInterface type
type MockAdminServiceInterface struct {
	mock.Mock
}

type MockAdminServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminServiceInterface) EXPECT() *MockAdminServiceInterface_Expecter {
	return &MockAdminServiceInterface_Expecter{mock: &_m.Mock}
}

// GetInstanceCounts provides a mock function with given fields: ctx
func (_m *MockAdminServiceInterface) GetInstanceCounts(ctx context.Context) (models.InstanceCounts, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetInstanceCounts")
	}

	var r0 models.InstanceCounts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (models.InstanceCounts, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) models.InstanceCounts); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.InstanceCounts)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminServiceInterface_GetInstanceCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstanceCounts'
type MockAdminServiceInterface_GetInstanceCounts_Call struct {
	*mock.Call
}

// GetInstanceCounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminServiceInterface_Expecter) GetInstanceCounts(ctx interface{}) *MockAdminServiceInterface_GetInstanceCounts_Call {
	return &MockAdminServiceInterface_GetInstanceCounts_Call{Call: _e.mock.On("GetInstanceCounts", ctx)}
}

func (_c *MockAdminServiceInterface_GetInstanceCounts_Call) Run(run func(ctx context.Context)) *MockAdminServiceInterface_GetInstanceCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminServiceInterface_GetInstanceCounts_Call) Return(_a0 models.InstanceCounts, _a1 error) *MockAdminServiceInterface_GetInstanceCounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminServiceInterface_GetInstanceCounts_Call) RunAndReturn(run func(context.Context) (models.InstanceCounts, error)) *MockAdminServiceInterface_GetInstanceCounts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminServiceInterface creates a new instance of MockAdminServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminServiceInterface {
	mock := &MockAdminServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
